/* ══════════════════════════════════════════════════════════════════════
   知識點資料：題本有附的公式（仍需熟到能立即辨認與使用）
   ══════════════════════════════════════════════════════════════════════ */
function card(o){
  return {
    id:o.id, grade:o.grade, category:o.category, kind:o.kind || 'formula',
    title:o.title, formula:o.formula || '',
    variables:o.variables || [], usageConditions:o.usageConditions || '',
    triggerWords:o.triggerWords || [], commonMistakes:o.commonMistakes || [],
    attachedInExam:!!o.attachedInExam,
    diagramType:o.diagramType || null, diagramData:o.diagramData || null,
    diagramExtra:o.diagramExtra || null,
    recallPrompt:o.recall,
    /* 題庫：重複練同一張卡時輪流出題，避免背住單一題的答案 */
    recognitionQuestions:[o.recog].concat(o.recogMore || []),
    applicationQuestions:[o.apply].concat(o.applyMore || []),
    recognitionQuestion:o.recog, applicationQuestion:o.apply,
    workedExample:o.worked, explanation:o.explain || '', sourceNote:o.source || ''
  };
}
var ATTACHED = [

card({id:'A1', grade:8, category:'num', attachedInExam:true, title:'和的平方公式',
  formula:'(a+b)^2=a^2+2ab+b^2',
  variables:[{sym:'a', desc:'括號裡的第一項'}, {sym:'b', desc:'括號裡的第二項'}],
  usageConditions:'兩項相加後整體平方，或要把 a²+2ab+b² 收回成完全平方式時使用。',
  triggerWords:['展開', '完全平方', '（　＋　）²', '因式分解'],
  commonMistakes:['寫成 a²+b²，漏掉中間的 2ab', '2ab 忘記乘 2', 'b 是分數或帶負號時忘記整個平方'],
  recall:{type:'blank', prompt:'把和的平方公式補完整。',
    template:'(a+b)^2=a^2+@1+@2', blanks:['2ab', 'b^2'],
    bank:['2ab', 'b^2', 'ab', '2b^2', 'a^2b^2'],
    anyOrder:true,
    hint1:'中間項是「兩項相乘再乘 2」，最後一項是尾項自己平方。'},
  recog:{type:'choice', prompt:'下列哪一個算式最適合直接套用「和的平方公式」？',
    options:[{math:'(x+5)^2'}, {math:'(x+5)(x-5)'}, {math:'x^2-25'}, {math:'(x-5)^2'}],
    answer:0, hint1:'先看括號裡是加還是減，再看是不是整體平方。',
    why:'(x+5)² 是兩項「相加」後整體平方，正好是 (a+b)² 的樣子；(x−5)² 要用差的平方，另外兩個是平方差。'},
  apply:{type:'numeric', prompt:'展開 (x+3)² 之後，一次項（x 項）的係數是多少？',
    given:'(x+3)^2', answer:'6', unit:'',
    hint1:'對照公式，a = x、b = 3，中間項是 2ab。',
    steps:['a = x、b = 3', '中間項 2ab = 2 × x × 3 = 6x', '所以一次項係數是 6']},
  recogMore:[{type:'choice', prompt:'x² + 8x + 16 是下列哪一個式子展開的結果？',
    options:[{math:'(x+4)^2'}, {math:'(x+8)^2'}, {math:'(x+4)(x-4)'}, {math:'(x+2)^2'}],
    answer:0, hint1:'16 是幾的平方？中間項 8x 是不是它的 2 倍？',
    why:'16 = 4²，中間項 2·x·4 = 8x，完全符合 (x+4)²。'}],
  applyMore:[
    {type:'numeric', prompt:'用 (20+1)² 計算 21²，答案是多少？',
     given:'21^2=(20+1)^2', answer:'441', unit:'', hint1:'400 + 2×20×1 + 1。',
     steps:['21² = (20 + 1)²', '= 400 + 40 + 1', '= 441']},
    {type:'numeric', prompt:'展開 (2x+5)² 之後，常數項是多少？',
     given:'(2x+5)^2', answer:'25', unit:'', hint1:'常數項就是尾項 5 的平方。',
     steps:['a = 2x、b = 5', '常數項 = b² = 5² = 25', '（完整展開為 4x² + 20x + 25）']}],
  worked:{title:'展開 (x+3)²', given:'(x+3)^2',
    steps:[{label:'對照公式', text:'a = x，b = 3'},
           {label:'代入', math:'(x+3)^2=x^2+2\\cdot x\\cdot 3+3^2'},
           {label:'整理', math:'=x^2+6x+9'}],
    answer:'x^2+6x+9'},
  explain:'a、b 各代表括號內的一項。展開後固定有三項：頭項平方 a²、兩項乘積的兩倍 2ab、尾項平方 b²。',
  source:'題本附錄公式表'}),

card({id:'A2', grade:8, category:'num', attachedInExam:true, title:'差的平方公式',
  formula:'(a-b)^2=a^2-2ab+b^2',
  variables:[{sym:'a', desc:'被減的那一項'}, {sym:'b', desc:'減去的那一項'}],
  usageConditions:'兩項相減後整體平方時使用；注意只有中間項是負的。',
  triggerWords:['展開', '完全平方', '（　－　）²'],
  commonMistakes:['最後一項寫成 −b²（b² 一定是正的）', '中間項忘記負號', '把 (a−b)² 當成 a²−b²'],
  recall:{type:'blank', prompt:'把差的平方公式補完整。',
    template:'(a-b)^2=a^2@1+@2', blanks:['-2ab', 'b^2'],
    bank:['-2ab', 'b^2', '+2ab', '-b^2', '-ab'],
    hint1:'只有中間那一項會變號，最後一項平方之後一定是正的。'},
  recog:{type:'choice', prompt:'把 x²−10x+25 因式分解，應該想到哪一個公式？',
    options:[{t:'差的平方 (a−b)²'}, {t:'和的平方 (a+b)²'}, {t:'平方差 a²−b²'}, {t:'一元二次公式解'}],
    answer:0, hint1:'頭尾都是完全平方數，看中間項的正負號。',
    why:'x² 與 25 = 5² 都是平方項，中間 −10x = −2·x·5 是負的，所以是 (x−5)²。'},
  apply:{type:'numeric', prompt:'計算 98² 時，把 98 看成 100−2，展開後常數項 b² 是多少？',
    given:'98^2=(100-2)^2', answer:'4', unit:'',
    hint1:'a = 100、b = 2，最後一項是 b²。',
    steps:['98 = 100 − 2，所以 a = 100、b = 2', 'b² = 2² = 4', '（完整結果為 10000 − 400 + 4 = 9604）']},
  recogMore:[{type:'choice', prompt:'下列哪一個是完全平方式？',
    options:[{math:'x^2-6x+9'}, {math:'x^2-6x+6'}, {math:'x^2-6x-9'}, {math:'x^2+6x-9'}],
    answer:0, hint1:'頭尾要都是平方數，中間項要是兩底乘積的 2 倍。',
    why:'x² 與 9 = 3² 都是平方，中間 −6x = −2·x·3，所以是 (x−3)²。'}],
  applyMore:[
    {type:'numeric', prompt:'展開 (x−7)² 之後，一次項（x 項）的係數是多少？',
     given:'(x-7)^2', answer:'-14', unit:'', hint1:'中間項是 −2ab，a = x、b = 7。',
     steps:['a = x、b = 7', '中間項 = −2 × x × 7 = −14x', '係數是 −14']},
    {type:'choice', prompt:'把 x² − 12x + 36 因式分解，結果是？',
     given:'x^2-12x+36', options:[{math:'(x-6)^2'}, {math:'(x+6)^2'},
       {math:'(x-6)(x+6)'}, {math:'(x-12)^2'}],
     answer:0, unit:'', hint1:'36 = 6²，中間 −12x = −2·x·6。',
     steps:['頭尾都是平方：x² 與 6²', '中間 −12x = −2 × x × 6', '所以是 (x − 6)²']}],
  worked:{title:'用差的平方算 98²', given:'98^2',
    steps:[{label:'改寫', math:'98^2=(100-2)^2'},
           {label:'套公式', math:'=100^2-2\\cdot 100\\cdot 2+2^2'},
           {label:'計算', math:'=10000-400+4'},
           {label:'得答案', math:'=9604'}],
    answer:'9604'},
  explain:'和差平方只有中間項不同：相加時中間是 +2ab，相減時中間是 −2ab。頭尾兩項永遠是正的平方。',
  source:'題本附錄公式表'}),

card({id:'A3', grade:8, category:'num', attachedInExam:true, title:'平方差公式',
  formula:'a^2-b^2=(a+b)(a-b)',
  variables:[{sym:'a', desc:'第一個平方項的底'}, {sym:'b', desc:'第二個平方項的底'}],
  usageConditions:'看到「平方減平方」，或看到 (甲＋乙)(甲－乙) 的乘積時使用。',
  triggerWords:['因式分解', '平方差', '兩數相乘', '簡算'],
  commonMistakes:['把 a²−b² 拆成 (a−b)²', '只有相減才能用，a²+b² 不能分解', '忘記檢查兩項是不是都是平方'],
  recall:{type:'blank', prompt:'把平方差公式補完整。',
    template:'a^2-b^2=@1@2', blanks:['(a+b)', '(a-b)'],
    bank:['(a+b)', '(a-b)', '(a^2+b^2)', '(a-b)^2'],
    anyOrder:true,
    hint1:'答案是兩個括號相乘，一個放加號、一個放減號。'},
  recog:{type:'choice', prompt:'下列哪一個可以用平方差公式因式分解？',
    options:[{math:'x^2-49'}, {math:'x^2+49'}, {math:'x^2-7x'}, {math:'x^2+14x+49'}],
    answer:0, hint1:'兩項都要是完全平方，中間必須是減號。',
    why:'x²−49 = x²−7²，符合「平方減平方」；x²+49 是相加不能分解，另外兩個要用提公因式或完全平方。'},
  apply:{type:'numeric', prompt:'用平方差公式計算 51 × 49 = ？',
    given:'51\\times 49=(50+1)(50-1)', answer:'2499', unit:'',
    hint1:'兩數的平均是 50，差是 1，寫成 (50+1)(50−1)。',
    steps:['51 × 49 = (50 + 1)(50 − 1)', '= 50² − 1²', '= 2500 − 1 = 2499']},
  recogMore:[{type:'choice', prompt:'下列哪一個「不能」用平方差公式分解？',
    options:[{math:'x^2+16'}, {math:'x^2-16'}, {math:'4x^2-9'}, {math:'25-y^2'}],
    answer:0, hint:'', hint1:'平方差一定是「減」，相加不能分解。',
    why:'x² + 16 是兩個平方相加，在國中範圍內不能因式分解；其餘三個都是平方減平方。'}],
  applyMore:[
    {type:'choice', prompt:'把 x² − 36 因式分解，結果是？',
     given:'x^2-36', options:[{math:'(x+6)(x-6)'}, {math:'(x-6)^2'},
       {math:'(x+36)(x-1)'}, {math:'(x+6)^2'}],
     answer:0, unit:'', hint1:'36 = 6²，套 a² − b² = (a+b)(a−b)。',
     steps:['x² − 36 = x² − 6²', '= (x + 6)(x − 6)']},
    {type:'numeric', prompt:'用平方差公式計算 103 × 97 = ？',
     given:'103\\times 97=(100+3)(100-3)', answer:'9991', unit:'',
     hint1:'兩數的平均是 100，各差 3。',
     steps:['103 × 97 = (100 + 3)(100 − 3)', '= 100² − 3²', '= 10000 − 9 = 9991']}],
  worked:{title:'用平方差簡算 51 × 49', given:'51\\times 49',
    steps:[{label:'找出中心值', text:'51 與 49 的中間值是 50，各差 1'},
           {label:'改寫', math:'51\\times 49=(50+1)(50-1)'},
           {label:'套公式', math:'=50^2-1^2'},
           {label:'計算', math:'=2500-1=2499'}],
    answer:'2499'},
  explain:'a²−b² 一定可以拆成兩個括號：一個是兩底相加，一個是兩底相減。反過來，看到 (甲＋乙)(甲－乙) 也可以直接算成甲²−乙²。',
  source:'題本附錄公式表'}),

card({id:'A4', grade:8, category:'geo', attachedInExam:true, title:'勾股定理（畢氏定理）',
  formula:'c^2=a^2+b^2',
  variables:[{sym:'a', desc:'直角的一股'}, {sym:'b', desc:'直角的另一股'}, {sym:'c', desc:'斜邊，直角所對的邊'}],
  usageConditions:'題目中出現直角、垂直、長方形對角線、高、坐標距離時使用。必須先確定哪一邊是斜邊。',
  triggerWords:['直角', '垂直', '斜邊', '對角線', '梯子', '影子'],
  commonMistakes:['把斜邊當成一股', '算完忘記開根號', '沒有直角就亂用'],
  diagramType:'SpecialRightTriangleDiagram', diagramData:{variant:'pythagoras'},
  recall:{type:'blank', prompt:'補完勾股定理（c 為斜邊）。',
    template:'c^2=@1+@2', blanks:['a^2', 'b^2'],
    bank:['a^2', 'b^2', '2ab', 'ab'],
    anyOrder:true,
    hint1:'斜邊的平方等於兩股平方的和。'},
  recog:{type:'choice', prompt:'哪一種情境「不能」直接用勾股定理？',
    options:[{t:'三邊長 5、6、7 的一般三角形'}, {t:'長方形的對角線'},
             {t:'等腰三角形作高後的一半'}, {t:'坐標平面上兩點的距離'}],
    answer:0, hint1:'一定要先找到直角。',
    why:'勾股定理只在直角三角形成立。長方形對角線、作高、坐標距離都會出現直角，一般三角形沒有直角就不能用。'},
  apply:{type:'numeric', prompt:'直角三角形兩股長 6 與 8，斜邊長是多少？',
    given:'a=6,\\ b=8', answer:'10', unit:'',
    hint1:'先把兩股平方相加，再開根號。',
    steps:['c² = 6² + 8² = 36 + 64 = 100', 'c = √100 = 10']},
  recogMore:[{type:'choice', prompt:'三邊長 5、12、13 的三角形是什麼三角形？',
    options:[{t:'直角三角形'}, {t:'銳角三角形'}, {t:'鈍角三角形'}, {t:'正三角形'}],
    answer:0, hint1:'檢查最長邊的平方是否等於另外兩邊平方和。',
    why:'5² + 12² = 25 + 144 = 169 = 13²，符合勾股定理的逆敘述，所以是直角三角形。'}],
  applyMore:[
    {type:'numeric', prompt:'直角三角形斜邊長 13、一股長 5，另一股長是多少？',
     given:'c=13,\\ a=5', answer:'12', unit:'', hint1:'求股要改寫成 b² = c² − a²。',
     steps:['b² = 13² − 5² = 169 − 25 = 144', 'b = √144 = 12']},
    {type:'numeric', prompt:'長 12、寬 9 的長方形，對角線長是多少？',
     given:'12,\\ 9', answer:'15', unit:'', hint1:'長、寬與對角線構成直角三角形。',
     steps:['對角線² = 12² + 9² = 144 + 81 = 225', '對角線 = √225 = 15']}],
  worked:{title:'兩股 6、8 求斜邊', given:'a=6,\\ b=8',
    steps:[{label:'確認斜邊', text:'6 與 8 夾直角，所以第三邊 c 是斜邊'},
           {label:'代入', math:'c^2=6^2+8^2'},
           {label:'計算', math:'c^2=36+64=100'},
           {label:'開根號', math:'c=\\sqrt{100}=10'}],
    answer:'10'},
  explain:'c 一定是直角所對的最長邊。等號左邊只放斜邊的平方，右邊放兩股的平方和。求股時要改寫成 a² = c² − b²。',
  source:'題本附錄公式表'}),

card({id:'A5', grade:7, category:'geo', attachedInExam:true, title:'圓周長',
  formula:'\\text{圓周長}=2\\pi r',
  variables:[{sym:'r', desc:'圓的半徑'}, {sym:'π', desc:'圓周率，題目通常直接保留 π'}],
  usageConditions:'求繞圓一圈的長度、滾動一圈走的距離、圓形跑道長度時使用。',
  triggerWords:['一圈', '繞一周', '滾動', '周長', '鐵絲圍'],
  commonMistakes:['把直徑當半徑，多乘一次 2', '周長與面積公式混用', '半圓忘記加上直徑'],
  diagramType:'SectorDiagram', diagramData:{full:true, mode:'circumference'},
  recall:{type:'blank', prompt:'補完圓周長公式。',
    template:'\\text{圓周長}=@1', blanks:['2\\pi r'],
    bank:['2\\pi r', '\\pi r^2', '\\pi r', '2\\pi r^2'],
    hint1:'周長是長度，r 只出現一次（一次方）。'},
  recog:{type:'choice', prompt:'車輪滾動一圈前進的距離，等於下列哪一個？',
    options:[{t:'車輪的圓周長'}, {t:'車輪的圓面積'}, {t:'車輪的半徑'}, {t:'車輪的直徑'}],
    answer:0, hint1:'滾一圈＝把圓周攤平成一條線。',
    why:'輪子滾一圈，接觸地面的長度就是圓周攤開的長度，也就是圓周長 2πr。'},
  apply:{type:'choice', prompt:'半徑 7 公分的圓，周長是多少？',
    given:'r=7', options:[{math:'14\\pi'}, {math:'49\\pi'}, {math:'7\\pi'}, {math:'28\\pi'}],
    answer:0, unit:'公分', hint1:'把 r = 7 代進 2πr。',
    steps:['圓周長 = 2πr', '= 2 × π × 7', '= 14π（公分）']},
  recogMore:[{type:'choice', prompt:'「用鐵絲圍成一個圓，需要多長的鐵絲」求的是？',
    options:[{t:'圓周長'}, {t:'圓面積'}, {t:'半徑'}, {t:'直徑'}],
    answer:0, hint1:'鐵絲是繞一圈的長度。',
    why:'圍一圈需要的長度就是圓周長 2πr，鐵絲是線不是面。'}],
  applyMore:[
    {type:'choice', prompt:'直徑 20 公分的圓，周長是多少？',
     given:'d=20', options:[{math:'20\\pi'}, {math:'40\\pi'},
       {math:'10\\pi'}, {math:'100\\pi'}],
     answer:0, unit:'公分', hint1:'直徑 20 ⇒ 半徑 10，代入 2πr。',
     steps:['半徑 = 20 ÷ 2 = 10', '周長 = 2π × 10 = 20π（公分）']},
    {type:'numeric', prompt:'某圓的周長是 18π，半徑是多少？',
     given:'2\\pi r=18\\pi', answer:'9', unit:'', hint1:'2πr = 18π，兩邊同除以 2π。',
     steps:['2πr = 18π', 'r = 18π ÷ 2π = 9']}],
  worked:{title:'半徑 7 公分的圓周長', given:'r=7',
    steps:[{label:'寫公式', math:'\\text{圓周長}=2\\pi r'},
           {label:'代入', math:'=2\\times\\pi\\times 7'},
           {label:'計算', math:'=14\\pi'}],
    answer:'14\\pi \\text{ 公分}'},
  explain:'r 是半徑（圓心到圓上的距離）。若題目給的是直徑 d，因為 d = 2r，周長也可以寫成 πd。',
  source:'題本附錄公式表'}),

card({id:'A6', grade:7, category:'geo', attachedInExam:true, title:'圓面積',
  formula:'\\text{圓面積}=\\pi r^2',
  variables:[{sym:'r', desc:'圓的半徑'}, {sym:'π', desc:'圓周率'}],
  usageConditions:'求圓形區域大小、圓形草皮、圓桌桌面等「面」的量時使用。',
  triggerWords:['面積', '塗滿', '鋪滿', '多少平方公分'],
  commonMistakes:['把 πr² 寫成 (πr)²', '用直徑代入 r', '面積與周長互換'],
  diagramType:'SectorDiagram', diagramData:{full:true, mode:'area'},
  recall:{type:'blank', prompt:'補完圓面積公式。',
    template:'\\text{圓面積}=@1', blanks:['\\pi r^2'],
    bank:['\\pi r^2', '2\\pi r', '\\pi r', '2\\pi r^2'],
    hint1:'面積是兩個長度相乘，所以 r 是平方。'},
  recog:{type:'choice', prompt:'題目問「圓形花圃要鋪多少草皮」，該用哪個公式？',
    options:[{math:'\\pi r^2'}, {math:'2\\pi r'}, {math:'\\pi r'}, {math:'2r'}],
    answer:0, hint1:'鋪滿一個面 ⇒ 面積。',
    why:'鋪草皮是把整個圓面鋪滿，屬於面積，用 πr²；2πr 是圍一圈的長度。'},
  apply:{type:'choice', prompt:'直徑 10 公分的圓，面積是多少？',
    given:'d=10', options:[{math:'25\\pi'}, {math:'100\\pi'}, {math:'10\\pi'}, {math:'20\\pi'}],
    answer:0, unit:'平方公分', hint1:'直徑 10 ⇒ 半徑 5，再代入 πr²。',
    steps:['直徑 10，半徑 r = 10 ÷ 2 = 5', '面積 = π × 5² = 25π（平方公分）']},
  recogMore:[{type:'choice', prompt:'圓的半徑變成原來的 2 倍，面積會變成原來的幾倍？',
    options:[{t:'4 倍'}, {t:'2 倍'}, {t:'8 倍'}, {t:'不變'}],
    answer:0, hint1:'面積公式裡的 r 是平方。',
    why:'面積與 r² 成正比，半徑 2 倍 ⇒ 面積 2² = 4 倍。'}],
  applyMore:[
    {type:'choice', prompt:'半徑 3 公分的圓，面積是多少？',
     given:'r=3', options:[{math:'9\\pi'}, {math:'6\\pi'},
       {math:'3\\pi'}, {math:'12\\pi'}],
     answer:0, unit:'平方公分', hint1:'π × 3²。',
     steps:['面積 = π × 3² = 9π（平方公分）']},
    {type:'numeric', prompt:'某圓的面積是 49π，半徑是多少？',
     given:'\\pi r^2=49\\pi', answer:'7', unit:'', hint1:'r² = 49，再開根號。',
     steps:['πr² = 49π ⇒ r² = 49', 'r = 7']}],
  worked:{title:'直徑 10 公分的圓面積', given:'d=10',
    steps:[{label:'先換成半徑', math:'r=\\frac{10}{2}=5'},
           {label:'寫公式', math:'\\text{圓面積}=\\pi r^2'},
           {label:'代入', math:'=\\pi\\times 5^2=25\\pi'}],
    answer:'25\\pi \\text{ 平方公分}'},
  explain:'πr² 是「π 乘上 r 的平方」，不是 (πr) 再平方。題目給直徑時務必先除以 2。',
  source:'題本附錄公式表'}),

card({id:'A7', grade:7, category:'geo', attachedInExam:true, title:'凸 n 邊形內角和',
  formula:'\\text{內角和}=(n-2)\\times 180^\\circ',
  variables:[{sym:'n', desc:'多邊形的邊數（也是頂點數）'}],
  usageConditions:'題目給多邊形邊數求角度總和，或已知部分角求剩下的角時使用。',
  triggerWords:['幾邊形', '內角和', '每個內角', '正多邊形'],
  commonMistakes:['忘記減 2', '把內角和當成每一個內角', '把 (n−2) 乘錯成 (n−1)'],
  diagramType:'QuadrilateralDiagram', diagramData:{variant:'polygon-angles'},
  recall:{type:'blank', prompt:'補完凸 n 邊形的內角和公式。',
    template:'\\text{內角和}=@1\\times 180^\\circ', blanks:['(n-2)'],
    bank:['(n-2)', '(n-1)', 'n', '(n+2)'],
    hint1:'從一個頂點拉對角線，n 邊形會被切成 (n − 2) 個三角形。'},
  recog:{type:'choice', prompt:'題目問「正八邊形每一個內角是幾度」，正確做法是？',
    options:[{t:'先算內角和，再除以 8'}, {t:'直接用 (8−2)×180°'},
             {t:'用 360° ÷ 8'}, {t:'用 180° − 8'}],
    answer:0, hint1:'「每一個」代表要平分。',
    why:'(8−2)×180° = 1080° 是八個角的總和，要再除以 8 才是每一個內角 135°。'},
  apply:{type:'numeric', prompt:'六邊形的內角和是幾度？（只填數字）',
    given:'n=6', answer:'720', unit:'度', hint1:'n = 6，代入 (n − 2) × 180°。',
    steps:['(6 − 2) × 180°', '= 4 × 180° = 720°']},
  recogMore:[{type:'choice', prompt:'凸多邊形的內角和一定是 180° 的倍數，這個說法？',
    options:[{t:'正確，因為可以切成整數個三角形'}, {t:'錯誤，只有正多邊形才成立'},
             {t:'錯誤，四邊形就不是'}, {t:'要看邊數是奇數還是偶數'}],
    answer:0, hint1:'(n − 2) 是整數。',
    why:'內角和 = (n − 2) × 180°，(n − 2) 一定是整數，所以內角和必為 180° 的整數倍。'}],
  applyMore:[
    {type:'numeric', prompt:'某凸多邊形的內角和是 1080°，它是幾邊形？',
     given:'(n-2)\\times 180^\\circ=1080^\\circ', answer:'8', unit:'邊形',
     hint1:'先把 1080 除以 180。',
     steps:['(n − 2) × 180° = 1080°', 'n − 2 = 6', 'n = 8']},
    {type:'numeric', prompt:'十邊形的內角和是幾度？（只填數字）',
     given:'n=10', answer:'1440', unit:'度', hint1:'(10 − 2) × 180°。',
     steps:['(10 − 2) × 180°', '= 8 × 180° = 1440°']}],
  worked:{title:'六邊形的內角和', given:'n=6',
    steps:[{label:'寫公式', math:'(n-2)\\times 180^\\circ'},
           {label:'代入 n = 6', math:'=(6-2)\\times 180^\\circ'},
           {label:'計算', math:'=4\\times 180^\\circ=720^\\circ'}],
    answer:'720^\\circ'},
  explain:'從一個頂點向其他不相鄰頂點拉對角線，n 邊形會被切成 (n − 2) 個三角形，每個三角形內角和 180°。',
  source:'題本附錄公式表'}),

card({id:'A8', grade:8, category:'num', attachedInExam:true, title:'等差數列通項',
  formula:'a_n=a_1+(n-1)d',
  variables:[{sym:'aₙ', desc:'第 n 項'}, {sym:'a₁', desc:'首項'},
             {sym:'n', desc:'第幾項'}, {sym:'d', desc:'公差（後項減前項）'}],
  usageConditions:'數列每次都加固定數，要求某一項時使用。',
  triggerWords:['每次多', '每排增加', '第幾項', '公差', '規律'],
  commonMistakes:['用 nd 而不是 (n−1)d', '公差算成前項減後項', '首項從第 0 項開始數'],
  recall:{type:'blank', prompt:'補完等差數列的通項公式。',
    template:'a_n=a_1+@1', blanks:['(n-1)d'],
    bank:['(n-1)d', 'nd', '(n+1)d', 'n d^2'],
    hint1:'從第 1 項走到第 n 項，只走了 (n − 1) 步。'},
  recog:{type:'choice', prompt:'哪一個數列可以用等差通項公式？',
    options:[{math:'3,\\ 7,\\ 11,\\ 15,\\ \\ldots'}, {math:'2,\\ 4,\\ 8,\\ 16,\\ \\ldots'},
             {math:'1,\\ 4,\\ 9,\\ 16,\\ \\ldots'}, {math:'1,\\ 1,\\ 2,\\ 3,\\ 5,\\ \\ldots'}],
    answer:0, hint1:'相鄰兩項相減，差是不是都一樣？',
    why:'3、7、11、15 每次都加 4，差固定所以是等差；2、4、8、16 是每次乘 2（等比）。'},
  apply:{type:'numeric', prompt:'等差數列首項 5、公差 3，第 10 項是多少？',
    given:'a_1=5,\\ d=3,\\ n=10', answer:'32', unit:'',
    hint1:'代入 a₁ + (n − 1)d，注意是 9 個 d。',
    steps:['a₁₀ = 5 + (10 − 1) × 3', '= 5 + 27 = 32']},
  recogMore:[{type:'choice', prompt:'「禮堂第一排 12 個座位，每往後一排多 2 個」屬於哪一種數列？',
    options:[{t:'等差數列，公差 2'}, {t:'等比數列，公比 2'},
             {t:'等差數列，公差 12'}, {t:'不是數列'}],
    answer:0, hint1:'每次是「多 2 個」還是「變 2 倍」？',
    why:'每排固定多 2 個，差固定，所以是公差 2 的等差數列，首項 12。'}],
  applyMore:[
    {type:'numeric', prompt:'等差數列首項 100、公差 −7，第 8 項是多少？',
     given:'a_1=100,\\ d=-7,\\ n=8', answer:'51', unit:'',
     hint1:'公差是負的，代入時要小心正負號。',
     steps:['a₈ = 100 + (8 − 1) × (−7)', '= 100 − 49 = 51']},
    {type:'numeric', prompt:'等差數列第 1 項是 4、第 5 項是 20，公差是多少？',
     given:'a_1=4,\\ a_5=20', answer:'4', unit:'',
     hint1:'從第 1 項到第 5 項加了 4 次公差。',
     steps:['a₅ = a₁ + 4d ⇒ 20 = 4 + 4d', '4d = 16', 'd = 4']}],
  worked:{title:'首項 5、公差 3 的第 10 項', given:'a_1=5,\\ d=3',
    steps:[{label:'寫公式', math:'a_n=a_1+(n-1)d'},
           {label:'代入', math:'a_{10}=5+(10-1)\\times 3'},
           {label:'計算', math:'=5+27=32'}],
    answer:'32'},
  explain:'(n − 1) 代表從首項出發「加了幾次公差」。第 1 項加 0 次，第 10 項加 9 次，所以是 (n − 1) 而不是 n。',
  source:'題本附錄公式表'}),

card({id:'A9', grade:8, category:'num', attachedInExam:true, title:'等差數列前 n 項和',
  formula:'S_n=\\frac{n(a_1+a_n)}{2}',
  variables:[{sym:'Sₙ', desc:'前 n 項的總和'}, {sym:'n', desc:'項數'},
             {sym:'a₁', desc:'首項'}, {sym:'aₙ', desc:'第 n 項（末項）'}],
  usageConditions:'把等差數列從第 1 項一路加到第 n 項時使用，須先知道末項。',
  triggerWords:['總共', '總和', '全部加起來', '疊起來共'],
  commonMistakes:['忘記除以 2', '不知道末項就硬代', '把項數 n 和末項 aₙ 搞混'],
  recall:{type:'blank', prompt:'補完等差數列求和公式。',
    template:'S_n=@1', blanks:['\\frac{n(a_1+a_n)}{2}'],
    bank:['\\frac{n(a_1+a_n)}{2}', '\\frac{a_1+a_n}{2}', 'n(a_1+a_n)', '\\frac{n(a_1-a_n)}{2}'],
    hint1:'（首項 ＋ 末項）× 項數 ÷ 2，就像梯形面積。'},
  recog:{type:'choice', prompt:'「1 + 2 + 3 + … + 100」最快的算法是？',
    options:[{t:'用等差求和公式，n = 100'}, {t:'用等差通項公式'},
             {t:'用等比通項公式'}, {t:'一項一項相加'}],
    answer:0, hint1:'題目要的是「總和」不是某一項。',
    why:'要總和就用 Sₙ；n = 100、a₁ = 1、a₁₀₀ = 100，得 100 × 101 ÷ 2 = 5050。'},
  apply:{type:'numeric', prompt:'1 + 2 + 3 + … + 100 = ？',
    given:'a_1=1,\\ a_{100}=100,\\ n=100', answer:'5050', unit:'',
    hint1:'（1 + 100）× 100 ÷ 2。',
    steps:['S₁₀₀ = 100 × (1 + 100) ÷ 2', '= 100 × 101 ÷ 2 = 5050']},
  recogMore:[{type:'choice', prompt:'題目問「把積木一層一層疊起來，總共用了幾塊」，該用哪個公式？',
    options:[{t:'等差數列求和 Sₙ'}, {t:'等差數列通項 aₙ'},
             {t:'等比數列通項'}, {t:'平均數'}],
    answer:0, hint1:'「總共」是要把每一層加起來。',
    why:'每層數量成等差、要求全部加總，用 Sₙ = n(a₁ + aₙ) ÷ 2。'}],
  applyMore:[
    {type:'numeric', prompt:'2 + 4 + 6 + … + 40 的總和是多少？',
     given:'a_1=2,\\ a_n=40,\\ n=20', answer:'420', unit:'',
     hint1:'共有 40 ÷ 2 = 20 項，首項 2、末項 40。',
     steps:['項數 n = 40 ÷ 2 = 20', 'S = 20 × (2 + 40) ÷ 2', '= 20 × 42 ÷ 2 = 420']},
    {type:'numeric', prompt:'等差數列首項 3、末項 39，共 13 項，總和是多少？',
     given:'a_1=3,\\ a_n=39,\\ n=13', answer:'273', unit:'',
     hint1:'(3 + 39) × 13 ÷ 2。',
     steps:['S = 13 × (3 + 39) ÷ 2', '= 13 × 42 ÷ 2', '= 13 × 21 = 273']}],
  worked:{title:'求 1 + 2 + … + 100', given:'a_1=1,\\ a_n=100,\\ n=100',
    steps:[{label:'寫公式', math:'S_n=\\frac{n(a_1+a_n)}{2}'},
           {label:'代入', math:'S_{100}=\\frac{100(1+100)}{2}'},
           {label:'計算', math:'=\\frac{100\\times 101}{2}=5050'}],
    answer:'5050'},
  explain:'把數列頭尾配對，每一對的和都是 a₁ + aₙ，一共有 n ÷ 2 對，所以總和是 n(a₁ + aₙ) ÷ 2。',
  source:'題本附錄公式表'}),

card({id:'A10', grade:8, category:'num', attachedInExam:true, title:'等比數列通項',
  formula:'a_n=a_1r^{n-1}',
  variables:[{sym:'aₙ', desc:'第 n 項'}, {sym:'a₁', desc:'首項'},
             {sym:'r', desc:'公比（後項除以前項）'}, {sym:'n', desc:'第幾項'}],
  usageConditions:'數列每次都乘固定倍數（加倍、對折、細菌分裂）時使用。',
  triggerWords:['每次乘', '加倍', '對折', '倍增', '公比'],
  commonMistakes:['指數寫成 n 而不是 n−1', '把公比算成相減', '負公比忘記正負交替'],
  recall:{type:'blank', prompt:'補完等比數列的通項公式。',
    template:'a_n=a_1@1', blanks:['r^{n-1}'],
    bank:['r^{n-1}', 'r^n', '(n-1)r', 'r^{n+1}'],
    hint1:'從第 1 項到第 n 項只乘了 (n − 1) 次公比。'},
  recog:{type:'choice', prompt:'一張紙每對折一次厚度加倍，這是哪一種數列？',
    options:[{t:'等比數列，公比 2'}, {t:'等差數列，公差 2'},
             {t:'等差數列，公差 1'}, {t:'既不是等差也不是等比'}],
    answer:0, hint1:'看是「每次加固定數」還是「每次乘固定數」。',
    why:'加倍是乘以 2，屬於等比數列，公比 r = 2。'},
  apply:{type:'numeric', prompt:'等比數列首項 3、公比 2，第 5 項是多少？',
    given:'a_1=3,\\ r=2,\\ n=5', answer:'48', unit:'',
    hint1:'第 5 項只乘了 4 次公比。',
    steps:['a₅ = 3 × 2⁵⁻¹ = 3 × 2⁴', '= 3 × 16 = 48']},
  recogMore:[{type:'choice', prompt:'「細菌每小時分裂成原來的兩倍」屬於哪一種數列？',
    options:[{t:'等比數列，公比 2'}, {t:'等差數列，公差 2'},
             {t:'等差數列，公差 1'}, {t:'不是數列'}],
    answer:0, hint1:'「變成兩倍」是乘還是加？',
    why:'每小時乘以 2，比值固定，所以是公比 2 的等比數列。'}],
  applyMore:[
    {type:'numeric', prompt:'等比數列首項 2、公比 3，第 4 項是多少？',
     given:'a_1=2,\\ r=3,\\ n=4', answer:'54', unit:'',
     hint1:'第 4 項只乘了 3 次公比。',
     steps:['a₄ = 2 × 3⁴⁻¹ = 2 × 3³', '= 2 × 27 = 54']},
    {type:'numeric', prompt:'一張紙對折 6 次後會有幾層？（首項 1、公比 2 的第 7 項）',
     given:'a_1=1,\\ r=2,\\ n=7', answer:'64', unit:'層',
     hint1:'沒對折時是 1 層，對折 6 次是第 7 項。',
     steps:['a₇ = 1 × 2⁷⁻¹ = 2⁶', '= 64（層）']}],
  worked:{title:'首項 3、公比 2 的第 5 項', given:'a_1=3,\\ r=2',
    steps:[{label:'寫公式', math:'a_n=a_1r^{n-1}'},
           {label:'代入', math:'a_5=3\\times 2^{5-1}'},
           {label:'計算', math:'=3\\times 16=48'}],
    answer:'48'},
  explain:'r 是「後項 ÷ 前項」。指數是 n − 1，因為第 1 項還沒乘過公比。',
  source:'題本附錄公式表'}),

card({id:'A11', grade:8, category:'eq', attachedInExam:true, title:'一元二次方程式公式解',
  formula:'x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}',
  variables:[{sym:'a', desc:'二次項係數（不可為 0）'}, {sym:'b', desc:'一次項係數'},
             {sym:'c', desc:'常數項'}, {sym:'b²−4ac', desc:'判別式，決定有沒有實數解'}],
  usageConditions:'方程式整理成 ax²+bx+c = 0 後，若無法因式分解就用公式解。',
  triggerWords:['一元二次', '求 x', '解方程式', '無法因式分解'],
  commonMistakes:['沒有先移項成等於 0 就代入', '忘記 −b 的負號', '把 2a 只除到其中一項', 'b 是負數時代入忘記加括號'],
  recall:{type:'blank', prompt:'補完一元二次方程式的公式解。',
    template:'x=@1', blanks:['\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}'],
    bank:['\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}', '\\frac{b\\pm\\sqrt{b^2-4ac}}{2a}',
          '\\frac{-b\\pm\\sqrt{b^2+4ac}}{2a}', '\\frac{-b\\pm\\sqrt{b^2-4ac}}{a}'],
    hint1:'分子開頭是 −b，根號內是 b² − 4ac，整個分子都要除以 2a。'},
  recog:{type:'choice', prompt:'解 x² + 5x + 3 = 0 時，最合適的方法是？',
    options:[{t:'公式解'}, {t:'十字交乘因式分解'}, {t:'直接開平方'}, {t:'代入消去法'}],
    answer:0, hint1:'先試著找兩個整數相乘得 3、相加得 5。',
    why:'找不到兩個整數相乘 3、相加 5，因式分解走不通，所以用公式解。'},
  apply:{type:'choice', prompt:'x² − 5x + 6 = 0，判別式 b² − 4ac 的值是多少？',
    given:'a=1,\\ b=-5,\\ c=6',
    options:[{math:'1'}, {math:'49'}, {math:'-1'}, {math:'25'}],
    answer:0, unit:'', hint1:'b = −5，注意 (−5)² 是正的。',
    steps:['a = 1、b = −5、c = 6', 'b² − 4ac = (−5)² − 4 × 1 × 6', '= 25 − 24 = 1']},
  recogMore:[{type:'choice', prompt:'若判別式 b² − 4ac < 0，代表這個一元二次方程式？',
    options:[{t:'沒有實數解'}, {t:'有兩個相異實數解'},
             {t:'有一個重根'}, {t:'無法判斷'}],
    answer:0, hint1:'判別式在根號裡面。',
    why:'根號內為負數時沒有實數值，所以方程式沒有實數解。大於 0 有兩相異解、等於 0 有重根。'}],
  applyMore:[
    {type:'numeric', prompt:'2x² − 7x + 3 = 0 的判別式 b² − 4ac 是多少？',
     given:'a=2,\\ b=-7,\\ c=3', answer:'25', unit:'',
     hint1:'(−7)² − 4 × 2 × 3。',
     steps:['a = 2、b = −7、c = 3', 'b² − 4ac = 49 − 24 = 25']},
    {type:'choice', prompt:'x² + 2x − 8 = 0 的兩根是？',
     given:'a=1,\\ b=2,\\ c=-8',
     options:[{math:'x=2 \\text{ 或 } x=-4'}, {math:'x=-2 \\text{ 或 } x=4'},
       {math:'x=1 \\text{ 或 } x=-8'}, {math:'x=8 \\text{ 或 } x=-1'}],
     answer:0, unit:'', hint1:'找兩數相乘 −8、相加 +2。',
     steps:['(x + 4)(x − 2) = 0', 'x = −4 或 x = 2', '（用公式解也會得到同樣答案）']}],
  worked:{title:'用公式解 x² − 5x + 6 = 0', given:'a=1,\\ b=-5,\\ c=6',
    steps:[{label:'確認係數', text:'a = 1，b = −5，c = 6（先確定右邊是 0）'},
           {label:'代入', math:'x=\\frac{-(-5)\\pm\\sqrt{(-5)^2-4(1)(6)}}{2(1)}'},
           {label:'算判別式', math:'=\\frac{5\\pm\\sqrt{25-24}}{2}'},
           {label:'開根號', math:'=\\frac{5\\pm 1}{2}'},
           {label:'分開寫', math:'x=3 \\text{ 或 } x=2'}],
    answer:'x=3 \\text{ 或 } x=2'},
  explain:'a、b、c 必須先把方程式整理成 ax² + bx + c = 0 才能對號入座。判別式 b² − 4ac 大於 0 有兩相異實數解，等於 0 有重根，小於 0 沒有實數解。',
  source:'題本附錄公式表'})

];
