/* ══════════════════════════════════════════════════════════════════════
   知識點資料：數與代數、根式（題本未附，必須自己記）
   ══════════════════════════════════════════════════════════════════════ */
var NUM_CARDS = [

card({id:'B1', grade:7, category:'num', title:'負號分配（括號內相加）',
  formula:'-(a+b)=-a-b',
  variables:[{sym:'a', desc:'括號內第一項'}, {sym:'b', desc:'括號內第二項'}],
  usageConditions:'括號前面是負號（或減去一整個括號）時，去括號要把每一項都變號。',
  triggerWords:['去括號', '減去', '相反數', '化簡'],
  commonMistakes:['只變第一項的號', '把 −(a+b) 寫成 −a+b'],
  recall:{type:'blank', anyOrder:true, prompt:'去括號後應該是？',
    template:'-(a+b)=@1@2', blanks:['-a', '-b'],
    bank:['-a', '-b', '+a', '+b'], hint1:'括號內每一項都要變號，不能只變第一項。'},
  recog:{type:'choice', prompt:'化簡 5 − (x + 2) 的第一步應該是？',
    options:[{math:'5-x-2'}, {math:'5-x+2'}, {math:'5+x+2'}, {math:'5+x-2'}],
    answer:0, hint1:'減去一整個括號＝括號內每一項都變號。',
    why:'負號要分配給括號內兩項，x 變 −x，＋2 變 −2，得 5 − x − 2 = 3 − x。'},
  apply:{type:'numeric', prompt:'化簡 10 − (3 + 4) 的值是多少？',
    given:'10-(3+4)', answer:'3', unit:'', hint1:'先把負號分配進去：10 − 3 − 4。',
    steps:['10 − (3 + 4) = 10 − 3 − 4', '= 3']},
  recogMore:[{type:'choice', prompt:'「減去一整個括號」等於做什麼？',
    options:[{t:'把括號內每一項都變號'}, {t:'只把第一項變號'},
             {t:'把括號直接拿掉'}, {t:'把括號內每一項都乘 2'}],
    answer:0, hint1:'括號前的負號相當於乘以 −1。',
    why:'負號要分配給括號內的每一項，只變第一項是最常見的錯誤。'}],
  applyMore:[
    {type:'choice', prompt:'化簡 8 − (x + 5)，結果是？',
     given:'8-(x+5)', options:[{math:'3-x'}, {math:'3+x'}, {math:'13-x'}, {math:'13+x'}],
     answer:0, unit:'', hint1:'先分配負號：8 − x − 5。',
     steps:['8 − (x + 5) = 8 − x − 5', '= 3 − x']},
    {type:'numeric', prompt:'把 −(2a + 3b) 去括號後，b 的係數是多少？',
     given:'-(2a+3b)', answer:'-3', unit:'', hint1:'兩項都要變號。',
     steps:['−(2a + 3b) = −2a − 3b', 'b 的係數是 −3']}],
  worked:{title:'化簡 5 − (x + 2)', given:'5-(x+2)',
    steps:[{label:'分配負號', math:'5-x-2'}, {label:'合併常數', math:'=3-x'}],
    answer:'3-x'},
  explain:'括號前的負號等於乘以 −1，所以括號內每一項都要變號。',
  source:'自己要記'}),

card({id:'B2', grade:7, category:'num', title:'負號分配（括號內相減）',
  formula:'-(a-b)=-a+b',
  variables:[{sym:'a', desc:'被減數'}, {sym:'b', desc:'減數'}],
  usageConditions:'括號前是負號、括號內是減法時，減號會被變成加號。',
  triggerWords:['去括號', '相減', '化簡', '兩式相減'],
  commonMistakes:['第二項忘記變成 +b', '整串照抄沒變號'],
  recall:{type:'blank', prompt:'去括號後應該是？',
    template:'-(a-b)=@1@2', blanks:['-a', '+b'],
    bank:['-a', '+b', '-b', '+a'], hint1:'負負得正，原本的 −b 會變成 +b。'},
  recog:{type:'choice', prompt:'(2x + 5) − (x − 3) 去括號後是？',
    options:[{math:'2x+5-x+3'}, {math:'2x+5-x-3'}, {math:'2x+5+x-3'}, {math:'2x-5-x+3'}],
    answer:0, hint1:'第二個括號前面是減號，裡面兩項都要變號。',
    why:'−(x − 3) = −x + 3，所以整式是 2x + 5 − x + 3 = x + 8。'},
  apply:{type:'numeric', prompt:'計算 20 − (8 − 5) 的值。',
    given:'20-(8-5)', answer:'17', unit:'', hint1:'20 − 8 + 5。',
    steps:['20 − (8 − 5) = 20 − 8 + 5', '= 17']},
  recogMore:[{type:'choice', prompt:'下列哪一個去括號是正確的？',
    options:[{math:'-(x-4)=-x+4'}, {math:'-(x-4)=-x-4'},
             {math:'-(x-4)=x+4'}, {math:'-(x-4)=x-4'}],
    answer:0, hint1:'負負得正。',
    why:'−(x − 4) 中，x 變 −x、−4 變 +4，所以是 −x + 4。'}],
  applyMore:[
    {type:'choice', prompt:'化簡 (5x − 2) − (3x − 7)，結果是？',
     given:'(5x-2)-(3x-7)', options:[{math:'2x+5'}, {math:'2x-9'},
       {math:'8x-9'}, {math:'2x-5'}],
     answer:0, unit:'', hint1:'第二個括號前是減號，裡面兩項都要變號。',
     steps:['= 5x − 2 − 3x + 7', '= (5x − 3x) + (−2 + 7)', '= 2x + 5']},
    {type:'numeric', prompt:'把 −(a − 9) 去括號後，常數項是多少？',
     given:'-(a-9)', answer:'9', unit:'', hint1:'−9 變號之後是多少？',
     steps:['−(a − 9) = −a + 9', '常數項是 9']}],
  worked:{title:'化簡 (2x+5) − (x−3)', given:'(2x+5)-(x-3)',
    steps:[{label:'分配負號', math:'2x+5-x+3'}, {label:'合併同類項', math:'=x+8'}],
    answer:'x+8'},
  explain:'負號分配時，括號內的加變減、減變加。最容易錯的就是第二項。',
  source:'自己要記'}),

card({id:'B3', grade:7, category:'num', title:'數線上兩點的距離',
  formula:'\\text{距離}=|a-b|',
  variables:[{sym:'a', desc:'第一點的坐標'}, {sym:'b', desc:'第二點的坐標'}],
  usageConditions:'數線上兩點求距離時使用，距離一定是非負數。',
  triggerWords:['數線', '相距', '距離', '中點'],
  commonMistakes:['算出負數就當答案', '兩點都是負數時忘記加括號'],
  recall:{type:'blank', prompt:'數線上 a、b 兩點的距離是？',
    template:'\\text{距離}=@1', blanks:['|a-b|'],
    bank:['|a-b|', 'a-b', 'a+b', '|a+b|'], hint1:'距離不能是負的，所以要加絕對值。'},
  recog:{type:'choice', prompt:'數線上 −3 與 5 相距多少？',
    options:[{math:'8'}, {math:'2'}, {math:'-8'}, {math:'15'}],
    answer:0, hint1:'|−3 − 5| 要先算括號內再取絕對值。',
    why:'|−3 − 5| = |−8| = 8，從 −3 走到 5 要經過 8 個單位。'},
  apply:{type:'numeric', prompt:'數線上 −7 與 4 的距離是多少？',
    given:'a=-7,\\ b=4', answer:'11', unit:'', hint1:'|−7 − 4| = |−11|。',
    steps:['|−7 − 4| = |−11|', '= 11']},
  recogMore:[{type:'choice', prompt:'數線上兩點的距離有可能是負數嗎？',
    options:[{t:'不可能，距離一定大於等於 0'}, {t:'可能，看相減的順序'},
             {t:'可能，兩點都是負數時'}, {t:'只有原點左邊才可能'}],
    answer:0, hint1:'想想「距離」的意義。',
    why:'距離是長度，不可能是負的，所以公式外面要加絕對值。'}],
  applyMore:[
    {type:'numeric', prompt:'數線上 6 與 −2 相距多少？',
     given:'a=6,\\ b=-2', answer:'8', unit:'', hint1:'|6 − (−2)| = |8|。',
     steps:['|6 − (−2)| = |6 + 2|', '= |8| = 8']},
    {type:'numeric', prompt:'數線上 −5 與 −12 相距多少？',
     given:'a=-5,\\ b=-12', answer:'7', unit:'', hint1:'|−5 − (−12)| = |7|。',
     steps:['|−5 − (−12)| = |−5 + 12|', '= |7| = 7']}],
  worked:{title:'求 −7 與 4 的距離', given:'a=-7,\\ b=4',
    steps:[{label:'代入', math:'|-7-4|'}, {label:'先算括號內', math:'=|-11|'},
           {label:'取絕對值', math:'=11'}],
    answer:'11'},
  explain:'a − b 可能是負的，但距離不能是負的，所以外面要加絕對值。|a − b| 與 |b − a| 相等。',
  source:'自己要記'}),

card({id:'B4', grade:7, category:'num', title:'零次方',
  formula:'a^0=1,\\ a\\neq 0',
  variables:[{sym:'a', desc:'底數，不可以是 0'}],
  usageConditions:'任何非零數的 0 次方都等於 1，常出現在指數律化簡的最後一步。',
  triggerWords:['0 次方', '化簡', '指數律'],
  commonMistakes:['寫成 0', '忘記 a ≠ 0 的限制', '把 0⁰ 當成 1'],
  recall:{type:'blank', prompt:'補完零次方的規則。',
    template:'a^0=@1', blanks:['1'], bank:['1', '0', 'a', '-1'],
    hint1:'只要底數不是 0，結果固定是同一個數。'},
  recog:{type:'choice', prompt:'下列哪一個式子「不成立」？',
    options:[{math:'0^0=1'}, {math:'5^0=1'}, {math:'(-3)^0=1'}, {math:'(\\frac{2}{7})^0=1'}],
    answer:0, hint1:'公式有一個但書。',
    why:'零次方規則要求底數不為 0，所以 0⁰ 沒有定義；其餘底數都不是 0，結果都是 1。'},
  apply:{type:'numeric', prompt:'計算 (−8)⁰ + 3⁰ 的值。',
    given:'(-8)^0+3^0', answer:'2', unit:'', hint1:'兩個底數都不是 0。',
    steps:['(−8)⁰ = 1，3⁰ = 1', '1 + 1 = 2']},
  recogMore:[{type:'choice', prompt:'為什麼 a⁰ = 1（a ≠ 0）？',
    options:[{t:'因為 aᵐ ÷ aᵐ = a⁰，而任何非零數除以自己等於 1'},
             {t:'因為 0 次方代表沒有相乘'},
             {t:'因為規定就是這樣'}, {t:'因為 a × 0 = 0'}],
    answer:0, hint1:'從同底數相除的指數律推回去。',
    why:'aᵐ ÷ aᵐ 一方面等於 a⁰，另一方面等於 1，所以 a⁰ = 1；a = 0 時除法不成立，故有但書。'}],
  applyMore:[
    {type:'numeric', prompt:'計算 5⁰ × 7 的值。',
     given:'5^0\\times 7', answer:'7', unit:'', hint1:'5⁰ = 1。',
     steps:['5⁰ = 1', '1 × 7 = 7']},
    {type:'numeric', prompt:'計算 (2⁰ + 3⁰) × 4 的值。',
     given:'(2^0+3^0)\\times 4', answer:'8', unit:'', hint1:'括號內兩個都是 1。',
     steps:['2⁰ = 1，3⁰ = 1', '(1 + 1) × 4 = 2 × 4 = 8']}],
  worked:{title:'計算 (−8)⁰ + 3⁰', given:'(-8)^0+3^0',
    steps:[{label:'各自化簡', math:'(-8)^0=1,\\ 3^0=1'}, {label:'相加', math:'1+1=2'}],
    answer:'2'},
  explain:'因為 aᵐ ÷ aᵐ = aᵐ⁻ᵐ = a⁰，而任何非零數除以自己等於 1，所以 a⁰ = 1。',
  source:'自己要記'}),

card({id:'B5', grade:7, category:'num', title:'同底數相乘',
  formula:'a^ma^n=a^{m+n}',
  variables:[{sym:'a', desc:'相同的底數'}, {sym:'m', desc:'第一個指數'}, {sym:'n', desc:'第二個指數'}],
  usageConditions:'底數相同的兩個乘冪相乘時，指數相加。',
  triggerWords:['同底', '相乘', '指數律', '化簡'],
  commonMistakes:['把指數相乘', '底數也一起乘', '底數不同也硬加'],
  recall:{type:'blank', prompt:'補完同底數相乘的指數律。',
    template:'a^ma^n=a^{@1}', blanks:['m+n'],
    bank:['m+n', 'mn', 'm-n', 'm^n'], hint1:'相乘 ⇒ 指數相加。'},
  recog:{type:'choice', prompt:'下列哪一個可以直接用「同底數相乘」化簡？',
    options:[{math:'2^3\\times 2^5'}, {math:'2^3\\times 3^5'}, {math:'2^3+2^5'}, {math:'2^3\\div 3^5'}],
    answer:0, hint1:'底數必須完全相同，而且是相乘。',
    why:'只有 2³ × 2⁵ 底數相同又是相乘，等於 2⁸；底數不同或是相加都不能用。'},
  apply:{type:'numeric', prompt:'2³ × 2⁵ 化簡成 2 的幾次方？（只填指數）',
    given:'2^3\\times 2^5', answer:'8', unit:'', hint1:'3 + 5。',
    steps:['2³ × 2⁵ = 2³⁺⁵', '= 2⁸，指數是 8']},
  recogMore:[{type:'choice', prompt:'2³ × 3³ 可以用「同底數相乘」化簡嗎？',
    options:[{t:'不行，底數不同'}, {t:'可以，等於 6⁶'},
             {t:'可以，等於 2⁶'}, {t:'可以，等於 5³'}],
    answer:0, hint1:'指數律的前提是底數相同。',
    why:'底數不同不能用這條律。2³ × 3³ 要改用「積的乘冪」反過來寫成 (2×3)³ = 6³。'}],
  applyMore:[
    {type:'numeric', prompt:'3² × 3³ × 3 化簡成 3 的幾次方？（只填指數）',
     given:'3^2\\times 3^3\\times 3', answer:'6', unit:'',
     hint1:'單獨的 3 是 3¹，指數全部相加。',
     steps:['3² × 3³ × 3¹', '指數相加：2 + 3 + 1 = 6', '所以是 3⁶']},
    {type:'numeric', prompt:'x⁴ · x⁷ 化簡成 x 的幾次方？（只填指數）',
     given:'x^4\\cdot x^7', answer:'11', unit:'', hint1:'4 + 7。',
     steps:['x⁴ · x⁷ = x⁴⁺⁷', '= x¹¹，指數是 11']}],
  worked:{title:'化簡 2³ × 2⁵', given:'2^3\\times 2^5',
    steps:[{label:'底數相同', text:'底數都是 2，可以用指數律'},
           {label:'指數相加', math:'2^{3+5}=2^8'}, {label:'展開', math:'=256'}],
    answer:'2^8=256'},
  explain:'aᵐ 是 m 個 a 相乘，aⁿ 是 n 個 a 相乘，合起來就是 (m + n) 個 a 相乘。',
  source:'自己要記'}),

card({id:'B6', grade:7, category:'num', title:'同底數相除',
  formula:'a^m\\div a^n=a^{m-n},\\ a\\neq 0,\\ m\\geq n',
  variables:[{sym:'a', desc:'相同的底數，不為 0'}, {sym:'m', desc:'被除數的指數'}, {sym:'n', desc:'除數的指數'}],
  usageConditions:'底數相同的乘冪相除時，指數相減（本課程限 m ≥ n）。',
  triggerWords:['同底', '相除', '約分', '化簡'],
  commonMistakes:['指數相除', '前後順序顛倒變成 n − m', '忘記 a ≠ 0'],
  recall:{type:'blank', prompt:'補完同底數相除的指數律。',
    template:'a^m\\div a^n=a^{@1}', blanks:['m-n'],
    bank:['m-n', 'n-m', 'm+n', 'm\\div n'], hint1:'相除 ⇒ 指數相減，被除數的指數放前面。'},
  recog:{type:'choice', prompt:'化簡 5⁷ ÷ 5² 要用哪一條指數律？',
    options:[{t:'同底數相除，指數相減'}, {t:'同底數相乘，指數相加'},
             {t:'乘冪的乘冪，指數相乘'}, {t:'零次方'}],
    answer:0, hint1:'看運算符號是乘還是除。',
    why:'底數同為 5 且是相除，所以指數相減得 5⁵。'},
  apply:{type:'numeric', prompt:'5⁷ ÷ 5² 化簡成 5 的幾次方？（只填指數）',
    given:'5^7\\div 5^2', answer:'5', unit:'', hint1:'7 − 2。',
    steps:['5⁷ ÷ 5² = 5⁷⁻²', '= 5⁵，指數是 5']},
  recogMore:[{type:'choice', prompt:'2⁶ ÷ 2⁶ 等於多少？',
    options:[{math:'1'}, {math:'0'}, {math:'2'}, {math:'2^{12}'}],
    answer:0, hint1:'指數相減之後是幾次方？',
    why:'2⁶ ÷ 2⁶ = 2⁶⁻⁶ = 2⁰ = 1，也可以直接看成同一個數除以自己。'}],
  applyMore:[
    {type:'numeric', prompt:'10⁹ ÷ 10⁴ 化簡成 10 的幾次方？（只填指數）',
     given:'10^9\\div 10^4', answer:'5', unit:'', hint1:'9 − 4。',
     steps:['10⁹ ÷ 10⁴ = 10⁹⁻⁴', '= 10⁵，指數是 5']},
    {type:'numeric', prompt:'a⁶ ÷ a 化簡成 a 的幾次方？（只填指數）',
     given:'a^6\\div a', answer:'5', unit:'', hint1:'單獨的 a 是 a¹。',
     steps:['a⁶ ÷ a¹ = a⁶⁻¹', '= a⁵，指數是 5']}],
  worked:{title:'化簡 5⁷ ÷ 5²', given:'5^7\\div 5^2',
    steps:[{label:'確認同底', text:'底數都是 5'},
           {label:'指數相減', math:'5^{7-2}=5^5'}],
    answer:'5^5'},
  explain:'除法是約分：分子有 7 個 5、分母有 2 個 5，約掉 2 個後剩下 5 個。',
  source:'自己要記'}),

card({id:'B7', grade:7, category:'num', title:'乘冪的乘冪',
  formula:'(a^m)^n=a^{mn}',
  variables:[{sym:'a', desc:'底數'}, {sym:'m', desc:'裡面的指數'}, {sym:'n', desc:'外面的指數'}],
  usageConditions:'整個乘冪再被平方、立方時使用，兩個指數相乘。',
  triggerWords:['再平方', '括號外還有指數', '化簡'],
  commonMistakes:['指數相加', '與同底數相乘搞混', '底數也乘上去'],
  recall:{type:'blank', prompt:'補完乘冪的乘冪。',
    template:'(a^m)^n=a^{@1}', blanks:['mn'],
    bank:['mn', 'm+n', 'm-n', 'm^n'], hint1:'括號外的指數是「重複幾次」，所以指數相乘。'},
  recog:{type:'choice', prompt:'(3²)⁴ 與下列哪一個相等？',
    options:[{math:'3^8'}, {math:'3^6'}, {math:'3^{16}'}, {math:'9^4\\times 3'}],
    answer:0, hint1:'2 × 4。',
    why:'(3²)⁴ 代表 3² 連乘 4 次，共有 8 個 3，所以是 3⁸。'},
  apply:{type:'numeric', prompt:'(2³)⁴ 化簡成 2 的幾次方？（只填指數）',
    given:'(2^3)^4', answer:'12', unit:'', hint1:'3 × 4。',
    steps:['(2³)⁴ = 2³ˣ⁴', '= 2¹², 指數是 12']},
  recogMore:[{type:'choice', prompt:'(2³)² 與 2³ × 2² 哪一個比較大？',
    options:[{t:'(2³)² 比較大'}, {t:'2³ × 2² 比較大'},
             {t:'一樣大'}, {t:'無法比較'}],
    answer:0, hint1:'一個是指數相乘，一個是指數相加。',
    why:'(2³)² = 2⁶ = 64；2³ × 2² = 2⁵ = 32。乘冪的乘冪是指數相乘，比相加大。'}],
  applyMore:[
    {type:'numeric', prompt:'(5²)³ 化簡成 5 的幾次方？（只填指數）',
     given:'(5^2)^3', answer:'6', unit:'', hint1:'2 × 3。',
     steps:['(5²)³ = 5²ˣ³', '= 5⁶，指數是 6']},
    {type:'numeric', prompt:'((x²)³)² 化簡成 x 的幾次方？（只填指數）',
     given:'((x^2)^3)^2', answer:'12', unit:'', hint1:'由內而外：2 × 3 × 2。',
     steps:['(x²)³ = x⁶', '(x⁶)² = x¹²，指數是 12']}],
  worked:{title:'化簡 (2³)⁴', given:'(2^3)^4',
    steps:[{label:'指數相乘', math:'2^{3\\times 4}'}, {label:'得結果', math:'=2^{12}'}],
    answer:'2^{12}'},
  explain:'(aᵐ)ⁿ 是把 aᵐ 重複乘 n 次，總共有 m × n 個 a。與 aᵐaⁿ（指數相加）要分清楚。',
  source:'自己要記'}),

card({id:'B8', grade:7, category:'num', title:'積的乘冪',
  formula:'(ab)^n=a^nb^n',
  variables:[{sym:'a', desc:'第一個因數'}, {sym:'b', desc:'第二個因數'}, {sym:'n', desc:'指數'}],
  usageConditions:'括號內是「相乘」再整體次方時，每個因數都要各自次方。',
  triggerWords:['括號整體次方', '化簡', '科學記號相乘'],
  commonMistakes:['只有一個因數次方', '把 (a+b)ⁿ 也拆開（不成立）'],
  recall:{type:'blank', anyOrder:true, prompt:'補完積的乘冪。',
    template:'(ab)^n=@1@2', blanks:['a^n', 'b^n'],
    bank:['a^n', 'b^n', 'ab^n', '(ab)^n'], hint1:'括號內每一個「相乘」的因數都要各自次方。'},
  recog:{type:'choice', prompt:'下列哪一個式子成立？',
    options:[{math:'(2x)^3=8x^3'}, {math:'(2+x)^3=8+x^3'},
             {math:'(2x)^3=2x^3'}, {math:'(2x)^3=6x^3'}],
    answer:0, hint1:'只有相乘才能各自次方，相加不行。',
    why:'(2x)³ = 2³ · x³ = 8x³。括號內是相加時不能這樣拆。'},
  apply:{type:'numeric', prompt:'(3y)² 展開後，y² 前面的係數是多少？',
    given:'(3y)^2', answer:'9', unit:'', hint1:'3 也要平方。',
    steps:['(3y)² = 3² × y²', '= 9y²，係數是 9']},
  recogMore:[{type:'choice', prompt:'(x + y)² 可以拆成 x² + y² 嗎？',
    options:[{t:'不行，括號內是相加不能各自平方'},
             {t:'可以，和積的乘冪一樣'},
             {t:'可以，但要再乘 2'}, {t:'只有 x、y 都是正數才可以'}],
    answer:0, hint1:'積的乘冪只適用於「相乘」。',
    why:'只有相乘才能各自次方。(x + y)² 要用和的平方公式，等於 x² + 2xy + y²。'}],
  applyMore:[
    {type:'numeric', prompt:'(2x)⁴ 展開後，x⁴ 前面的係數是多少？',
     given:'(2x)^4', answer:'16', unit:'', hint1:'2 也要四次方。',
     steps:['(2x)⁴ = 2⁴ × x⁴', '= 16x⁴，係數是 16']},
    {type:'choice', prompt:'(−2m)³ 展開後是？',
     given:'(-2m)^3', options:[{math:'-8m^3'}, {math:'8m^3'},
       {math:'-6m^3'}, {math:'-2m^3'}],
     answer:0, unit:'', hint1:'負數的奇次方仍然是負的。',
     steps:['(−2m)³ = (−2)³ × m³', '(−2)³ = −8', '所以是 −8m³']}],
  worked:{title:'展開 (3y)²', given:'(3y)^2',
    steps:[{label:'每個因數各自平方', math:'3^2\\times y^2'}, {label:'計算', math:'=9y^2'}],
    answer:'9y^2'},
  explain:'括號裡是乘法才能各自次方。(a + b)ⁿ 不能拆成 aⁿ + bⁿ，那要用乘法公式。',
  source:'自己要記'}),

card({id:'B9', grade:7, category:'num', title:'科學記號',
  formula:'c\\times 10^n,\\ 1\\leq c<10',
  variables:[{sym:'c', desc:'有效數字，必須大於等於 1 且小於 10'}, {sym:'n', desc:'10 的次方，整數'}],
  usageConditions:'表示很大或很小的數（人口、光速、細胞大小）時使用。',
  triggerWords:['科學記號', '約為', '幾乘以 10 的幾次方', '單位換算'],
  commonMistakes:['c 寫成 10 以上或小於 1', '小數點移動方向與指數正負弄反', '忘記 c 可以是小數'],
  recall:{type:'blank', prompt:'科學記號中，前面的數 c 必須符合什麼條件？',
    template:'c\\times 10^n,\\ @1', blanks:['1\\leq c<10'],
    bank:['1\\leq c<10', '0<c<1', '1<c\\leq 10', '0\\leq c<10'],
    hint1:'只能有一位整數，而且不能是 0。'},
  recog:{type:'choice', prompt:'下列哪一個「是」正確的科學記號？',
    options:[{math:'3.6\\times 10^5'}, {math:'36\\times 10^4'},
             {math:'0.36\\times 10^6'}, {math:'3.6\\times 5^{10}'}],
    answer:0, hint1:'檢查前面的數是不是介於 1 到 10 之間。',
    why:'3.6 符合 1 ≤ c < 10；36 太大、0.36 太小、底數必須是 10。'},
  apply:{type:'choice', prompt:'把 52000 寫成科學記號。',
    given:'52000', options:[{math:'5.2\\times 10^4'}, {math:'52\\times 10^3'},
      {math:'5.2\\times 10^3'}, {math:'0.52\\times 10^5'}],
    answer:0, unit:'', hint1:'小數點從最右邊往左移，移幾位指數就是幾。',
    steps:['52000 的小數點往左移 4 位變成 5.2', '所以是 5.2 × 10⁴']},
  recogMore:[{type:'choice', prompt:'3 × 10⁵ 與 9 × 10⁴ 哪一個比較大？',
    options:[{math:'3\\times 10^5'}, {math:'9\\times 10^4'},
             {t:'一樣大'}, {t:'無法比較'}],
    answer:0, hint1:'先比 10 的次方，次方大的就大。',
    why:'3 × 10⁵ = 300000，9 × 10⁴ = 90000。科學記號先看指數，指數大的數就大。'}],
  applyMore:[
    {type:'choice', prompt:'把 0.00037 寫成科學記號。',
     given:'0.00037', options:[{math:'3.7\\times 10^{-4}'}, {math:'3.7\\times 10^{4}'},
       {math:'37\\times 10^{-5}'}, {math:'0.37\\times 10^{-3}'}],
     answer:0, unit:'', hint1:'小數點要往右移 4 位才變成 3.7，往右移指數為負。',
     steps:['0.00037 → 3.7，小數點往右移了 4 位', '往右移 ⇒ 指數為負', '答案是 3.7 × 10⁻⁴']},
    {type:'numeric', prompt:'把 6.1 × 10³ 還原成一般數字。',
     given:'6.1\\times 10^3', answer:'6100', unit:'',
     hint1:'小數點往右移 3 位。',
     steps:['6.1 的小數點往右移 3 位', '= 6100']}],
  worked:{title:'把 52000 寫成科學記號', given:'52000',
    steps:[{label:'調整成 1 ~ 10', text:'52000 → 5.2，小數點往左移了 4 位'},
           {label:'補上 10 的次方', math:'5.2\\times 10^4'}],
    answer:'5.2\\times 10^4'},
  explain:'c 只能有一位整數位（1 到 9）。小數點往左移 n 位，指數就是 +n；往右移 n 位，指數是 −n。',
  source:'自己要記'}),

card({id:'B10', grade:7, category:'num', title:'比例式的內外項相乘',
  formula:'a:b=c:d\\Rightarrow ad=bc',
  variables:[{sym:'a, d', desc:'外項'}, {sym:'b, c', desc:'內項'}],
  usageConditions:'題目給兩組比相等，要求未知數時使用。',
  triggerWords:['比', '比例', '相當於', '成正比', '對應'],
  commonMistakes:['對錯內外項', '把 a:b 的順序寫反', '單位不同就直接列比'],
  recall:{type:'blank', anyOrder:true, prompt:'比例式可以怎麼變成等式？',
    template:'a:b=c:d\\Rightarrow @1=@2', blanks:['ad', 'bc'],
    bank:['ad', 'bc', 'ac', 'bd'], hint1:'外項相乘等於內項相乘。'},
  recog:{type:'choice', prompt:'「3 枝筆 45 元，7 枝筆多少元？」最適合列成？',
    options:[{math:'3:45=7:x'}, {math:'3:7=x:45'}, {math:'3:x=45:7'}, {math:'45:3=7:x'}],
    answer:0, hint1:'同一種量要放在比的同一邊，順序要一致。',
    why:'「枝數 : 價錢」的順序前後必須一致，寫成 3:45 = 7:x，交叉相乘得 3x = 315，x = 105。其餘選項把兩種量混在同一邊或順序顛倒，會解出錯誤答案。'},
  apply:{type:'numeric', prompt:'3 枝筆 45 元，7 枝筆要多少元？',
    given:'3:45=7:x', answer:'105', unit:'元', hint1:'交叉相乘：3x = 45 × 7。',
    steps:['3 : 45 = 7 : x', '3x = 45 × 7 = 315', 'x = 105（元）']},
  recogMore:[{type:'choice', prompt:'已知 a : b = c : d，下列哪一個一定成立？',
    options:[{math:'ad=bc'}, {math:'ab=cd'}, {math:'ac=bd'}, {math:'a+d=b+c'}],
    answer:0, hint1:'外項相乘等於內項相乘。',
    why:'a 與 d 是外項、b 與 c 是內項，所以 ad = bc。'}],
  applyMore:[
    {type:'numeric', prompt:'若 2 : 5 = x : 20，則 x 是多少？',
     given:'2:5=x:20', answer:'8', unit:'', hint1:'交叉相乘：5x = 2 × 20。',
     steps:['2 : 5 = x : 20', '5x = 40', 'x = 8']},
    {type:'numeric', prompt:'地圖比例尺 1 : 50000，圖上 3 公分代表實際幾公尺？',
     given:'1:50000', answer:'1500', unit:'公尺',
     hint1:'先算出實際幾公分，再換成公尺。',
     steps:['實際長度 = 3 × 50000 = 150000（公分）', '150000 公分 ÷ 100 = 1500（公尺）']}],
  worked:{title:'3 枝 45 元，求 7 枝的價錢', given:'3:45=7:x',
    steps:[{label:'列比例式', math:'3:45=7:x'},
           {label:'內外項相乘', math:'3x=45\\times 7'},
           {label:'計算', math:'3x=315'},
           {label:'求解', math:'x=105'}],
    answer:'105 \\text{ 元}'},
  explain:'a : b = c : d 中，a 和 d 是外項、b 和 c 是內項。列比例時同一種量要放同一個位置。',
  source:'自己要記'}),

card({id:'B11', grade:7, category:'num', title:'正比',
  formula:'y=kx',
  variables:[{sym:'k', desc:'比例常數，等於 y ÷ x'}, {sym:'x, y', desc:'兩個成正比的量'}],
  usageConditions:'一個量變成幾倍，另一個量也變成同樣幾倍時使用；圖形是過原點的直線。',
  triggerWords:['成正比', '愈多愈多', '倍數關係', '單價固定'],
  commonMistakes:['把正比寫成 y = x + k', '與反比混用', 'k 求成 x ÷ y'],
  recall:{type:'blank', prompt:'y 與 x 成正比時，關係式是？',
    template:'y=@1', blanks:['kx'], bank:['kx', '\\frac{k}{x}', 'k+x', 'kx^2'],
    hint1:'兩量的「商」固定，圖形是通過原點的直線。'},
  recog:{type:'choice', prompt:'下列哪一組成正比？',
    options:[{t:'買糖果的總價與數量（單價固定）'}, {t:'固定路程下的速率與時間'},
             {t:'長方形面積固定時的長與寬'}, {t:'剩餘金額與已花金額'}],
    answer:0, hint1:'看看兩個量的「商」是不是固定。',
    why:'單價固定時，總價 ÷ 數量 = 單價（常數），符合 y = kx；速率與時間、長與寬是乘積固定，屬於反比。'},
  apply:{type:'numeric', prompt:'y 與 x 成正比，x = 4 時 y = 12。當 x = 7 時 y 是多少？',
    given:'x=4,\\ y=12', answer:'21', unit:'', hint1:'先求 k = y ÷ x。',
    steps:['k = 12 ÷ 4 = 3', 'y = 3x，代入 x = 7', 'y = 3 × 7 = 21']},
  recogMore:[{type:'choice', prompt:'成正比的兩個量畫成圖形，會是什麼樣子？',
    options:[{t:'通過原點的直線'}, {t:'不通過原點的直線'},
             {t:'雙曲線'}, {t:'拋物線'}],
    answer:0, hint1:'x = 0 時 y 是多少？',
    why:'y = kx 中 x = 0 時 y = 0，所以圖形一定通過原點，而且是直線。'}],
  applyMore:[
    {type:'numeric', prompt:'y 與 x 成正比，x = 5 時 y = 35，比例常數 k 是多少？',
     given:'x=5,\\ y=35', answer:'7', unit:'', hint1:'k = y ÷ x。',
     steps:['k = 35 ÷ 5', '= 7']},
    {type:'choice', prompt:'蘋果每公斤 45 元，買 x 公斤的總價 y 是？',
     given:'', options:[{math:'y=45x'}, {math:'y=\\frac{45}{x}'},
       {math:'y=x+45'}, {math:'xy=45'}],
     answer:0, unit:'', hint1:'買愈多總價愈高，而且是固定倍數。',
     steps:['單價固定 45 元', '總價 = 單價 × 重量', 'y = 45x（成正比）']}],
  worked:{title:'求正比關係中的 y', given:'x=4 \\text{ 時 } y=12',
    steps:[{label:'求比例常數', math:'k=\\frac{12}{4}=3'},
           {label:'寫關係式', math:'y=3x'},
           {label:'代入', math:'y=3\\times 7=21'}],
    answer:'21'},
  explain:'k 是比例常數，等於 y ÷ x，兩量的商固定。x 變 2 倍時 y 也變 2 倍。',
  source:'自己要記'}),

card({id:'B12', grade:7, category:'num', title:'反比',
  formula:'xy=k \\text{ 或 } y=\\frac{k}{x}',
  variables:[{sym:'k', desc:'比例常數，等於 x × y'}, {sym:'x, y', desc:'兩個成反比的量'}],
  usageConditions:'一個量變大、另一個量按比例變小，兩量乘積固定時使用。',
  triggerWords:['成反比', '愈多愈少', '幾個人做幾天', '固定總量分配'],
  commonMistakes:['寫成 y = kx', '用相加相減處理', '忘記 x ≠ 0'],
  recall:{type:'blank', prompt:'y 與 x 成反比時，乘積關係是？',
    template:'xy=@1', blanks:['k'], bank:['k', 'kx', '\\frac{k}{x}', 'x+y'],
    hint1:'兩量的「積」固定。'},
  recog:{type:'choice', prompt:'下列哪一組成反比？',
    options:[{t:'工作總量固定時，人數與所需天數'}, {t:'單價固定時，數量與總價'},
             {t:'正方形的邊長與周長'}, {t:'時間與已行走的距離（等速）'}],
    answer:0, hint1:'兩量相乘是不是固定？',
    why:'人數 × 天數 = 工作總量（固定），是反比；其餘三組都是商固定，屬於正比。'},
  apply:{type:'numeric', prompt:'y 與 x 成反比，x = 3 時 y = 8。當 x = 4 時 y 是多少？',
    given:'x=3,\\ y=8', answer:'6', unit:'', hint1:'先求 k = xy。',
    steps:['k = 3 × 8 = 24', 'y = 24 ÷ x，代入 x = 4', 'y = 24 ÷ 4 = 6']},
  recogMore:[{type:'choice', prompt:'成反比的兩個量畫成圖形，會通過原點嗎？',
    options:[{t:'不會，x 與 y 都不能是 0'}, {t:'會，和正比一樣'},
             {t:'只有 k > 0 時會'}, {t:'無法判斷'}],
    answer:0, hint1:'xy = k，若 x = 0 乘積就變成 0 了。',
    why:'反比的乘積固定且不為 0，所以 x、y 都不能是 0，圖形不會通過原點。'}],
  applyMore:[
    {type:'numeric', prompt:'12 個人 5 天可以完成的工作，6 個人要做幾天？',
     given:'12\\times 5=60', answer:'10', unit:'天',
     hint1:'人數 × 天數 = 工作總量（固定）。',
     steps:['工作總量 = 12 × 5 = 60', '6 × 天數 = 60', '天數 = 10']},
    {type:'numeric', prompt:'x 與 y 成反比且 xy = 36，當 x = 9 時 y 是多少？',
     given:'xy=36,\\ x=9', answer:'4', unit:'', hint1:'36 ÷ 9。',
     steps:['xy = 36', '9y = 36', 'y = 4']}],
  worked:{title:'求反比關係中的 y', given:'x=3 \\text{ 時 } y=8',
    steps:[{label:'求比例常數', math:'k=3\\times 8=24'},
           {label:'寫關係式', math:'y=\\frac{24}{x}'},
           {label:'代入', math:'y=\\frac{24}{4}=6'}],
    answer:'6'},
  explain:'反比的固定量是「乘積」xy = k。正比固定的是商，反比固定的是積，這是最常混淆的地方。',
  source:'自己要記'}),

card({id:'B13', grade:7, category:'num', title:'百分率',
  formula:'\\text{百分率}=\\frac{\\text{部分}}{\\text{全部}}\\times 100\\%',
  variables:[{sym:'部分', desc:'被問到的那一部分數量'}, {sym:'全部', desc:'基準量（分母）'}],
  usageConditions:'求「佔幾 %」「及格率」「命中率」時使用，關鍵是找對基準量。',
  triggerWords:['百分之', '佔', '成功率', '及格率', '打折'],
  commonMistakes:['分子分母顛倒', '基準量找錯', '忘記乘 100%'],
  recall:{type:'blank', prompt:'補完百分率公式。',
    template:'\\text{百分率}=\\frac{@1}{@2}\\times 100\\%', blanks:['\\text{部分}', '\\text{全部}'],
    bank:['\\text{部分}', '\\text{全部}', '\\text{差額}', '\\text{總和}'],
    hint1:'分母是「基準量」，也就是「佔誰的」那個誰。'},
  recog:{type:'choice', prompt:'「25 人中有 20 人及格，及格率多少？」分母應該放哪個數？',
    options:[{t:'25（總人數）'}, {t:'20（及格人數）'}, {t:'5（不及格人數）'}, {t:'100'}],
    answer:0, hint1:'「佔全班的百分之幾」＝分母是全班。',
    why:'基準量是全班 25 人，所以 20 ÷ 25 × 100% = 80%。'},
  apply:{type:'numeric', prompt:'25 人中有 20 人及格，及格率是百分之多少？（只填數字）',
    given:'\\frac{20}{25}', answer:'80', unit:'%', hint1:'20 ÷ 25 = 0.8。',
    steps:['20 ÷ 25 = 0.8', '0.8 × 100% = 80%']},
  recogMore:[{type:'choice', prompt:'「今年比去年多 20%」，這裡的基準量是什麼？',
    options:[{t:'去年的數量'}, {t:'今年的數量'},
             {t:'今年與去年的和'}, {t:'多出來的數量'}],
    answer:0, hint1:'「比誰多」的那個「誰」就是基準量。',
    why:'「比去年多」代表以去年為基準，所以今年 = 去年 × (1 + 0.2)。'}],
  applyMore:[
    {type:'numeric', prompt:'60 人中有 15 人搭捷運，佔百分之多少？（只填數字）',
     given:'\\frac{15}{60}', answer:'25', unit:'%', hint1:'15 ÷ 60 = 0.25。',
     steps:['15 ÷ 60 = 0.25', '0.25 × 100% = 25%']},
    {type:'numeric', prompt:'某班 40 人，及格率 85%，及格的有幾人？',
     given:'40\\times 0.85', answer:'34', unit:'人',
     hint1:'先把 85% 化成 0.85 再乘以 40。',
     steps:['40 × 85% = 40 × 0.85', '= 34（人）']}],
  worked:{title:'求及格率', given:'20 \\text{ 人及格，共 } 25 \\text{ 人}',
    steps:[{label:'找基準量', text:'全班 25 人是分母'},
           {label:'代入', math:'\\frac{20}{25}\\times 100\\%'},
           {label:'計算', math:'=0.8\\times 100\\%=80\\%'}],
    answer:'80\\%'},
  explain:'百分率的分母是「基準量」。題目說「佔 A 的百分之幾」，A 就是分母。',
  source:'自己要記'}),

card({id:'B14', grade:7, category:'num', title:'增加率',
  formula:'\\text{新值}=\\text{原值}\\times(1+\\text{增加率})',
  variables:[{sym:'增加率', desc:'先把百分率化成小數，例如 20% 要寫成 0.2'},
             {sym:'原值', desc:'變動前的數量'}],
  usageConditions:'漲價、加薪、人口成長、加成時使用；括號內是 1 加上增加率。',
  triggerWords:['上漲', '增加', '成長', '加成', '調漲'],
  commonMistakes:['只乘 r 忘了 1', '把 20% 代成 20', '連續兩次成長用相加'],
  recall:{type:'blank', prompt:'增加 r 之後的新值是？',
    template:'\\text{新值}=\\text{原值}\\times@1', blanks:['(1+\\text{增加率})'],
    bank:['(1+\\text{增加率})', '(1-\\text{增加率})', '\\text{增加率}', '(1+\\text{增加率})^2'],
    hint1:'原本的 1 倍要留著，再加上增加的部分。'},
  recog:{type:'choice', prompt:'定價 500 元的商品調漲 20%，算式應該是？',
    options:[{math:'500\\times(1+0.2)'}, {math:'500\\times 0.2'},
             {math:'500\\times(1-0.2)'}, {math:'500+20'}],
    answer:0, hint1:'漲價後仍然包含原來的價錢。',
    why:'新價 = 原價 × (1 + 0.2) = 500 × 1.2 = 600 元；500 × 0.2 只是「漲的部分」。'},
  apply:{type:'numeric', prompt:'定價 500 元的商品調漲 20% 後是多少元？',
    given:'500\\times(1+0.2)', answer:'600', unit:'元', hint1:'500 × 1.2。',
    steps:['500 × (1 + 0.2) = 500 × 1.2', '= 600（元）']},
  recogMore:[{type:'choice', prompt:'某商品先漲 10%，再漲 10%，總共漲了百分之多少？',
    options:[{t:'21%'}, {t:'20%'}, {t:'11%'}, {t:'100%'}],
    answer:0, hint1:'連續變化要相乘，不能相加。',
    why:'1.1 × 1.1 = 1.21，所以總共漲了 21%，不是 20%。'}],
  applyMore:[
    {type:'numeric', prompt:'原價 800 元的商品調漲 15%，新價格是多少元？',
     given:'800\\times(1+0.15)', answer:'920', unit:'元',
     hint1:'800 × 1.15。',
     steps:['800 × (1 + 0.15) = 800 × 1.15', '= 920（元）']},
    {type:'numeric', prompt:'某鎮人口 2000 人，一年成長 5%，一年後有多少人？',
     given:'2000\\times(1+0.05)', answer:'2100', unit:'人',
     hint1:'2000 × 1.05。',
     steps:['2000 × (1 + 0.05) = 2000 × 1.05', '= 2100（人）']}],
  worked:{title:'500 元調漲 20%', given:'\\text{原值}=500,\\ \\text{增加率}=20\\%',
    steps:[{label:'把 20% 化成小數', math:'\\text{增加率}=0.2'},
           {label:'代入', math:'500\\times(1+0.2)'},
           {label:'計算', math:'=500\\times 1.2=600'}],
    answer:'600 \\text{ 元}'},
  explain:'括號裡的 1 代表原本的全部，增加率代表多出來的部分。百分率一定要先化成小數再代入。',
  source:'自己要記'}),

card({id:'B15', grade:7, category:'num', title:'減少率與打折',
  formula:'\\text{新值}=\\text{原值}\\times(1-\\text{減少率})',
  variables:[{sym:'減少率', desc:'先把百分率化成小數，例如 20% 要寫成 0.2'},
             {sym:'原值', desc:'變動前的數量'}],
  usageConditions:'降價、打折、折舊、減量時使用。台灣的「打八折」是乘 0.8。',
  triggerWords:['打折', '下降', '減少', '折扣', '降價'],
  commonMistakes:['打八折算成 1 − 0.8 = 0.2', '減 20% 與打 2 折混淆', '連續打折用相加'],
  recall:{type:'blank', prompt:'減少 r 之後的新值是？',
    template:'\\text{新值}=\\text{原值}\\times@1', blanks:['(1-\\text{減少率})'],
    bank:['(1-\\text{減少率})', '(1+\\text{減少率})', '\\text{減少率}', '(1-\\text{減少率})^2'],
    hint1:'剩下的比例＝1 減掉減少的比例。'},
  recog:{type:'choice', prompt:'原價 800 元「打八折」，應該乘以多少？',
    options:[{math:'0.8'}, {math:'0.2'}, {math:'1.8'}, {math:'8'}],
    answer:0, hint1:'打八折＝付原價的十分之八。',
    why:'打八折就是付原價的 80%，所以乘 0.8 得 640 元。若題目說「減少 20%」，同樣是乘（1 − 0.2）= 0.8。'},
  apply:{type:'numeric', prompt:'原價 800 元打八折後是多少元？',
    given:'800\\times 0.8', answer:'640', unit:'元', hint1:'八折＝乘 0.8。',
    steps:['800 × 0.8 = 640（元）']},
  recogMore:[{type:'choice', prompt:'「打九折」是乘以多少？',
    options:[{math:'0.9'}, {math:'0.1'}, {math:'1.9'}, {math:'9'}],
    answer:0, hint1:'打九折＝付原價的十分之九。',
    why:'打 n 折就是付原價的 n/10，所以九折是乘 0.9（等於減少 10%）。'}],
  applyMore:[
    {type:'numeric', prompt:'原價 1200 元打七五折，要付多少元？',
     given:'1200\\times 0.75', answer:'900', unit:'元',
     hint1:'七五折＝乘 0.75。',
     steps:['1200 × 0.75 = 900（元）']},
    {type:'numeric', prompt:'原價 250 元的商品減少 40%，新價格是多少元？',
     given:'250\\times(1-0.4)', answer:'150', unit:'元',
     hint1:'250 × 0.6。',
     steps:['250 × (1 − 0.4) = 250 × 0.6', '= 150（元）']}],
  worked:{title:'800 元打八折', given:'\\text{原值}=800',
    steps:[{label:'折數換成小數', text:'打八折＝付 80%＝乘 0.8'},
           {label:'代入', math:'800\\times(1-0.2)=800\\times 0.8'},
           {label:'計算', math:'=640'}],
    answer:'640 \\text{ 元}'},
  explain:'「打 n 折」是乘 n/10；「減少幾成幾」是乘（1 − 減少率）。八折與減少 20% 都是乘 0.8。',
  source:'自己要記'}),

card({id:'B16', grade:7, category:'num', title:'路程公式',
  formula:'\\text{路程}=\\text{速率}\\times\\text{時間}',
  variables:[{sym:'路程', desc:'走過的距離'}, {sym:'速率', desc:'每單位時間走的距離'}, {sym:'時間', desc:'花費的時間'}],
  usageConditions:'等速運動、相遇問題、追及問題都以此為基礎。',
  triggerWords:['每小時', '公里/時', '相遇', '追上', '幾分鐘後'],
  commonMistakes:['單位不一致（分與小時混用）', '相遇問題忘記兩人速率相加', '把時間當路程'],
  recall:{type:'blank', anyOrder:true, prompt:'補完路程公式。',
    template:'\\text{路程}=@1\\times@2', blanks:['\\text{速率}', '\\text{時間}'],
    bank:['\\text{速率}', '\\text{時間}', '\\text{路程}', '\\text{平均}'],
    hint1:'速率乘時間；求時間就把路程除以速率。'},
  recog:{type:'choice', prompt:'「時速 60 公里開 2.5 小時走多遠」該用哪個式子？',
    options:[{math:'60\\times 2.5'}, {math:'60\\div 2.5'}, {math:'2.5\\div 60'}, {math:'60+2.5'}],
    answer:0, hint1:'要求的是路程。',
    why:'路程 = 速率 × 時間 = 60 × 2.5 = 150 公里。'},
  apply:{type:'numeric', prompt:'時速 60 公里行駛 2.5 小時，共走幾公里？',
    given:'60\\times 2.5', answer:'150', unit:'公里', hint1:'單位已一致，直接相乘。',
    steps:['60 × 2.5 = 150（公里）']},
  recogMore:[{type:'choice', prompt:'時速 60 公里，走 30 分鐘可以走多遠？',
    options:[{t:'30 公里'}, {t:'60 公里'}, {t:'1800 公里'}, {t:'2 公里'}],
    answer:0, hint1:'時速配的時間單位要是「小時」。',
    why:'30 分鐘 = 0.5 小時，60 × 0.5 = 30 公里。單位沒統一是最常見的錯誤。'}],
  applyMore:[
    {type:'numeric', prompt:'要走 240 公里，時速 80 公里，需要幾小時？',
     given:'240\\div 80', answer:'3', unit:'小時',
     hint1:'時間 = 路程 ÷ 速率。',
     steps:['時間 = 240 ÷ 80', '= 3（小時）']},
    {type:'numeric', prompt:'4 小時走了 200 公里，時速是多少公里？',
     given:'200\\div 4', answer:'50', unit:'公里/小時',
     hint1:'速率 = 路程 ÷ 時間。',
     steps:['速率 = 200 ÷ 4', '= 50（公里／小時）']}],
  worked:{title:'時速 60 公里走 2.5 小時', given:'\\text{速率}=60,\\ \\text{時間}=2.5',
    steps:[{label:'檢查單位', text:'速率是「公里／小時」，時間是小時，單位一致'},
           {label:'代入', math:'60\\times 2.5'}, {label:'計算', math:'=150'}],
    answer:'150 \\text{ 公里}'},
  explain:'三個量互相變形：時間 = 路程 ÷ 速率、速率 = 路程 ÷ 時間。代入前一定要先統一單位。',
  source:'自己要記'}),

card({id:'B17', grade:7, category:'num', title:'平均速率',
  formula:'\\text{平均速率}=\\frac{\\text{總路程}}{\\text{總時間}}',
  variables:[{sym:'總路程', desc:'全程走過的距離總和'}, {sym:'總時間', desc:'全程花費的時間總和'}],
  usageConditions:'去程回程速率不同、分段行駛時使用，不能把兩段速率直接平均。',
  triggerWords:['平均速率', '來回', '去程回程', '全程'],
  commonMistakes:['把兩段速率相加除以 2', '忘記把時間加總', '只算單程'],
  recall:{type:'blank', prompt:'補完平均速率公式。',
    template:'\\text{平均速率}=\\frac{@1}{@2}', blanks:['\\text{總路程}', '\\text{總時間}'],
    bank:['\\text{總路程}', '\\text{總時間}', '\\text{速率和}', '2'],
    hint1:'全部距離除以全部時間，不是兩個速率相加除以 2。'},
  recog:{type:'choice', prompt:'去程時速 60、回程時速 40，全程平均速率是？',
    options:[{t:'總路程 ÷ 總時間，不是 50'}, {t:'(60 + 40) ÷ 2 = 50'},
             {t:'60 × 40 ÷ 2'}, {t:'無法計算'}],
    answer:0, hint1:'兩段花的時間不一樣長。',
    why:'慢的那一段花較多時間，平均會被拉低。必須用總路程 ÷ 總時間。'},
  apply:{type:'numeric', prompt:'某人去程 120 公里花 2 小時，回程 120 公里花 3 小時，平均速率是每小時幾公里？',
    given:'120+120=240,\\ 2+3=5', answer:'48', unit:'公里/小時',
    hint1:'總路程 240，總時間 5。',
    steps:['總路程 = 120 + 120 = 240（公里）', '總時間 = 2 + 3 = 5（小時）', '240 ÷ 5 = 48（公里／小時）']},
  recogMore:[{type:'choice', prompt:'為什麼去程與回程的速率不能直接平均？',
    options:[{t:'因為兩段花的時間不一樣長'}, {t:'因為兩段距離不一樣'},
             {t:'因為速率不能相加'}, {t:'其實可以直接平均'}],
    answer:0, hint1:'慢的那一段是不是花比較久？',
    why:'速率慢的那段花的時間比較長，對平均的影響也比較大，所以必須用總路程 ÷ 總時間。'}],
  applyMore:[
    {type:'numeric', prompt:'去程 60 公里花 1 小時、回程 60 公里花 2 小時，平均速率是每小時幾公里？',
     given:'\\text{總路程}=120,\\ \\text{總時間}=3', answer:'40', unit:'公里/小時',
     hint1:'120 ÷ 3，不是 (60 + 30) ÷ 2。',
     steps:['總路程 = 60 + 60 = 120（公里）', '總時間 = 1 + 2 = 3（小時）', '120 ÷ 3 = 40']},
    {type:'numeric', prompt:'先走 100 公尺花 20 秒，再走 200 公尺花 30 秒，平均速率是每秒幾公尺？',
     given:'\\text{總路程}=300,\\ \\text{總時間}=50', answer:'6', unit:'公尺/秒',
     hint1:'300 ÷ 50。',
     steps:['總路程 = 100 + 200 = 300（公尺）', '總時間 = 20 + 30 = 50（秒）', '300 ÷ 50 = 6']}],
  worked:{title:'去程 2 小時、回程 3 小時的平均速率', given:'\\text{各 } 120 \\text{ 公里}',
    steps:[{label:'算總路程', math:'120+120=240'},
           {label:'算總時間', math:'2+3=5'},
           {label:'相除', math:'\\frac{240}{5}=48'}],
    answer:'48 \\text{ 公里／小時}'},
  explain:'平均速率是「總量對總量」，不是兩個速率的算術平均。只有兩段時間相同時，答案才會剛好等於算術平均。',
  source:'自己要記'}),

card({id:'B18', grade:7, category:'num', title:'最大公因數與最小公倍數的關係',
  formula:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=ab',
  variables:[{sym:'gcd(a,b)', desc:'最大公因數'}, {sym:'lcm(a,b)', desc:'最小公倍數'},
             {sym:'a, b', desc:'兩個正整數'}],
  usageConditions:'已知兩數與其中一個公因數／公倍數，求另一個時使用。只適用於兩個數。',
  triggerWords:['最大公因數', '最小公倍數', '兩數乘積', '同時'],
  commonMistakes:['用在三個數上（不成立）', '把 gcd 與 lcm 位置弄反'],
  recall:{type:'blank', prompt:'補完最大公因數與最小公倍數的關係。',
    template:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=@1', blanks:['ab'],
    bank:['ab', 'a+b', 'a-b', '\\frac{a}{b}'], hint1:'兩者相乘剛好等於原本兩數的乘積。'},
  recog:{type:'choice', prompt:'已知兩數乘積 72、最大公因數 6，可以直接求出什麼？',
    options:[{t:'最小公倍數'}, {t:'兩數各是多少'}, {t:'兩數的和'}, {t:'兩數的差'}],
    answer:0, hint1:'公式裡有四個量，知道三個就能求第四個。',
    why:'lcm = 兩數乘積 ÷ gcd = 72 ÷ 6 = 12。但這個公式無法單獨決定兩個數各是多少。'},
  apply:{type:'numeric', prompt:'兩數乘積為 72、最大公因數為 6，最小公倍數是多少？',
    given:'ab=72,\\ \\gcd=6', answer:'12', unit:'', hint1:'lcm = ab ÷ gcd。',
    steps:['gcd × lcm = ab', '6 × lcm = 72', 'lcm = 12']},
  recogMore:[{type:'choice', prompt:'gcd × lcm = 兩數乘積，這個關係對三個數也成立嗎？',
    options:[{t:'不成立，只對兩個數成立'}, {t:'成立，任意多個數都可以'},
             {t:'只有三個數都是質數才成立'}, {t:'只有三個數互質才成立'}],
    answer:0, hint1:'公式推導時只配對了兩個數的質因數次方。',
    why:'這個關係只對「兩個數」成立，三個數以上必須回到質因數分解逐一處理。'}],
  applyMore:[
    {type:'numeric', prompt:'12 與 18 的最大公因數是 6，最小公倍數是多少？',
     given:'12\\times 18=216,\\ \\gcd=6', answer:'36', unit:'',
     hint1:'lcm = 兩數乘積 ÷ gcd。',
     steps:['12 × 18 = 216', 'lcm = 216 ÷ 6', '= 36']},
    {type:'numeric', prompt:'兩數的最大公因數是 4、最小公倍數是 60，兩數乘積是多少？',
     given:'\\gcd=4,\\ \\operatorname{lcm}=60', answer:'240', unit:'',
     hint1:'兩數乘積 = gcd × lcm。',
     steps:['兩數乘積 = 4 × 60', '= 240']}],
  worked:{title:'由乘積與 gcd 求 lcm', given:'ab=72,\\ \\gcd(a,b)=6',
    steps:[{label:'寫公式', math:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=ab'},
           {label:'代入', math:'6\\times\\operatorname{lcm}=72'},
           {label:'求解', math:'\\operatorname{lcm}=12'}],
    answer:'12'},
  explain:'把兩數做質因數分解後，gcd 取各質因數的最小次方、lcm 取最大次方，兩者相乘剛好把所有次方補齊成 ab。此關係只對「兩個數」成立。',
  source:'自己要記'}),

card({id:'B19', grade:7, category:'num', kind:'property', title:'不等式乘除負數要變號',
  formula:'\\text{兩邊同乘或同除負數}\\Rightarrow\\text{不等號反向}',
  variables:[{sym:'反向', desc:'大於變小於、小於變大於；≥ 與 ≤ 也一樣要對調'},
             {sym:'加減', desc:'只有乘除負數要變號，加減任何數都不必變'}],
  usageConditions:'解不等式時，只要兩邊同乘或同除一個負數，不等號方向就要顛倒。',
  triggerWords:['解不等式', '至少', '至多', '−x 的係數'],
  commonMistakes:['乘除負數忘記變號', '加減負數時卻多此一舉去變號'],
  recall:{type:'blank', prompt:'不等式兩邊同乘一個負數時，不等號會？',
    template:'\\text{兩邊同乘或同除負數}\\Rightarrow\\text{不等號}@1',
    blanks:['\\text{反向}'],
    bank:['\\text{反向}', '\\text{不變}', '\\text{變成等號}', '\\text{消失}'],
    hint1:'例如 2 < 3，兩邊同乘 −1 之後變成 −2 > −3。'},
  recog:{type:'choice', prompt:'解 −2x > 6 時，兩邊同除以 −2，不等號會變成？',
    options:[{math:'x<-3'}, {math:'x>-3'}, {math:'x<3'}, {math:'x>3'}],
    answer:0, hint1:'除以負數 ⇒ 不等號反向。',
    why:'兩邊同除以 −2（負數），不等號由 > 變成 <，得 x < −3。'},
  apply:{type:'choice', prompt:'解不等式 −3x ≤ 12，答案是？',
    given:'-3x\\leq 12', options:[{math:'x\\geq -4'}, {math:'x\\leq -4'},
      {math:'x\\geq 4'}, {math:'x\\leq 4'}],
    answer:0, unit:'', hint1:'兩邊同除以 −3，≤ 要變成 ≥。',
    steps:['兩邊同除以 −3（負數）', '不等號反向：x ≥ 12 ÷ (−3)', 'x ≥ −4']},
  recogMore:[{type:'choice', prompt:'不等式兩邊同時「加上 −3」，不等號要變向嗎？',
    options:[{t:'不用，只有乘除負數才要變'}, {t:'要變，因為加的是負數'},
             {t:'要變，因為兩邊都動了'}, {t:'看原本是大於還是小於'}],
    answer:0, hint1:'加減和乘除的規則不一樣。',
    why:'加減任何數都不會改變不等號方向，只有兩邊同乘或同除「負數」時才要反向。'}],
  applyMore:[
    {type:'choice', prompt:'解不等式 −x > 5，答案是？',
     given:'-x>5', options:[{math:'x<-5'}, {math:'x>-5'},
       {math:'x<5'}, {math:'x>5'}],
     answer:0, unit:'', hint1:'兩邊同乘 −1，不等號要反向。',
     steps:['兩邊同乘 −1（負數）', '不等號反向：x < −5']},
    {type:'choice', prompt:'解不等式 2 − x < 7，答案是？',
     given:'2-x<7', options:[{math:'x>-5'}, {math:'x<-5'},
       {math:'x>5'}, {math:'x<5'}],
     answer:0, unit:'', hint1:'先移項成 −x < 5，再乘 −1。',
     steps:['2 − x < 7 ⇒ −x < 5', '兩邊同乘 −1，不等號反向', 'x > −5']}],
  worked:{title:'解 −3x ≤ 12', given:'-3x\\leq 12',
    steps:[{label:'兩邊除以 −3', text:'除數是負的，不等號要反向'},
           {label:'反向後', math:'x\\geq\\frac{12}{-3}'},
           {label:'計算', math:'x\\geq -4'}],
    answer:'x\\geq -4'},
  explain:'加、減任何數都不必變號；只有乘或除以「負數」時才要把不等號反過來。',
  source:'自己要記'}),

card({id:'C1', grade:8, category:'num', title:'根號的平方',
  formula:'(\\sqrt{a})^2=a,\\ a\\geq 0',
  variables:[{sym:'a', desc:'被開方數，必須大於等於 0'}],
  usageConditions:'先開根號再平方時，直接回到原數。',
  triggerWords:['根號', '平方', '化簡', '有理化'],
  commonMistakes:['與 √(a²) = |a| 搞混', '忘記 a ≥ 0 的限制'],
  recall:{type:'blank', prompt:'補完根號的平方。',
    template:'(\\sqrt{a})^2=@1,\\ a\\geq 0', blanks:['a'],
    bank:['a', '|a|', 'a^2', '\\sqrt{a}'], hint1:'先開根號再平方，兩個動作互相抵消。'},
  recog:{type:'choice', prompt:'(√7)² 等於多少？',
    options:[{math:'7'}, {math:'\\sqrt{7}'}, {math:'49'}, {math:'14'}],
    answer:0, hint1:'開根號與平方互為反運算。',
    why:'(√7)² = 7，因為 √7 是「平方後等於 7 的正數」。'},
  apply:{type:'numeric', prompt:'計算 (√5)² + (√11)² 的值。',
    given:'(\\sqrt{5})^2+(\\sqrt{11})^2', answer:'16', unit:'',
    hint1:'各自還原成被開方數。',
    steps:['(√5)² = 5，(√11)² = 11', '5 + 11 = 16']},
  recogMore:[{type:'choice', prompt:'(√a)² 與 √(a²) 最大的差別是什麼？',
    options:[{t:'(√a)² 要求 a ≥ 0；√(a²) 的結果要取絕對值'},
             {t:'兩者完全相同'},
             {t:'(√a)² 結果可能是負的'}, {t:'√(a²) 要求 a ≥ 0'}],
    answer:0, hint1:'想想 a = −3 時兩個式子分別是什麼。',
    why:'a = −3 時 √a 沒有意義，但 √((−3)²) = 3 = |−3|。所以前者限制 a ≥ 0，後者要加絕對值。'}],
  applyMore:[
    {type:'numeric', prompt:'計算 (√13)² 的值。',
     given:'(\\sqrt{13})^2', answer:'13', unit:'', hint1:'開根號再平方會抵消。',
     steps:['(√13)² = 13']},
    {type:'numeric', prompt:'計算 (√2)² × (√8)² 的值。',
     given:'(\\sqrt{2})^2\\times(\\sqrt{8})^2', answer:'16', unit:'',
     hint1:'先各自還原成被開方數。',
     steps:['(√2)² = 2，(√8)² = 8', '2 × 8 = 16']}],
  worked:{title:'計算 (√5)² + (√11)²', given:'(\\sqrt{5})^2+(\\sqrt{11})^2',
    steps:[{label:'還原', math:'5+11'}, {label:'計算', math:'=16'}],
    answer:'16'},
  explain:'(√a)² 的前提是 a ≥ 0（否則根號沒有意義），所以結果直接是 a，不必加絕對值。',
  source:'自己要記'}),

card({id:'C2', grade:8, category:'num', title:'平方再開根號',
  formula:'\\sqrt{a^2}=|a|',
  variables:[{sym:'a', desc:'任意實數，可正可負'}],
  usageConditions:'先平方再開根號時，結果一定是非負數，所以要加絕對值。',
  triggerWords:['根號', '平方', '絕對值', '化簡'],
  commonMistakes:['直接寫成 a，忽略 a 可能是負數', '與 (√a)² = a 搞混'],
  recall:{type:'blank', prompt:'補完平方再開根號的結果。',
    template:'\\sqrt{a^2}=@1', blanks:['|a|'],
    bank:['|a|', 'a', '-a', 'a^2'], hint1:'根號的結果不能是負的。'},
  recog:{type:'choice', prompt:'√((−6)²) 等於多少？',
    options:[{math:'6'}, {math:'-6'}, {math:'36'}, {math:'\\pm 6'}],
    answer:0, hint1:'先算括號內的平方，再開根號。',
    why:'(−6)² = 36，√36 = 6。根號求的是非負的那個值，所以答案是 6 = |−6|。'},
  apply:{type:'numeric', prompt:'計算 √((−9)²) 的值。',
    given:'\\sqrt{(-9)^2}', answer:'9', unit:'', hint1:'√(a²) = |a|。',
    steps:['(−9)² = 81', '√81 = 9（也就是 |−9|）']},
  recogMore:[{type:'choice', prompt:'√(x²) 一定等於 x 嗎？',
    options:[{t:'不一定，x 是負數時等於 −x'}, {t:'一定等於 x'},
             {t:'一定等於 −x'}, {t:'只有 x 是整數才成立'}],
    answer:0, hint1:'根號的結果不能是負的。',
    why:'√(x²) = |x|。x ≥ 0 時等於 x，x < 0 時等於 −x（例如 x = −4 時結果是 4）。'}],
  applyMore:[
    {type:'numeric', prompt:'計算 √(12²) 的值。',
     given:'\\sqrt{12^2}', answer:'12', unit:'', hint1:'√(a²) = |a|，12 本來就是正的。',
     steps:['√(12²) = |12| = 12']},
    {type:'numeric', prompt:'計算 √((−5)²) + √(4²) 的值。',
     given:'\\sqrt{(-5)^2}+\\sqrt{4^2}', answer:'9', unit:'',
     hint1:'兩項各自取絕對值。',
     steps:['√((−5)²) = |−5| = 5', '√(4²) = 4', '5 + 4 = 9']}],
  worked:{title:'計算 √((−9)²)', given:'\\sqrt{(-9)^2}',
    steps:[{label:'用公式', math:'\\sqrt{(-9)^2}=|-9|'}, {label:'取絕對值', math:'=9'}],
    answer:'9'},
  explain:'√(a²) 與 (√a)² 不同：前者 a 可以是負數，結果取絕對值；後者要求 a ≥ 0，結果就是 a。',
  source:'自己要記'}),

card({id:'C3', grade:8, category:'num', title:'根號相乘',
  formula:'\\sqrt{a}\\sqrt{b}=\\sqrt{ab},\\ a,b\\geq 0',
  variables:[{sym:'a, b', desc:'被開方數，都要大於等於 0'}],
  usageConditions:'兩個根號相乘可以合併；反過來也可以把大根號拆成兩個以便化簡。',
  triggerWords:['根號相乘', '化簡根式', '最簡根式'],
  commonMistakes:['對相加也套用（√a + √b ≠ √(a+b)）', '忘記檢查 a、b 非負'],
  recall:{type:'blank', prompt:'補完根號相乘的規則。',
    template:'\\sqrt{a}\\sqrt{b}=@1', blanks:['\\sqrt{ab}'],
    bank:['\\sqrt{ab}', '\\sqrt{a+b}', 'ab', '\\sqrt{a}+\\sqrt{b}'],
    hint1:'兩個被開方數相乘，放進同一個根號。'},
  recog:{type:'choice', prompt:'化簡 √12 最好的第一步是？',
    options:[{t:'拆成 √4 × √3'}, {t:'拆成 √6 × √6'}, {t:'寫成 √10 + √2'}, {t:'直接寫 3√4'}],
    answer:0, hint1:'拆出一個「完全平方數」才化得掉。',
    why:'12 = 4 × 3，4 是完全平方數，所以 √12 = √4 · √3 = 2√3。'},
  apply:{type:'choice', prompt:'√8 × √2 化簡後等於多少？',
    given:'\\sqrt{8}\\times\\sqrt{2}', options:[{math:'4'}, {math:'\\sqrt{10}'},
      {math:'2\\sqrt{2}'}, {math:'16'}],
    answer:0, unit:'', hint1:'先合併成一個根號。',
    steps:['√8 × √2 = √16', '√16 = 4']},
  recogMore:[{type:'choice', prompt:'√2 + √3 等於 √5 嗎？',
    options:[{t:'不等於，根號相加不能合併'}, {t:'等於，和相乘一樣'},
             {t:'等於，但要再乘 2'}, {t:'只有被開方數是平方數時才等於'}],
    answer:0, hint1:'合併的規則只適用於相乘與相除。',
    why:'只有相乘（或相除）才能合併根號。√2 ≈ 1.41、√3 ≈ 1.73，相加約 3.14，但 √5 ≈ 2.24。'}],
  applyMore:[
    {type:'numeric', prompt:'√3 × √12 等於多少？',
     given:'\\sqrt{3}\\times\\sqrt{12}', answer:'6', unit:'',
     hint1:'先合併成 √36。',
     steps:['√3 × √12 = √36', '= 6']},
    {type:'choice', prompt:'把 √50 化成最簡根式。',
     given:'\\sqrt{50}', options:[{math:'5\\sqrt{2}'}, {math:'2\\sqrt{5}'},
       {math:'10\\sqrt{5}'}, {math:'25\\sqrt{2}'}],
     answer:0, unit:'', hint1:'50 = 25 × 2，25 是完全平方數。',
     steps:['√50 = √25 × √2', '= 5√2']}],
  worked:{title:'化簡 √8 × √2', given:'\\sqrt{8}\\times\\sqrt{2}',
    steps:[{label:'合併根號', math:'\\sqrt{8\\times 2}'},
           {label:'計算', math:'=\\sqrt{16}'}, {label:'開方', math:'=4'}],
    answer:'4'},
  explain:'只有「相乘」可以合併根號，相加不行。化簡時要把被開方數拆出最大的完全平方因數。',
  source:'自己要記'}),

card({id:'C4', grade:8, category:'num', title:'根號相除',
  formula:'\\frac{\\sqrt{a}}{\\sqrt{b}}=\\sqrt{\\frac{a}{b}},\\ a\\geq 0,\\ b>0',
  variables:[{sym:'a', desc:'分子的被開方數，可為 0'}, {sym:'b', desc:'分母的被開方數，必須大於 0'}],
  usageConditions:'兩個根號相除可以合併成一個根號；也用於分母有理化前的整理。',
  triggerWords:['根號相除', '分母有理化', '化簡'],
  commonMistakes:['分母為 0 仍套用', '對相減也套用', '化簡後忘記分母有理化'],
  recall:{type:'blank', prompt:'補完根號相除的規則。',
    template:'\\frac{\\sqrt{a}}{\\sqrt{b}}=@1', blanks:['\\sqrt{\\frac{a}{b}}'],
    bank:['\\sqrt{\\frac{a}{b}}', '\\frac{a}{b}', '\\sqrt{a-b}', '\\frac{\\sqrt{a}}{b}'],
    hint1:'把兩個被開方數放在同一個根號裡相除。'},
  recog:{type:'choice', prompt:'√18 ÷ √2 最快的算法是？',
    options:[{t:'先合併成 √9'}, {t:'先各自化簡成 3√2 ÷ √2'},
             {t:'寫成 √16'}, {t:'兩邊都平方'}],
    answer:0, hint1:'合併成一個根號後看看能不能整除。',
    why:'√18 ÷ √2 = √(18÷2) = √9 = 3。第二個做法也能得到 3，但多了一步。'},
  apply:{type:'numeric', prompt:'√50 ÷ √2 等於多少？',
    given:'\\frac{\\sqrt{50}}{\\sqrt{2}}', answer:'5', unit:'', hint1:'50 ÷ 2 = 25。',
    steps:['√50 ÷ √2 = √(50 ÷ 2)', '= √25 = 5']},
  recogMore:[{type:'choice', prompt:'分母有理化的目的是什麼？',
    options:[{t:'讓分母不再出現根號'}, {t:'讓分子變成整數'},
             {t:'讓分數變小'}, {t:'讓根號消失'}],
    answer:0, hint1:'有理化處理的是分母。',
    why:'分母有理化就是把分母的根號消掉（分子分母同乘同一個根式），分子仍然可以留著根號。'}],
  applyMore:[
    {type:'numeric', prompt:'√72 ÷ √8 等於多少？',
     given:'\\frac{\\sqrt{72}}{\\sqrt{8}}', answer:'3', unit:'',
     hint1:'72 ÷ 8 = 9。',
     steps:['√72 ÷ √8 = √(72 ÷ 8)', '= √9 = 3']},
    {type:'choice', prompt:'化簡 √(9/16)，結果是？',
     given:'\\sqrt{\\frac{9}{16}}', options:[{math:'\\frac{3}{4}'}, {math:'\\frac{9}{16}'},
       {math:'\\frac{4}{3}'}, {math:'\\frac{3}{16}'}],
     answer:0, unit:'', hint1:'分子分母各自開根號。',
     steps:['√(9/16) = √9 ÷ √16', '= 3 ÷ 4 = 3/4']}],
  worked:{title:'計算 √50 ÷ √2', given:'\\frac{\\sqrt{50}}{\\sqrt{2}}',
    steps:[{label:'合併根號', math:'\\sqrt{\\frac{50}{2}}'},
           {label:'約分', math:'=\\sqrt{25}'}, {label:'開方', math:'=5'}],
    answer:'5'},
  explain:'分母的 b 必須大於 0（不能是 0，也不能讓根號內為負）。若最後分母還留著根號，要再做分母有理化。',
  source:'自己要記'})

];
