/* ══════════════════════════════════════════════════════════════════════
   知識點資料：數與代數、根式（題本未附，必須自己記）
   ══════════════════════════════════════════════════════════════════════ */
var NUM_CARDS = [

card({id:'B1', grade:7, category:'num', title:'負號分配（括號內相加）',
  formula:'-(a+b)=-a-b',
  variables:[{sym:'a', desc:'括號內第一項'}, {sym:'b', desc:'括號內第二項'}],
  usageConditions:'括號前面是負號（或減去一整個括號）時，去括號要把每一項都變號。',
  triggerWords:['去括號', '減去', '相反數', '化簡'],
  commonMistakes:['只變第一項的號', '把 −(a+b) 寫成 −a+b'],
  recall:{type:'blank', prompt:'去括號後應該是？',
    template:'-(a+b)=@1@2', blanks:['-a', '-b'],
    bank:['-a', '-b', '+a', '+b'], hint1:'括號內每一項都要變號，不能只變第一項。'},
  recog:{type:'choice', prompt:'化簡 5 − (x + 2) 的第一步應該是？',
    options:[{math:'5-x-2'}, {math:'5-x+2'}, {math:'5+x+2'}, {math:'5+x-2'}],
    answer:0, hint1:'減去一整個括號＝括號內每一項都變號。',
    why:'負號要分配給括號內兩項，x 變 −x，＋2 變 −2，得 5 − x − 2 = 3 − x。'},
  apply:{type:'numeric', prompt:'化簡 10 − (3 + 4) 的值是多少？',
    given:'10-(3+4)', answer:'3', unit:'', hint1:'先把負號分配進去：10 − 3 − 4。',
    steps:['10 − (3 + 4) = 10 − 3 − 4', '= 3']},
  worked:{title:'化簡 5 − (x + 2)', given:'5-(x+2)',
    steps:[{label:'分配負號', math:'5-x-2'}, {label:'合併常數', math:'=3-x'}],
    answer:'3-x'},
  explain:'括號前的負號等於乘以 −1，所以括號內每一項都要變號。',
  source:'自己要記'}),

card({id:'B2', grade:7, category:'num', title:'負號分配（括號內相減）',
  formula:'-(a-b)=-a+b',
  variables:[{sym:'a', desc:'被減數'}, {sym:'b', desc:'減數'}],
  usageConditions:'括號前是負號、括號內是減法時，減號會被變成加號。',
  triggerWords:['去括號', '相減', '化簡', '兩式相減'],
  commonMistakes:['第二項忘記變成 +b', '整串照抄沒變號'],
  recall:{type:'blank', prompt:'去括號後應該是？',
    template:'-(a-b)=@1@2', blanks:['-a', '+b'],
    bank:['-a', '+b', '-b', '+a'], hint1:'負負得正，原本的 −b 會變成 +b。'},
  recog:{type:'choice', prompt:'(2x + 5) − (x − 3) 去括號後是？',
    options:[{math:'2x+5-x+3'}, {math:'2x+5-x-3'}, {math:'2x+5+x-3'}, {math:'2x-5-x+3'}],
    answer:0, hint1:'第二個括號前面是減號，裡面兩項都要變號。',
    why:'−(x − 3) = −x + 3，所以整式是 2x + 5 − x + 3 = x + 8。'},
  apply:{type:'numeric', prompt:'計算 20 − (8 − 5) 的值。',
    given:'20-(8-5)', answer:'17', unit:'', hint1:'20 − 8 + 5。',
    steps:['20 − (8 − 5) = 20 − 8 + 5', '= 17']},
  worked:{title:'化簡 (2x+5) − (x−3)', given:'(2x+5)-(x-3)',
    steps:[{label:'分配負號', math:'2x+5-x+3'}, {label:'合併同類項', math:'=x+8'}],
    answer:'x+8'},
  explain:'負號分配時，括號內的加變減、減變加。最容易錯的就是第二項。',
  source:'自己要記'}),

card({id:'B3', grade:7, category:'num', title:'數線上兩點的距離',
  formula:'\\text{距離}=|a-b|',
  variables:[{sym:'a', desc:'第一點的坐標'}, {sym:'b', desc:'第二點的坐標'}],
  usageConditions:'數線上兩點求距離時使用，距離一定是非負數。',
  triggerWords:['數線', '相距', '距離', '中點'],
  commonMistakes:['算出負數就當答案', '兩點都是負數時忘記加括號'],
  recall:{type:'blank', prompt:'數線上 a、b 兩點的距離是？',
    template:'\\text{距離}=@1', blanks:['|a-b|'],
    bank:['|a-b|', 'a-b', 'a+b', '|a+b|'], hint1:'距離不能是負的，所以要加絕對值。'},
  recog:{type:'choice', prompt:'數線上 −3 與 5 相距多少？',
    options:[{math:'8'}, {math:'2'}, {math:'-8'}, {math:'15'}],
    answer:0, hint1:'|−3 − 5| 要先算括號內再取絕對值。',
    why:'|−3 − 5| = |−8| = 8，從 −3 走到 5 要經過 8 個單位。'},
  apply:{type:'numeric', prompt:'數線上 −7 與 4 的距離是多少？',
    given:'a=-7,\\ b=4', answer:'11', unit:'', hint1:'|−7 − 4| = |−11|。',
    steps:['|−7 − 4| = |−11|', '= 11']},
  worked:{title:'求 −7 與 4 的距離', given:'a=-7,\\ b=4',
    steps:[{label:'代入', math:'|-7-4|'}, {label:'先算括號內', math:'=|-11|'},
           {label:'取絕對值', math:'=11'}],
    answer:'11'},
  explain:'a − b 可能是負的，但距離不能是負的，所以外面要加絕對值。|a − b| 與 |b − a| 相等。',
  source:'自己要記'}),

card({id:'B4', grade:7, category:'num', title:'零次方',
  formula:'a^0=1,\\ a\\neq 0',
  variables:[{sym:'a', desc:'底數，不可以是 0'}],
  usageConditions:'任何非零數的 0 次方都等於 1，常出現在指數律化簡的最後一步。',
  triggerWords:['0 次方', '化簡', '指數律'],
  commonMistakes:['寫成 0', '忘記 a ≠ 0 的限制', '把 0⁰ 當成 1'],
  recall:{type:'blank', prompt:'補完零次方的規則。',
    template:'a^0=@1', blanks:['1'], bank:['1', '0', 'a', '-1'],
    hint1:'只要底數不是 0，結果固定是同一個數。'},
  recog:{type:'choice', prompt:'下列哪一個式子「不成立」？',
    options:[{math:'0^0=1'}, {math:'5^0=1'}, {math:'(-3)^0=1'}, {math:'(\\frac{2}{7})^0=1'}],
    answer:0, hint1:'公式有一個但書。',
    why:'零次方規則要求底數不為 0，所以 0⁰ 沒有定義；其餘底數都不是 0，結果都是 1。'},
  apply:{type:'numeric', prompt:'計算 (−8)⁰ + 3⁰ 的值。',
    given:'(-8)^0+3^0', answer:'2', unit:'', hint1:'兩個底數都不是 0。',
    steps:['(−8)⁰ = 1，3⁰ = 1', '1 + 1 = 2']},
  worked:{title:'計算 (−8)⁰ + 3⁰', given:'(-8)^0+3^0',
    steps:[{label:'各自化簡', math:'(-8)^0=1,\\ 3^0=1'}, {label:'相加', math:'1+1=2'}],
    answer:'2'},
  explain:'因為 aᵐ ÷ aᵐ = aᵐ⁻ᵐ = a⁰，而任何非零數除以自己等於 1，所以 a⁰ = 1。',
  source:'自己要記'}),

card({id:'B5', grade:7, category:'num', title:'同底數相乘',
  formula:'a^ma^n=a^{m+n}',
  variables:[{sym:'a', desc:'相同的底數'}, {sym:'m', desc:'第一個指數'}, {sym:'n', desc:'第二個指數'}],
  usageConditions:'底數相同的兩個乘冪相乘時，指數相加。',
  triggerWords:['同底', '相乘', '指數律', '化簡'],
  commonMistakes:['把指數相乘', '底數也一起乘', '底數不同也硬加'],
  recall:{type:'blank', prompt:'補完同底數相乘的指數律。',
    template:'a^ma^n=a^{@1}', blanks:['m+n'],
    bank:['m+n', 'mn', 'm-n', 'm^n'], hint1:'相乘 ⇒ 指數相加。'},
  recog:{type:'choice', prompt:'下列哪一個可以直接用「同底數相乘」化簡？',
    options:[{math:'2^3\\times 2^5'}, {math:'2^3\\times 3^5'}, {math:'2^3+2^5'}, {math:'2^3\\div 3^5'}],
    answer:0, hint1:'底數必須完全相同，而且是相乘。',
    why:'只有 2³ × 2⁵ 底數相同又是相乘，等於 2⁸；底數不同或是相加都不能用。'},
  apply:{type:'numeric', prompt:'2³ × 2⁵ 化簡成 2 的幾次方？（只填指數）',
    given:'2^3\\times 2^5', answer:'8', unit:'', hint1:'3 + 5。',
    steps:['2³ × 2⁵ = 2³⁺⁵', '= 2⁸，指數是 8']},
  worked:{title:'化簡 2³ × 2⁵', given:'2^3\\times 2^5',
    steps:[{label:'底數相同', text:'底數都是 2，可以用指數律'},
           {label:'指數相加', math:'2^{3+5}=2^8'}, {label:'展開', math:'=256'}],
    answer:'2^8=256'},
  explain:'aᵐ 是 m 個 a 相乘，aⁿ 是 n 個 a 相乘，合起來就是 (m + n) 個 a 相乘。',
  source:'自己要記'}),

card({id:'B6', grade:7, category:'num', title:'同底數相除',
  formula:'a^m\\div a^n=a^{m-n},\\ a\\neq 0,\\ m\\geq n',
  variables:[{sym:'a', desc:'相同的底數，不為 0'}, {sym:'m', desc:'被除數的指數'}, {sym:'n', desc:'除數的指數'}],
  usageConditions:'底數相同的乘冪相除時，指數相減（本課程限 m ≥ n）。',
  triggerWords:['同底', '相除', '約分', '化簡'],
  commonMistakes:['指數相除', '前後順序顛倒變成 n − m', '忘記 a ≠ 0'],
  recall:{type:'blank', prompt:'補完同底數相除的指數律。',
    template:'a^m\\div a^n=a^{@1}', blanks:['m-n'],
    bank:['m-n', 'n-m', 'm+n', 'm\\div n'], hint1:'相除 ⇒ 指數相減，被除數的指數放前面。'},
  recog:{type:'choice', prompt:'化簡 5⁷ ÷ 5² 要用哪一條指數律？',
    options:[{t:'同底數相除，指數相減'}, {t:'同底數相乘，指數相加'},
             {t:'乘冪的乘冪，指數相乘'}, {t:'零次方'}],
    answer:0, hint1:'看運算符號是乘還是除。',
    why:'底數同為 5 且是相除，所以指數相減得 5⁵。'},
  apply:{type:'numeric', prompt:'5⁷ ÷ 5² 化簡成 5 的幾次方？（只填指數）',
    given:'5^7\\div 5^2', answer:'5', unit:'', hint1:'7 − 2。',
    steps:['5⁷ ÷ 5² = 5⁷⁻²', '= 5⁵，指數是 5']},
  worked:{title:'化簡 5⁷ ÷ 5²', given:'5^7\\div 5^2',
    steps:[{label:'確認同底', text:'底數都是 5'},
           {label:'指數相減', math:'5^{7-2}=5^5'}],
    answer:'5^5'},
  explain:'除法是約分：分子有 7 個 5、分母有 2 個 5，約掉 2 個後剩下 5 個。',
  source:'自己要記'}),

card({id:'B7', grade:7, category:'num', title:'乘冪的乘冪',
  formula:'(a^m)^n=a^{mn}',
  variables:[{sym:'a', desc:'底數'}, {sym:'m', desc:'裡面的指數'}, {sym:'n', desc:'外面的指數'}],
  usageConditions:'整個乘冪再被平方、立方時使用，兩個指數相乘。',
  triggerWords:['再平方', '括號外還有指數', '化簡'],
  commonMistakes:['指數相加', '與同底數相乘搞混', '底數也乘上去'],
  recall:{type:'blank', prompt:'補完乘冪的乘冪。',
    template:'(a^m)^n=a^{@1}', blanks:['mn'],
    bank:['mn', 'm+n', 'm-n', 'm^n'], hint1:'括號外的指數是「重複幾次」，所以指數相乘。'},
  recog:{type:'choice', prompt:'(3²)⁴ 與下列哪一個相等？',
    options:[{math:'3^8'}, {math:'3^6'}, {math:'3^{16}'}, {math:'9^4\\times 3'}],
    answer:0, hint1:'2 × 4。',
    why:'(3²)⁴ 代表 3² 連乘 4 次，共有 8 個 3，所以是 3⁸。'},
  apply:{type:'numeric', prompt:'(2³)⁴ 化簡成 2 的幾次方？（只填指數）',
    given:'(2^3)^4', answer:'12', unit:'', hint1:'3 × 4。',
    steps:['(2³)⁴ = 2³ˣ⁴', '= 2¹², 指數是 12']},
  worked:{title:'化簡 (2³)⁴', given:'(2^3)^4',
    steps:[{label:'指數相乘', math:'2^{3\\times 4}'}, {label:'得結果', math:'=2^{12}'}],
    answer:'2^{12}'},
  explain:'(aᵐ)ⁿ 是把 aᵐ 重複乘 n 次，總共有 m × n 個 a。與 aᵐaⁿ（指數相加）要分清楚。',
  source:'自己要記'}),

card({id:'B8', grade:7, category:'num', title:'積的乘冪',
  formula:'(ab)^n=a^nb^n',
  variables:[{sym:'a', desc:'第一個因數'}, {sym:'b', desc:'第二個因數'}, {sym:'n', desc:'指數'}],
  usageConditions:'括號內是「相乘」再整體次方時，每個因數都要各自次方。',
  triggerWords:['括號整體次方', '化簡', '科學記號相乘'],
  commonMistakes:['只有一個因數次方', '把 (a+b)ⁿ 也拆開（不成立）'],
  recall:{type:'blank', prompt:'補完積的乘冪。',
    template:'(ab)^n=@1@2', blanks:['a^n', 'b^n'],
    bank:['a^n', 'b^n', 'ab^n', '(ab)^n'], hint1:'括號內每一個「相乘」的因數都要各自次方。'},
  recog:{type:'choice', prompt:'下列哪一個式子成立？',
    options:[{math:'(2x)^3=8x^3'}, {math:'(2+x)^3=8+x^3'},
             {math:'(2x)^3=2x^3'}, {math:'(2x)^3=6x^3'}],
    answer:0, hint1:'只有相乘才能各自次方，相加不行。',
    why:'(2x)³ = 2³ · x³ = 8x³。括號內是相加時不能這樣拆。'},
  apply:{type:'numeric', prompt:'(3y)² 展開後，y² 前面的係數是多少？',
    given:'(3y)^2', answer:'9', unit:'', hint1:'3 也要平方。',
    steps:['(3y)² = 3² × y²', '= 9y²，係數是 9']},
  worked:{title:'展開 (3y)²', given:'(3y)^2',
    steps:[{label:'每個因數各自平方', math:'3^2\\times y^2'}, {label:'計算', math:'=9y^2'}],
    answer:'9y^2'},
  explain:'括號裡是乘法才能各自次方。(a + b)ⁿ 不能拆成 aⁿ + bⁿ，那要用乘法公式。',
  source:'自己要記'}),

card({id:'B9', grade:7, category:'num', title:'科學記號',
  formula:'c\\times 10^n,\\ 1\\leq c<10',
  variables:[{sym:'c', desc:'有效數字，必須大於等於 1 且小於 10'}, {sym:'n', desc:'10 的次方，整數'}],
  usageConditions:'表示很大或很小的數（人口、光速、細胞大小）時使用。',
  triggerWords:['科學記號', '約為', '幾乘以 10 的幾次方', '單位換算'],
  commonMistakes:['c 寫成 10 以上或小於 1', '小數點移動方向與指數正負弄反', '忘記 c 可以是小數'],
  recall:{type:'blank', prompt:'科學記號中，前面的數 c 必須符合什麼條件？',
    template:'c\\times 10^n,\\ @1', blanks:['1\\leq c<10'],
    bank:['1\\leq c<10', '0<c<1', '1<c\\leq 10', '0\\leq c<10'],
    hint1:'只能有一位整數，而且不能是 0。'},
  recog:{type:'choice', prompt:'下列哪一個「是」正確的科學記號？',
    options:[{math:'3.6\\times 10^5'}, {math:'36\\times 10^4'},
             {math:'0.36\\times 10^6'}, {math:'3.6\\times 5^{10}'}],
    answer:0, hint1:'檢查前面的數是不是介於 1 到 10 之間。',
    why:'3.6 符合 1 ≤ c < 10；36 太大、0.36 太小、底數必須是 10。'},
  apply:{type:'choice', prompt:'把 52000 寫成科學記號。',
    given:'52000', options:[{math:'5.2\\times 10^4'}, {math:'52\\times 10^3'},
      {math:'5.2\\times 10^3'}, {math:'0.52\\times 10^5'}],
    answer:0, unit:'', hint1:'小數點從最右邊往左移，移幾位指數就是幾。',
    steps:['52000 的小數點往左移 4 位變成 5.2', '所以是 5.2 × 10⁴']},
  worked:{title:'把 52000 寫成科學記號', given:'52000',
    steps:[{label:'調整成 1 ~ 10', text:'52000 → 5.2，小數點往左移了 4 位'},
           {label:'補上 10 的次方', math:'5.2\\times 10^4'}],
    answer:'5.2\\times 10^4'},
  explain:'c 只能有一位整數位（1 到 9）。小數點往左移 n 位，指數就是 +n；往右移 n 位，指數是 −n。',
  source:'自己要記'}),

card({id:'B10', grade:7, category:'num', title:'比例式的內外項相乘',
  formula:'a:b=c:d\\Rightarrow ad=bc',
  variables:[{sym:'a, d', desc:'外項'}, {sym:'b, c', desc:'內項'}],
  usageConditions:'題目給兩組比相等，要求未知數時使用。',
  triggerWords:['比', '比例', '相當於', '成正比', '對應'],
  commonMistakes:['對錯內外項', '把 a:b 的順序寫反', '單位不同就直接列比'],
  recall:{type:'blank', prompt:'比例式可以怎麼變成等式？',
    template:'a:b=c:d\\Rightarrow @1=@2', blanks:['ad', 'bc'],
    bank:['ad', 'bc', 'ac', 'bd'], hint1:'外項相乘等於內項相乘。'},
  recog:{type:'choice', prompt:'「3 枝筆 45 元，7 枝筆多少元？」最適合列成？',
    options:[{math:'3:45=7:x'}, {math:'3:7=x:45'}, {math:'3:x=45:7'}, {math:'45:3=7:x'}],
    answer:0, hint1:'同一種量要放在比的同一邊，順序要一致。',
    why:'「枝數 : 價錢」的順序前後必須一致，寫成 3:45 = 7:x，交叉相乘得 3x = 315，x = 105。其餘選項把兩種量混在同一邊或順序顛倒，會解出錯誤答案。'},
  apply:{type:'numeric', prompt:'3 枝筆 45 元，7 枝筆要多少元？',
    given:'3:45=7:x', answer:'105', unit:'元', hint1:'交叉相乘：3x = 45 × 7。',
    steps:['3 : 45 = 7 : x', '3x = 45 × 7 = 315', 'x = 105（元）']},
  worked:{title:'3 枝 45 元，求 7 枝的價錢', given:'3:45=7:x',
    steps:[{label:'列比例式', math:'3:45=7:x'},
           {label:'內外項相乘', math:'3x=45\\times 7'},
           {label:'計算', math:'3x=315'},
           {label:'求解', math:'x=105'}],
    answer:'105 \\text{ 元}'},
  explain:'a : b = c : d 中，a 和 d 是外項、b 和 c 是內項。列比例時同一種量要放同一個位置。',
  source:'自己要記'}),

card({id:'B11', grade:7, category:'num', title:'正比',
  formula:'y=kx',
  variables:[{sym:'k', desc:'比例常數，等於 y ÷ x'}, {sym:'x, y', desc:'兩個成正比的量'}],
  usageConditions:'一個量變成幾倍，另一個量也變成同樣幾倍時使用；圖形是過原點的直線。',
  triggerWords:['成正比', '愈多愈多', '倍數關係', '單價固定'],
  commonMistakes:['把正比寫成 y = x + k', '與反比混用', 'k 求成 x ÷ y'],
  recall:{type:'blank', prompt:'y 與 x 成正比時，關係式是？',
    template:'y=@1', blanks:['kx'], bank:['kx', '\\frac{k}{x}', 'k+x', 'kx^2'],
    hint1:'兩量的「商」固定，圖形是通過原點的直線。'},
  recog:{type:'choice', prompt:'下列哪一組成正比？',
    options:[{t:'買糖果的總價與數量（單價固定）'}, {t:'固定路程下的速率與時間'},
             {t:'長方形面積固定時的長與寬'}, {t:'剩餘金額與已花金額'}],
    answer:0, hint1:'看看兩個量的「商」是不是固定。',
    why:'單價固定時，總價 ÷ 數量 = 單價（常數），符合 y = kx；速率與時間、長與寬是乘積固定，屬於反比。'},
  apply:{type:'numeric', prompt:'y 與 x 成正比，x = 4 時 y = 12。當 x = 7 時 y 是多少？',
    given:'x=4,\\ y=12', answer:'21', unit:'', hint1:'先求 k = y ÷ x。',
    steps:['k = 12 ÷ 4 = 3', 'y = 3x，代入 x = 7', 'y = 3 × 7 = 21']},
  worked:{title:'求正比關係中的 y', given:'x=4 \\text{ 時 } y=12',
    steps:[{label:'求比例常數', math:'k=\\frac{12}{4}=3'},
           {label:'寫關係式', math:'y=3x'},
           {label:'代入', math:'y=3\\times 7=21'}],
    answer:'21'},
  explain:'k 是比例常數，等於 y ÷ x，兩量的商固定。x 變 2 倍時 y 也變 2 倍。',
  source:'自己要記'}),

card({id:'B12', grade:7, category:'num', title:'反比',
  formula:'xy=k \\text{ 或 } y=\\frac{k}{x}',
  variables:[{sym:'k', desc:'比例常數，等於 x × y'}, {sym:'x, y', desc:'兩個成反比的量'}],
  usageConditions:'一個量變大、另一個量按比例變小，兩量乘積固定時使用。',
  triggerWords:['成反比', '愈多愈少', '幾個人做幾天', '固定總量分配'],
  commonMistakes:['寫成 y = kx', '用相加相減處理', '忘記 x ≠ 0'],
  recall:{type:'blank', prompt:'y 與 x 成反比時，乘積關係是？',
    template:'xy=@1', blanks:['k'], bank:['k', 'kx', '\\frac{k}{x}', 'x+y'],
    hint1:'兩量的「積」固定。'},
  recog:{type:'choice', prompt:'下列哪一組成反比？',
    options:[{t:'工作總量固定時，人數與所需天數'}, {t:'單價固定時，數量與總價'},
             {t:'正方形的邊長與周長'}, {t:'時間與已行走的距離（等速）'}],
    answer:0, hint1:'兩量相乘是不是固定？',
    why:'人數 × 天數 = 工作總量（固定），是反比；其餘三組都是商固定，屬於正比。'},
  apply:{type:'numeric', prompt:'y 與 x 成反比，x = 3 時 y = 8。當 x = 4 時 y 是多少？',
    given:'x=3,\\ y=8', answer:'6', unit:'', hint1:'先求 k = xy。',
    steps:['k = 3 × 8 = 24', 'y = 24 ÷ x，代入 x = 4', 'y = 24 ÷ 4 = 6']},
  worked:{title:'求反比關係中的 y', given:'x=3 \\text{ 時 } y=8',
    steps:[{label:'求比例常數', math:'k=3\\times 8=24'},
           {label:'寫關係式', math:'y=\\frac{24}{x}'},
           {label:'代入', math:'y=\\frac{24}{4}=6'}],
    answer:'6'},
  explain:'反比的固定量是「乘積」xy = k。正比固定的是商，反比固定的是積，這是最常混淆的地方。',
  source:'自己要記'}),

card({id:'B13', grade:7, category:'num', title:'百分率',
  formula:'\\text{百分率}=\\frac{\\text{部分}}{\\text{全部}}\\times 100\\%',
  variables:[{sym:'部分', desc:'被問到的那一部分數量'}, {sym:'全部', desc:'基準量（分母）'}],
  usageConditions:'求「佔幾 %」「及格率」「命中率」時使用，關鍵是找對基準量。',
  triggerWords:['百分之', '佔', '成功率', '及格率', '打折'],
  commonMistakes:['分子分母顛倒', '基準量找錯', '忘記乘 100%'],
  recall:{type:'blank', prompt:'補完百分率公式。',
    template:'\\text{百分率}=\\frac{@1}{@2}\\times 100\\%', blanks:['\\text{部分}', '\\text{全部}'],
    bank:['\\text{部分}', '\\text{全部}', '\\text{差額}', '\\text{總和}'],
    hint1:'分母是「基準量」，也就是「佔誰的」那個誰。'},
  recog:{type:'choice', prompt:'「25 人中有 20 人及格，及格率多少？」分母應該放哪個數？',
    options:[{t:'25（總人數）'}, {t:'20（及格人數）'}, {t:'5（不及格人數）'}, {t:'100'}],
    answer:0, hint1:'「佔全班的百分之幾」＝分母是全班。',
    why:'基準量是全班 25 人，所以 20 ÷ 25 × 100% = 80%。'},
  apply:{type:'numeric', prompt:'25 人中有 20 人及格，及格率是百分之多少？（只填數字）',
    given:'\\frac{20}{25}', answer:'80', unit:'%', hint1:'20 ÷ 25 = 0.8。',
    steps:['20 ÷ 25 = 0.8', '0.8 × 100% = 80%']},
  worked:{title:'求及格率', given:'20 \\text{ 人及格，共 } 25 \\text{ 人}',
    steps:[{label:'找基準量', text:'全班 25 人是分母'},
           {label:'代入', math:'\\frac{20}{25}\\times 100\\%'},
           {label:'計算', math:'=0.8\\times 100\\%=80\\%'}],
    answer:'80\\%'},
  explain:'百分率的分母是「基準量」。題目說「佔 A 的百分之幾」，A 就是分母。',
  source:'自己要記'}),

card({id:'B14', grade:7, category:'num', title:'增加率',
  formula:'\\text{新值}=\\text{原值}\\times(1+r)',
  variables:[{sym:'r', desc:'增加率，寫成小數'}, {sym:'原值', desc:'變動前的數量'}],
  usageConditions:'漲價、加薪、人口成長、加成時使用；括號內是 1 加上增加率。',
  triggerWords:['上漲', '增加', '成長', '加成', '調漲'],
  commonMistakes:['只乘 r 忘了 1', '把 20% 代成 20', '連續兩次成長用相加'],
  recall:{type:'blank', prompt:'增加 r 之後的新值是？',
    template:'\\text{新值}=\\text{原值}\\times@1', blanks:['(1+r)'],
    bank:['(1+r)', '(1-r)', 'r', '(1+r)^2'], hint1:'原本的 1 倍要留著，再加上增加的部分。'},
  recog:{type:'choice', prompt:'定價 500 元的商品調漲 20%，算式應該是？',
    options:[{math:'500\\times(1+0.2)'}, {math:'500\\times 0.2'},
             {math:'500\\times(1-0.2)'}, {math:'500+20'}],
    answer:0, hint1:'漲價後仍然包含原來的價錢。',
    why:'新價 = 原價 × (1 + 0.2) = 500 × 1.2 = 600 元；500 × 0.2 只是「漲的部分」。'},
  apply:{type:'numeric', prompt:'定價 500 元的商品調漲 20% 後是多少元？',
    given:'500\\times(1+0.2)', answer:'600', unit:'元', hint1:'500 × 1.2。',
    steps:['500 × (1 + 0.2) = 500 × 1.2', '= 600（元）']},
  worked:{title:'500 元調漲 20%', given:'\\text{原值}=500,\\ r=0.2',
    steps:[{label:'把 20% 化成小數', math:'r=0.2'},
           {label:'代入', math:'500\\times(1+0.2)'},
           {label:'計算', math:'=500\\times 1.2=600'}],
    answer:'600 \\text{ 元}'},
  explain:'(1 + r) 中的 1 代表原本的全部，r 代表多出來的部分。百分率一定要先化成小數。',
  source:'自己要記'}),

card({id:'B15', grade:7, category:'num', title:'減少率與打折',
  formula:'\\text{新值}=\\text{原值}\\times(1-r)',
  variables:[{sym:'r', desc:'減少率，寫成小數'}, {sym:'原值', desc:'變動前的數量'}],
  usageConditions:'降價、打折、折舊、減量時使用。台灣的「打八折」是乘 0.8。',
  triggerWords:['打折', '下降', '減少', '折扣', '降價'],
  commonMistakes:['打八折算成 1 − 0.8 = 0.2', '減 20% 與打 2 折混淆', '連續打折用相加'],
  recall:{type:'blank', prompt:'減少 r 之後的新值是？',
    template:'\\text{新值}=\\text{原值}\\times@1', blanks:['(1-r)'],
    bank:['(1-r)', '(1+r)', '-r', '(1-r)^2'], hint1:'剩下的比例＝1 減掉減少的比例。'},
  recog:{type:'choice', prompt:'原價 800 元「打八折」，應該乘以多少？',
    options:[{math:'0.8'}, {math:'0.2'}, {math:'1.8'}, {math:'8'}],
    answer:0, hint1:'打八折＝付原價的十分之八。',
    why:'打八折就是付原價的 80%，所以乘 0.8 得 640 元。若題目說「減少 20%」，同樣是乘 (1 − 0.2) = 0.8。'},
  apply:{type:'numeric', prompt:'原價 800 元打八折後是多少元？',
    given:'800\\times 0.8', answer:'640', unit:'元', hint1:'八折＝乘 0.8。',
    steps:['800 × 0.8 = 640（元）']},
  worked:{title:'800 元打八折', given:'\\text{原值}=800',
    steps:[{label:'折數換成小數', text:'打八折＝付 80%＝乘 0.8'},
           {label:'代入', math:'800\\times(1-0.2)=800\\times 0.8'},
           {label:'計算', math:'=640'}],
    answer:'640 \\text{ 元}'},
  explain:'「打 n 折」是乘 n/10；「減少 r」是乘 (1 − r)。八折與減少 20% 都是乘 0.8。',
  source:'自己要記'}),

card({id:'B16', grade:7, category:'num', title:'路程公式',
  formula:'\\text{路程}=\\text{速率}\\times\\text{時間}',
  variables:[{sym:'路程', desc:'走過的距離'}, {sym:'速率', desc:'每單位時間走的距離'}, {sym:'時間', desc:'花費的時間'}],
  usageConditions:'等速運動、相遇問題、追及問題都以此為基礎。',
  triggerWords:['每小時', '公里/時', '相遇', '追上', '幾分鐘後'],
  commonMistakes:['單位不一致（分與小時混用）', '相遇問題忘記兩人速率相加', '把時間當路程'],
  recall:{type:'blank', prompt:'補完路程公式。',
    template:'\\text{路程}=@1\\times@2', blanks:['\\text{速率}', '\\text{時間}'],
    bank:['\\text{速率}', '\\text{時間}', '\\text{路程}', '\\text{平均}'],
    hint1:'速率乘時間；求時間就把路程除以速率。'},
  recog:{type:'choice', prompt:'「時速 60 公里開 2.5 小時走多遠」該用哪個式子？',
    options:[{math:'60\\times 2.5'}, {math:'60\\div 2.5'}, {math:'2.5\\div 60'}, {math:'60+2.5'}],
    answer:0, hint1:'要求的是路程。',
    why:'路程 = 速率 × 時間 = 60 × 2.5 = 150 公里。'},
  apply:{type:'numeric', prompt:'時速 60 公里行駛 2.5 小時，共走幾公里？',
    given:'60\\times 2.5', answer:'150', unit:'公里', hint1:'單位已一致，直接相乘。',
    steps:['60 × 2.5 = 150（公里）']},
  worked:{title:'時速 60 公里走 2.5 小時', given:'\\text{速率}=60,\\ \\text{時間}=2.5',
    steps:[{label:'檢查單位', text:'速率是「公里／小時」，時間是小時，單位一致'},
           {label:'代入', math:'60\\times 2.5'}, {label:'計算', math:'=150'}],
    answer:'150 \\text{ 公里}'},
  explain:'三個量互相變形：時間 = 路程 ÷ 速率、速率 = 路程 ÷ 時間。代入前一定要先統一單位。',
  source:'自己要記'}),

card({id:'B17', grade:7, category:'num', title:'平均速率',
  formula:'\\text{平均速率}=\\frac{\\text{總路程}}{\\text{總時間}}',
  variables:[{sym:'總路程', desc:'全程走過的距離總和'}, {sym:'總時間', desc:'全程花費的時間總和'}],
  usageConditions:'去程回程速率不同、分段行駛時使用，不能把兩段速率直接平均。',
  triggerWords:['平均速率', '來回', '去程回程', '全程'],
  commonMistakes:['把兩段速率相加除以 2', '忘記把時間加總', '只算單程'],
  recall:{type:'blank', prompt:'補完平均速率公式。',
    template:'\\text{平均速率}=\\frac{@1}{@2}', blanks:['\\text{總路程}', '\\text{總時間}'],
    bank:['\\text{總路程}', '\\text{總時間}', '\\text{速率和}', '2'],
    hint1:'全部距離除以全部時間，不是兩個速率相加除以 2。'},
  recog:{type:'choice', prompt:'去程時速 60、回程時速 40，全程平均速率是？',
    options:[{t:'總路程 ÷ 總時間，不是 50'}, {t:'(60 + 40) ÷ 2 = 50'},
             {t:'60 × 40 ÷ 2'}, {t:'無法計算'}],
    answer:0, hint1:'兩段花的時間不一樣長。',
    why:'慢的那一段花較多時間，平均會被拉低。必須用總路程 ÷ 總時間。'},
  apply:{type:'numeric', prompt:'某人去程 120 公里花 2 小時，回程 120 公里花 3 小時，平均速率是每小時幾公里？',
    given:'120+120=240,\\ 2+3=5', answer:'48', unit:'公里/小時',
    hint1:'總路程 240，總時間 5。',
    steps:['總路程 = 120 + 120 = 240（公里）', '總時間 = 2 + 3 = 5（小時）', '240 ÷ 5 = 48（公里／小時）']},
  worked:{title:'去程 2 小時、回程 3 小時的平均速率', given:'\\text{各 } 120 \\text{ 公里}',
    steps:[{label:'算總路程', math:'120+120=240'},
           {label:'算總時間', math:'2+3=5'},
           {label:'相除', math:'\\frac{240}{5}=48'}],
    answer:'48 \\text{ 公里／小時}'},
  explain:'平均速率是「總量對總量」，不是兩個速率的算術平均。只有兩段時間相同時，答案才會剛好等於算術平均。',
  source:'自己要記'}),

card({id:'B18', grade:7, category:'num', title:'最大公因數與最小公倍數的關係',
  formula:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=ab',
  variables:[{sym:'gcd(a,b)', desc:'最大公因數'}, {sym:'lcm(a,b)', desc:'最小公倍數'},
             {sym:'a, b', desc:'兩個正整數'}],
  usageConditions:'已知兩數與其中一個公因數／公倍數，求另一個時使用。只適用於兩個數。',
  triggerWords:['最大公因數', '最小公倍數', '兩數乘積', '同時'],
  commonMistakes:['用在三個數上（不成立）', '把 gcd 與 lcm 位置弄反'],
  recall:{type:'blank', prompt:'補完最大公因數與最小公倍數的關係。',
    template:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=@1', blanks:['ab'],
    bank:['ab', 'a+b', 'a-b', '\\frac{a}{b}'], hint1:'兩者相乘剛好等於原本兩數的乘積。'},
  recog:{type:'choice', prompt:'已知兩數乘積 72、最大公因數 6，可以直接求出什麼？',
    options:[{t:'最小公倍數'}, {t:'兩數各是多少'}, {t:'兩數的和'}, {t:'兩數的差'}],
    answer:0, hint1:'公式裡有四個量，知道三個就能求第四個。',
    why:'lcm = 兩數乘積 ÷ gcd = 72 ÷ 6 = 12。但這個公式無法單獨決定兩個數各是多少。'},
  apply:{type:'numeric', prompt:'兩數乘積為 72、最大公因數為 6，最小公倍數是多少？',
    given:'ab=72,\\ \\gcd=6', answer:'12', unit:'', hint1:'lcm = ab ÷ gcd。',
    steps:['gcd × lcm = ab', '6 × lcm = 72', 'lcm = 12']},
  worked:{title:'由乘積與 gcd 求 lcm', given:'ab=72,\\ \\gcd(a,b)=6',
    steps:[{label:'寫公式', math:'\\gcd(a,b)\\times\\operatorname{lcm}(a,b)=ab'},
           {label:'代入', math:'6\\times\\operatorname{lcm}=72'},
           {label:'求解', math:'\\operatorname{lcm}=12'}],
    answer:'12'},
  explain:'把兩數做質因數分解後，gcd 取各質因數的最小次方、lcm 取最大次方，兩者相乘剛好把所有次方補齊成 ab。此關係只對「兩個數」成立。',
  source:'自己要記'}),

card({id:'B19', grade:7, category:'num', kind:'property', title:'不等式乘除負數要變號',
  formula:'a<b,\\ c<0\\Rightarrow ac>bc',
  variables:[{sym:'c', desc:'乘上或除以的負數'}],
  usageConditions:'解不等式時，只要兩邊同乘或同除一個負數，不等號方向就要顛倒。',
  triggerWords:['解不等式', '至少', '至多', '−x 的係數'],
  commonMistakes:['乘除負數忘記變號', '加減負數時卻多此一舉去變號'],
  recall:{type:'blank', prompt:'不等式兩邊同乘一個負數時，不等號會？',
    template:'a<b,\\ c<0\\Rightarrow ac@1bc', blanks:['>'],
    bank:['>', '<', '=', '\\geq'], hint1:'方向要顛倒過來。'},
  recog:{type:'choice', prompt:'解 −2x > 6 時，兩邊同除以 −2，不等號會變成？',
    options:[{math:'x<-3'}, {math:'x>-3'}, {math:'x<3'}, {math:'x>3'}],
    answer:0, hint1:'除以負數 ⇒ 不等號反向。',
    why:'兩邊同除以 −2（負數），不等號由 > 變成 <，得 x < −3。'},
  apply:{type:'choice', prompt:'解不等式 −3x ≤ 12，答案是？',
    given:'-3x\\leq 12', options:[{math:'x\\geq -4'}, {math:'x\\leq -4'},
      {math:'x\\geq 4'}, {math:'x\\leq 4'}],
    answer:0, unit:'', hint1:'兩邊同除以 −3，≤ 要變成 ≥。',
    steps:['兩邊同除以 −3（負數）', '不等號反向：x ≥ 12 ÷ (−3)', 'x ≥ −4']},
  worked:{title:'解 −3x ≤ 12', given:'-3x\\leq 12',
    steps:[{label:'兩邊除以 −3', text:'除數是負的，不等號要反向'},
           {label:'反向後', math:'x\\geq\\frac{12}{-3}'},
           {label:'計算', math:'x\\geq -4'}],
    answer:'x\\geq -4'},
  explain:'加、減任何數都不必變號；只有乘或除以「負數」時才要把不等號反過來。',
  source:'自己要記'}),

card({id:'C1', grade:8, category:'num', title:'根號的平方',
  formula:'(\\sqrt{a})^2=a,\\ a\\geq 0',
  variables:[{sym:'a', desc:'被開方數，必須大於等於 0'}],
  usageConditions:'先開根號再平方時，直接回到原數。',
  triggerWords:['根號', '平方', '化簡', '有理化'],
  commonMistakes:['與 √(a²) = |a| 搞混', '忘記 a ≥ 0 的限制'],
  recall:{type:'blank', prompt:'補完根號的平方。',
    template:'(\\sqrt{a})^2=@1,\\ a\\geq 0', blanks:['a'],
    bank:['a', '|a|', 'a^2', '\\sqrt{a}'], hint1:'先開根號再平方，兩個動作互相抵消。'},
  recog:{type:'choice', prompt:'(√7)² 等於多少？',
    options:[{math:'7'}, {math:'\\sqrt{7}'}, {math:'49'}, {math:'14'}],
    answer:0, hint1:'開根號與平方互為反運算。',
    why:'(√7)² = 7，因為 √7 是「平方後等於 7 的正數」。'},
  apply:{type:'numeric', prompt:'計算 (√5)² + (√11)² 的值。',
    given:'(\\sqrt{5})^2+(\\sqrt{11})^2', answer:'16', unit:'',
    hint1:'各自還原成被開方數。',
    steps:['(√5)² = 5，(√11)² = 11', '5 + 11 = 16']},
  worked:{title:'計算 (√5)² + (√11)²', given:'(\\sqrt{5})^2+(\\sqrt{11})^2',
    steps:[{label:'還原', math:'5+11'}, {label:'計算', math:'=16'}],
    answer:'16'},
  explain:'(√a)² 的前提是 a ≥ 0（否則根號沒有意義），所以結果直接是 a，不必加絕對值。',
  source:'自己要記'}),

card({id:'C2', grade:8, category:'num', title:'平方再開根號',
  formula:'\\sqrt{a^2}=|a|',
  variables:[{sym:'a', desc:'任意實數，可正可負'}],
  usageConditions:'先平方再開根號時，結果一定是非負數，所以要加絕對值。',
  triggerWords:['根號', '平方', '絕對值', '化簡'],
  commonMistakes:['直接寫成 a，忽略 a 可能是負數', '與 (√a)² = a 搞混'],
  recall:{type:'blank', prompt:'補完平方再開根號的結果。',
    template:'\\sqrt{a^2}=@1', blanks:['|a|'],
    bank:['|a|', 'a', '-a', 'a^2'], hint1:'根號的結果不能是負的。'},
  recog:{type:'choice', prompt:'√((−6)²) 等於多少？',
    options:[{math:'6'}, {math:'-6'}, {math:'36'}, {math:'\\pm 6'}],
    answer:0, hint1:'先算括號內的平方，再開根號。',
    why:'(−6)² = 36，√36 = 6。根號求的是非負的那個值，所以答案是 6 = |−6|。'},
  apply:{type:'numeric', prompt:'計算 √((−9)²) 的值。',
    given:'\\sqrt{(-9)^2}', answer:'9', unit:'', hint1:'√(a²) = |a|。',
    steps:['(−9)² = 81', '√81 = 9（也就是 |−9|）']},
  worked:{title:'計算 √((−9)²)', given:'\\sqrt{(-9)^2}',
    steps:[{label:'用公式', math:'\\sqrt{(-9)^2}=|-9|'}, {label:'取絕對值', math:'=9'}],
    answer:'9'},
  explain:'√(a²) 與 (√a)² 不同：前者 a 可以是負數，結果取絕對值；後者要求 a ≥ 0，結果就是 a。',
  source:'自己要記'}),

card({id:'C3', grade:8, category:'num', title:'根號相乘',
  formula:'\\sqrt{a}\\sqrt{b}=\\sqrt{ab},\\ a,b\\geq 0',
  variables:[{sym:'a, b', desc:'被開方數，都要大於等於 0'}],
  usageConditions:'兩個根號相乘可以合併；反過來也可以把大根號拆成兩個以便化簡。',
  triggerWords:['根號相乘', '化簡根式', '最簡根式'],
  commonMistakes:['對相加也套用（√a + √b ≠ √(a+b)）', '忘記檢查 a、b 非負'],
  recall:{type:'blank', prompt:'補完根號相乘的規則。',
    template:'\\sqrt{a}\\sqrt{b}=@1', blanks:['\\sqrt{ab}'],
    bank:['\\sqrt{ab}', '\\sqrt{a+b}', 'ab', '\\sqrt{a}+\\sqrt{b}'],
    hint1:'兩個被開方數相乘，放進同一個根號。'},
  recog:{type:'choice', prompt:'化簡 √12 最好的第一步是？',
    options:[{t:'拆成 √4 × √3'}, {t:'拆成 √6 × √6'}, {t:'寫成 √10 + √2'}, {t:'直接寫 3√4'}],
    answer:0, hint1:'拆出一個「完全平方數」才化得掉。',
    why:'12 = 4 × 3，4 是完全平方數，所以 √12 = √4 · √3 = 2√3。'},
  apply:{type:'choice', prompt:'√8 × √2 化簡後等於多少？',
    given:'\\sqrt{8}\\times\\sqrt{2}', options:[{math:'4'}, {math:'\\sqrt{10}'},
      {math:'2\\sqrt{2}'}, {math:'16'}],
    answer:0, unit:'', hint1:'先合併成一個根號。',
    steps:['√8 × √2 = √16', '√16 = 4']},
  worked:{title:'化簡 √8 × √2', given:'\\sqrt{8}\\times\\sqrt{2}',
    steps:[{label:'合併根號', math:'\\sqrt{8\\times 2}'},
           {label:'計算', math:'=\\sqrt{16}'}, {label:'開方', math:'=4'}],
    answer:'4'},
  explain:'只有「相乘」可以合併根號，相加不行。化簡時要把被開方數拆出最大的完全平方因數。',
  source:'自己要記'}),

card({id:'C4', grade:8, category:'num', title:'根號相除',
  formula:'\\frac{\\sqrt{a}}{\\sqrt{b}}=\\sqrt{\\frac{a}{b}},\\ a\\geq 0,\\ b>0',
  variables:[{sym:'a', desc:'分子的被開方數，可為 0'}, {sym:'b', desc:'分母的被開方數，必須大於 0'}],
  usageConditions:'兩個根號相除可以合併成一個根號；也用於分母有理化前的整理。',
  triggerWords:['根號相除', '分母有理化', '化簡'],
  commonMistakes:['分母為 0 仍套用', '對相減也套用', '化簡後忘記分母有理化'],
  recall:{type:'blank', prompt:'補完根號相除的規則。',
    template:'\\frac{\\sqrt{a}}{\\sqrt{b}}=@1', blanks:['\\sqrt{\\frac{a}{b}}'],
    bank:['\\sqrt{\\frac{a}{b}}', '\\frac{a}{b}', '\\sqrt{a-b}', '\\frac{\\sqrt{a}}{b}'],
    hint1:'把兩個被開方數放在同一個根號裡相除。'},
  recog:{type:'choice', prompt:'√18 ÷ √2 最快的算法是？',
    options:[{t:'先合併成 √9'}, {t:'先各自化簡成 3√2 ÷ √2'},
             {t:'寫成 √16'}, {t:'兩邊都平方'}],
    answer:0, hint1:'合併成一個根號後看看能不能整除。',
    why:'√18 ÷ √2 = √(18÷2) = √9 = 3。第二個做法也能得到 3，但多了一步。'},
  apply:{type:'numeric', prompt:'√50 ÷ √2 等於多少？',
    given:'\\frac{\\sqrt{50}}{\\sqrt{2}}', answer:'5', unit:'', hint1:'50 ÷ 2 = 25。',
    steps:['√50 ÷ √2 = √(50 ÷ 2)', '= √25 = 5']},
  worked:{title:'計算 √50 ÷ √2', given:'\\frac{\\sqrt{50}}{\\sqrt{2}}',
    steps:[{label:'合併根號', math:'\\sqrt{\\frac{50}{2}}'},
           {label:'約分', math:'=\\sqrt{25}'}, {label:'開方', math:'=5'}],
    answer:'5'},
  explain:'分母的 b 必須大於 0（不能是 0，也不能讓根號內為負）。若最後分母還留著根號，要再做分母有理化。',
  source:'自己要記'})

];
