/* ══════════════════════════════════════════════════════════════════════
   知識點資料：函數與統計、幾何公式（題本未附）
   ══════════════════════════════════════════════════════════════════════ */
var FUNC_CARDS = [

card({id:'D1', grade:8, category:'eq', title:'水平線 y = c',
  formula:'y=c',
  variables:[{sym:'c', desc:'固定的 y 坐標'}],
  usageConditions:'圖形上所有點的 y 都一樣時使用；平行 x 軸。',
  triggerWords:['平行 x 軸', '高度固定', '水平線'],
  commonMistakes:['把水平線寫成 x = c', '以為 y = c 不是函數'],
  diagramType:'LinearFunctionGraph', diagramData:{variant:'hv'},
  recall:{type:'blank', prompt:'平行 x 軸的水平線方程式是？',
    template:'@1', blanks:['y=c'], bank:['y=c', 'x=c', 'y=x', 'x=y'],
    hint1:'水平線上每一點的高度（y）都一樣。'},
  recog:{type:'choice', prompt:'通過 (2, 5) 且平行 x 軸的直線是？',
    options:[{math:'y=5'}, {math:'x=2'}, {math:'y=2'}, {math:'x=5'}],
    answer:0, hint1:'平行 x 軸 ⇒ y 固定。',
    why:'平行 x 軸的直線上所有點 y 都相同，這條線上的 y 都是 5，所以是 y = 5。'},
  apply:{type:'choice', prompt:'直線 y = −3 與 y 軸的交點是？',
    given:'y=-3', options:[{math:'(0,-3)'}, {math:'(-3,0)'}, {math:'(0,3)'}, {math:'(3,0)'}],
    answer:0, unit:'', hint1:'在 y 軸上的點，x 一定是 0。',
    steps:['y 軸上的點 x = 0', '這條線上 y 恆為 −3', '交點是 (0, −3)']},
  worked:{title:'找 y = −3 與 y 軸的交點', given:'y=-3',
    steps:[{label:'y 軸的條件', math:'x=0'},
           {label:'代入直線', text:'不論 x 是多少，y 都是 −3'},
           {label:'交點', math:'(0,-3)'}],
    answer:'(0,-3)'},
  explain:'c 是固定的高度。y = c 的圖形是一條水平線，斜率為 0（本課程不使用斜率公式，只需知道它是水平的）。',
  source:'自己要記'}),

card({id:'D2', grade:8, category:'eq', title:'鉛垂線 x = c',
  formula:'x=c',
  variables:[{sym:'c', desc:'固定的 x 坐標'}],
  usageConditions:'圖形上所有點的 x 都一樣時使用；平行 y 軸，不是函數。',
  triggerWords:['平行 y 軸', '鉛垂線', '垂直線'],
  commonMistakes:['與 y = c 顛倒', '以為它可以寫成 y = ax + b'],
  diagramType:'LinearFunctionGraph', diagramData:{variant:'hv'},
  recall:{type:'blank', prompt:'平行 y 軸的鉛垂線方程式是？',
    template:'@1', blanks:['x=c'], bank:['x=c', 'y=c', 'y=x', 'y=cx'],
    hint1:'鉛垂線上每一點的左右位置（x）都一樣。'},
  recog:{type:'choice', prompt:'通過 (4, −1) 且平行 y 軸的直線是？',
    options:[{math:'x=4'}, {math:'y=-1'}, {math:'x=-1'}, {math:'y=4'}],
    answer:0, hint1:'平行 y 軸 ⇒ x 固定。',
    why:'平行 y 軸的直線上所有點 x 都相同，這條線的 x 都是 4，所以是 x = 4。'},
  apply:{type:'choice', prompt:'直線 x = 4 與直線 y = 3 的交點坐標是？',
    given:'x=4,\\ y=3', options:[{math:'(4,3)'}, {math:'(3,4)'}, {math:'(4,0)'}, {math:'(0,3)'}],
    answer:0, unit:'', hint1:'一條決定 x，一條決定 y。',
    steps:['x = 4 給定橫坐標', 'y = 3 給定縱坐標', '交點是 (4, 3)']},
  worked:{title:'求 x = 4 與 y = 3 的交點', given:'x=4,\\ y=3',
    steps:[{label:'讀出兩個條件', text:'x 必須是 4，y 必須是 3'},
           {label:'寫成坐標', math:'(4,3)'}],
    answer:'(4,3)'},
  explain:'c 是固定的左右位置。x = c 的圖形是鉛垂線，因為同一個 x 對到無限多個 y，所以它不是函數。',
  source:'自己要記'}),

card({id:'D3', grade:8, category:'eq', title:'一次函數 y = ax + b',
  formula:'y=ax+b,\\ a\\neq 0',
  variables:[{sym:'a', desc:'決定傾斜方向，不可為 0'}, {sym:'b', desc:'與 y 軸的交點高度'},
             {sym:'x', desc:'自變數'}, {sym:'y', desc:'應變數'}],
  usageConditions:'兩量呈固定增減關係（每多 1 就多 a）時使用；圖形是直線。',
  triggerWords:['每增加', '固定費用', '基本費', '直線', '一次函數'],
  commonMistakes:['a = 0 也叫一次函數', '把 b 當成傾斜程度', '表格中沒檢查差是否固定就當一次函數'],
  diagramType:'LinearFunctionGraph', diagramData:{variant:'compare'},
  recall:{type:'blank', prompt:'補完一次函數的一般式與限制。',
    template:'y=@1+b,\\ a@2 0', blanks:['ax', '\\neq'],
    bank:['ax', '\\neq', 'ax^2', '='], hint1:'x 的最高次方是 1，而且 x 的係數不能是 0。'},
  recog:{type:'choice', prompt:'計程車起跳 85 元，之後每公里加 20 元。總車資 y 與里程 x 的關係是？',
    options:[{math:'y=20x+85'}, {math:'y=85x+20'}, {math:'y=105x'}, {math:'y=20x'}],
    answer:0, hint1:'固定不變的是起跳價，隨里程變的是每公里費用。',
    why:'每公里增加 20 元 ⇒ a = 20；還沒開就要付的 85 元是固定的 ⇒ b = 85。'},
  apply:{type:'numeric', prompt:'一次函數 y = 20x + 85，當 x = 6 時 y 是多少？',
    given:'y=20x+85,\\ x=6', answer:'205', unit:'元', hint1:'先算 20 × 6，再加 85。',
    steps:['y = 20 × 6 + 85', '= 120 + 85 = 205']},
  worked:{title:'計程車車資', given:'y=20x+85,\\ x=6',
    steps:[{label:'代入 x', math:'y=20\\times 6+85'},
           {label:'先乘後加', math:'=120+85'},
           {label:'得答案', math:'=205'}],
    answer:'205 \\text{ 元}'},
  explain:'a 是「每增加 1 單位 x 時 y 的變化量」，a > 0 圖形由左下往右上、a < 0 由左上往右下；b 是 x = 0 時的 y 值，也就是與 y 軸的交點。',
  source:'自己要記'}),

card({id:'D4', grade:9, category:'eq', title:'二次函數頂點式的頂點',
  formula:'y=a(x-h)^2+k\\Rightarrow \\text{頂點}(h,k)',
  variables:[{sym:'h', desc:'左右平移量，往右為正'}, {sym:'k', desc:'上下平移量，往上為正'},
             {sym:'a', desc:'決定開口方向與寬窄'}],
  usageConditions:'函數已寫成 y = a(x − h)² + k 時，直接讀出頂點坐標。',
  triggerWords:['頂點', '最高點', '最低點', '最大值', '最小值'],
  commonMistakes:['把 h 的正負號抄反（(x−3)² 的 h 是 3 不是 −3）', '把 k 寫進 x 的位置'],
  diagramType:'QuadraticFunctionGraph', diagramData:{variant:'shift'},
  recall:{type:'blank', prompt:'y = a(x − h)² + k 的頂點坐標是？',
    template:'\\text{頂點}=@1', blanks:['(h,k)'],
    bank:['(h,k)', '(-h,k)', '(k,h)', '(h,-k)'],
    hint1:'括號裡減去的數就是 h，最後加上的數就是 k。'},
  recog:{type:'choice', prompt:'y = 2(x + 3)² − 5 的頂點是？',
    options:[{math:'(-3,-5)'}, {math:'(3,-5)'}, {math:'(-3,5)'}, {math:'(3,5)'}],
    answer:0, hint1:'(x + 3) 要看成 (x − (−3))。',
    why:'(x + 3)² = (x − (−3))²，所以 h = −3、k = −5，頂點為 (−3, −5)。'},
  apply:{type:'choice', prompt:'y = −(x − 4)² + 7 的頂點是？',
    given:'y=-(x-4)^2+7',
    options:[{math:'(4,7)'}, {math:'(-4,7)'}, {math:'(7,4)'}, {math:'(4,-7)'}],
    answer:0, unit:'', hint1:'括號裡是 x − 4 ⇒ h = 4。',
    steps:['對照 y = a(x − h)² + k', 'h = 4、k = 7', '頂點是 (4, 7)']},
  worked:{title:'讀出 y = −(x−4)² + 7 的頂點', given:'y=-(x-4)^2+7',
    steps:[{label:'對照式子', text:'a = −1、h = 4、k = 7'},
           {label:'寫出頂點', math:'(h,k)=(4,7)'},
           {label:'補充', text:'a < 0 開口向下，所以 (4, 7) 是最高點，最大值為 7'}],
    answer:'(4,7)'},
  explain:'h 在括號裡且前面是減號，所以 (x − 4) 的 h 是 +4、(x + 3) 的 h 是 −3。k 在括號外，直接就是 y 坐標。',
  source:'自己要記'}),

card({id:'D5', grade:9, category:'eq', title:'二次函數的對稱軸',
  formula:'y=a(x-h)^2+k\\Rightarrow \\text{對稱軸 } x=h',
  variables:[{sym:'h', desc:'頂點的 x 坐標，也是對稱軸的位置'}],
  usageConditions:'求對稱軸、判斷兩點是否對稱、比較兩個 x 對應的 y 大小時使用。',
  triggerWords:['對稱軸', '對稱', '相同的 y 值', '左右一樣高'],
  commonMistakes:['寫成 y = h', '把對稱軸寫成 x = k'],
  diagramType:'QuadraticFunctionGraph', diagramData:{variant:'vertex'},
  recall:{type:'blank', prompt:'y = a(x − h)² + k 的對稱軸是？',
    template:'@1', blanks:['x=h'], bank:['x=h', 'y=h', 'x=k', 'y=k'],
    hint1:'對稱軸是一條鉛垂線，通過頂點。'},
  recog:{type:'choice', prompt:'y = 3(x − 2)² + 1 上哪兩個 x 的 y 值一定相同？',
    options:[{t:'x = 1 與 x = 3'}, {t:'x = 0 與 x = 1'},
             {t:'x = 2 與 x = 3'}, {t:'x = −2 與 x = 2'}],
    answer:0, hint1:'對稱軸是 x = 2，找左右等距的兩點。',
    why:'對稱軸 x = 2，x = 1 與 x = 3 都距離對稱軸 1 單位，所以 y 值相同。'},
  apply:{type:'choice', prompt:'y = −2(x + 5)² + 3 的對稱軸是？',
    given:'y=-2(x+5)^2+3',
    options:[{math:'x=-5'}, {math:'x=5'}, {math:'y=3'}, {math:'x=3'}],
    answer:0, unit:'', hint1:'(x + 5) = (x − (−5))。',
    steps:['h = −5', '對稱軸是 x = h', '所以對稱軸為 x = −5']},
  worked:{title:'求 y = −2(x+5)² + 3 的對稱軸', given:'y=-2(x+5)^2+3',
    steps:[{label:'找 h', math:'(x+5)^2=(x-(-5))^2\\Rightarrow h=-5'},
           {label:'寫對稱軸', math:'x=-5'}],
    answer:'x=-5'},
  explain:'對稱軸是通過頂點的鉛垂線，方程式一定是 x = 某數。距離對稱軸相同的兩個 x，函數值一定相等。',
  source:'自己要記'}),

card({id:'D6', grade:9, category:'eq', kind:'property', title:'二次函數的開口方向',
  formula:'y=a(x-h)^2+k \\text{ 中：} a>0 \\text{ 開口向上，} a<0 \\text{ 開口向下}',
  variables:[{sym:'a', desc:'二次函數 y = a(x − h)² + k 括號前面的係數，正負決定開口方向，絕對值決定寬窄'},
             {sym:'(h, k)', desc:'頂點，開口向上時是最低點，開口向下時是最高點'}],
  usageConditions:'判斷有最大值還是最小值、判斷圖形形狀時使用。',
  triggerWords:['開口', '最大值', '最小值', '圖形形狀'],
  commonMistakes:['把 a 的正負與頂點高低混為一談', '以為開口向上就一定有最大值'],
  diagramType:'QuadraticFunctionGraph', diagramData:{variant:'open'},
  recall:{type:'blank', prompt:'補完開口方向的判斷。',
    template:'y=a(x-h)^2+k \\text{ 中：} a>0 \\Rightarrow \\text{開口向}@1,\\quad a<0 \\Rightarrow \\text{開口向}@2',
    blanks:['\\text{上}', '\\text{下}'],
    bank:['\\text{上}', '\\text{下}', '\\text{左}', '\\text{右}'],
    hint1:'這裡的 a 是 y = a(x − h)² + k 括號前面那個係數：正的像微笑，負的像難過的嘴角。'},
  recog:{type:'choice', prompt:'y = −3(x − 1)² + 8 有最大值還是最小值？',
    options:[{t:'最大值 8'}, {t:'最小值 8'}, {t:'最大值 1'}, {t:'沒有極值'}],
    answer:0, hint1:'先看括號前的 a 是正是負，再看頂點的 k。',
    why:'a = −3 < 0，開口向下，頂點 (1, 8) 是最高點，所以有最大值 8。'},
  apply:{type:'choice', prompt:'下列哪一個二次函數的圖形開口向上且開口最窄？',
    given:'', options:[{math:'y=4x^2'}, {math:'y=x^2'},
      {math:'y=-4x^2'}, {math:'y=\\frac{1}{2}x^2'}],
    answer:0, unit:'', hint1:'先篩掉括號前係數 a < 0 的，再比 |a| 誰最大。',
    steps:['開口向上 ⇒ a > 0，排除 y = −4x²', '|a| 愈大開口愈窄', '|4| > |1| > |½|，所以 y = 4x² 最窄']},
  worked:{title:'判斷 y = −3(x−1)² + 8 的極值', given:'y=-3(x-1)^2+8',
    steps:[{label:'看括號前的 a', text:'a = −3 < 0，開口向下'},
           {label:'找頂點', math:'(h,k)=(1,8)'},
           {label:'下結論', text:'開口向下 ⇒ 頂點是最高點 ⇒ 最大值為 8'}],
    answer:'\\text{最大值 } 8'},
  explain:'這裡的 a 專指二次函數 y = a(x − h)² + k 括號前面的係數。a > 0 開口向上（頂點是最低點、有最小值），a < 0 開口向下（頂點是最高點、有最大值）；|a| 愈大開口愈窄。',
  source:'自己要記'}),

card({id:'D7', grade:7, category:'stat', title:'平均數',
  formula:'\\text{平均數}=\\frac{\\text{總和}}{\\text{個數}}',
  variables:[{sym:'總和', desc:'所有資料相加'}, {sym:'個數', desc:'資料筆數'}],
  usageConditions:'求一組資料的集中情形時使用；每筆資料同等重要時用它。',
  triggerWords:['平均', '每人平均', '平均分數'],
  commonMistakes:['個數數錯', '有 0 分的資料就漏掉不算', '與中位數混用'],
  recall:{type:'blank', prompt:'補完平均數公式。',
    template:'\\text{平均數}=\\frac{@1}{@2}', blanks:['\\text{總和}', '\\text{個數}'],
    bank:['\\text{總和}', '\\text{個數}', '\\text{次數}', '\\text{全距}'],
    hint1:'把所有資料加起來，再除以有幾筆。'},
  recog:{type:'choice', prompt:'資料 2、100、3、4、5，用哪一個統計量描述「中心」比較不會被極端值影響？',
    options:[{t:'中位數'}, {t:'平均數'}, {t:'全距'}, {t:'總和'}],
    answer:0, hint1:'有一筆資料特別大。',
    why:'100 是極端值，會把平均數拉高到 22.8，中位數 4 比較能代表整體。'},
  apply:{type:'numeric', prompt:'五次小考成績 80、85、90、75、70，平均是多少分？',
    given:'80,85,90,75,70', answer:'80', unit:'分', hint1:'先加總再除以 5。',
    steps:['總和 = 80 + 85 + 90 + 75 + 70 = 400', '400 ÷ 5 = 80（分）']},
  worked:{title:'求五次小考平均', given:'80,\\ 85,\\ 90,\\ 75,\\ 70',
    steps:[{label:'加總', math:'80+85+90+75+70=400'},
           {label:'除以個數', math:'\\frac{400}{5}=80'}],
    answer:'80 \\text{ 分}'},
  explain:'平均數會被極端值影響。若題目資料中有特別大或特別小的值，通常會考中位數。',
  source:'自己要記'}),

card({id:'D8', grade:7, category:'stat', title:'加權平均',
  formula:'\\text{加權平均}=\\frac{\\sum(\\text{數值}\\times\\text{次數})}{\\sum\\text{次數}}',
  variables:[{sym:'數值', desc:'每一組的代表值或分數'}, {sym:'次數', desc:'該組出現幾次或所佔權重'}],
  usageConditions:'每筆資料重要性不同（學分數、人數、比重）時使用。',
  triggerWords:['加權', '各佔', '比重', '學分', '人數不同'],
  commonMistakes:['直接把各組數值平均', '分母只寫組數而不是次數總和', '權重沒有加總'],
  recall:{type:'blank', prompt:'補完加權平均公式。',
    template:'\\text{加權平均}=\\frac{\\sum(\\text{數值}\\times@1)}{\\sum@2}',
    blanks:['\\text{次數}', '\\text{次數}'],
    bank:['\\text{次數}', '\\text{數值}', '\\text{組數}', '\\text{總和}'],
    hint1:'分子把每個值乘上它的次數，分母是次數總和。'},
  recog:{type:'choice', prompt:'甲班 20 人平均 80 分、乙班 30 人平均 70 分，兩班合起來的平均是？',
    options:[{t:'用加權平均，不是 75 分'}, {t:'(80 + 70) ÷ 2 = 75 分'},
             {t:'80 分'}, {t:'70 分'}],
    answer:0, hint1:'兩班人數不一樣多。',
    why:'人數不同時要加權：(20×80 + 30×70) ÷ 50 = 3700 ÷ 50 = 74 分，不是 75 分。'},
  apply:{type:'numeric', prompt:'甲班 20 人平均 80 分、乙班 30 人平均 70 分，兩班合計的平均是幾分？',
    given:'20\\times 80+30\\times 70', answer:'74', unit:'分',
    hint1:'先算總分，再除以總人數 50。',
    steps:['總分 = 20 × 80 + 30 × 70 = 1600 + 2100 = 3700', '總人數 = 20 + 30 = 50', '3700 ÷ 50 = 74（分）']},
  worked:{title:'兩班合併的平均分數', given:'20 \\text{ 人平均 } 80,\\ 30 \\text{ 人平均 } 70',
    steps:[{label:'算各班總分', math:'20\\times 80=1600,\\ 30\\times 70=2100'},
           {label:'加總', math:'1600+2100=3700'},
           {label:'除以總人數', math:'\\frac{3700}{50}=74'}],
    answer:'74 \\text{ 分}'},
  explain:'加權平均的分母一定是「次數（權重）總和」，不是組數。人數多的那一組會把平均拉向自己。',
  source:'自己要記'}),

card({id:'D9', grade:7, category:'stat', title:'相對次數',
  formula:'\\text{相對次數}=\\frac{\\text{該組次數}}{\\text{總次數}}',
  variables:[{sym:'該組次數', desc:'某一組出現的筆數'}, {sym:'總次數', desc:'全部資料筆數'}],
  usageConditions:'比較不同總數的兩組資料，或畫相對次數分配圖時使用。',
  triggerWords:['相對次數', '所佔比例', '百分比分配'],
  commonMistakes:['分母用組數而非總次數', '所有相對次數相加不等於 1 就沒察覺'],
  recall:{type:'blank', prompt:'補完相對次數公式。',
    template:'\\text{相對次數}=\\frac{@1}{@2}', blanks:['\\text{該組次數}', '\\text{總次數}'],
    bank:['\\text{該組次數}', '\\text{總次數}', '\\text{組數}', '\\text{組距}'],
    hint1:'某一組佔全部的比例。'},
  recog:{type:'choice', prompt:'全部相對次數加起來應該等於多少？',
    options:[{math:'1'}, {math:'100'}, {math:'\\text{總次數}'}, {math:'\\text{組數}'}],
    answer:0, hint1:'每一組都是「佔全部的幾分之幾」。',
    why:'所有組的次數相加就是總次數，除以總次數後恰好是 1（也就是 100%）。'},
  apply:{type:'choice', prompt:'40 人中有 10 人搭公車，這一組的相對次數是多少？',
    given:'\\frac{10}{40}', options:[{math:'0.25'}, {math:'0.4'}, {math:'2.5'}, {math:'10'}],
    answer:0, unit:'', hint1:'10 ÷ 40。',
    steps:['10 ÷ 40 = 0.25', '也就是 25%']},
  worked:{title:'求搭公車的相對次數', given:'\\text{該組 } 10 \\text{ 人，共 } 40 \\text{ 人}',
    steps:[{label:'代入', math:'\\frac{10}{40}'}, {label:'化簡', math:'=0.25'},
           {label:'換成百分比', text:'0.25 = 25%'}],
    answer:'0.25'},
  explain:'相對次數是比例，介於 0 與 1 之間；全部相加必為 1。它讓總人數不同的兩組資料可以公平比較。',
  source:'自己要記'}),

card({id:'D10', grade:9, category:'stat', title:'全距',
  formula:'\\text{全距}=\\text{最大值}-\\text{最小值}',
  variables:[{sym:'最大值', desc:'資料中最大的一筆'}, {sym:'最小值', desc:'資料中最小的一筆'}],
  usageConditions:'描述資料分散程度最簡單的方式，只看頭尾兩筆。',
  triggerWords:['全距', '相差最多', '分散程度', '差距'],
  commonMistakes:['沒排序就相減', '與四分位距混用', '算成最大加最小'],
  recall:{type:'blank', prompt:'補完全距公式。',
    template:'\\text{全距}=\\text{最大值}@1\\text{最小值}', blanks:['-'],
    bank:['-', '+', '\\times', '\\div'], hint1:'頭尾相減。'},
  recog:{type:'choice', prompt:'全距最大的缺點是什麼？',
    options:[{t:'只看頭尾兩筆，容易被極端值影響'}, {t:'計算太複雜'},
             {t:'一定要先算平均數'}, {t:'資料太多時算不出來'}],
    answer:0, hint1:'想想只有一筆特別大時會怎樣。',
    why:'全距只用最大值與最小值，中間資料完全沒被考慮，只要有一個極端值就會被拉大。'},
  apply:{type:'numeric', prompt:'資料 12、7、20、15、9 的全距是多少？',
    given:'12,7,20,15,9', answer:'13', unit:'', hint1:'找出最大 20 與最小 7。',
    steps:['最大值 = 20，最小值 = 7', '20 − 7 = 13']},
  worked:{title:'求全距', given:'12,\\ 7,\\ 20,\\ 15,\\ 9',
    steps:[{label:'排序', math:'7,\\ 9,\\ 12,\\ 15,\\ 20'},
           {label:'找頭尾', text:'最小 7、最大 20'},
           {label:'相減', math:'20-7=13'}],
    answer:'13'},
  explain:'全距愈大代表資料愈分散，但因為只看兩筆，遇到極端值時建議改看四分位距。',
  source:'自己要記'}),

card({id:'D11', grade:9, category:'stat', title:'四分位距',
  formula:'\\text{四分位距}=Q_3-Q_1',
  variables:[{sym:'Q₁', desc:'第一四分位數，前 25% 的分界'},
             {sym:'Q₃', desc:'第三四分位數，前 75% 的分界'},
             {sym:'四分位距', desc:'中間 50% 資料的寬度，也就是盒狀圖盒身的長度'}],
  usageConditions:'資料有極端值時，用來描述中間一半資料的分散程度；也是盒狀圖的盒身長度。',
  triggerWords:['四分位距', '盒狀圖', '中間一半', 'Q₁', 'Q₃'],
  commonMistakes:['忘記先排序', 'Q₃ 與 Q₁ 相減順序顛倒', '把四分位距當成全距'],
  recall:{type:'blank', prompt:'補完四分位距公式。',
    template:'\\text{四分位距}=@1-@2', blanks:['Q_3', 'Q_1'],
    bank:['Q_3', 'Q_1', 'Q_2', '\\text{最大值}'], hint1:'大的減小的：第三四分位數減第一四分位數。'},
  recog:{type:'choice', prompt:'盒狀圖中「盒子的長度」代表什麼？',
    options:[{t:'四分位距 Q₃ − Q₁'}, {t:'全距'}, {t:'中位數'}, {t:'平均數'}],
    answer:0, hint1:'盒子的兩端分別是 Q₁ 與 Q₃。',
    why:'盒身左右兩端是 Q₁ 與 Q₃，長度就是四分位距，代表中間 50% 資料的範圍。'},
  apply:{type:'numeric', prompt:'某組資料 Q₁ = 12、Q₂ = 18、Q₃ = 25，四分位距是多少？',
    given:'Q_1=12,\\ Q_3=25', answer:'13', unit:'', hint1:'只用 Q₃ 與 Q₁。',
    steps:['四分位距 = Q₃ − Q₁', '= 25 − 12 = 13']},
  worked:{title:'求四分位距', given:'Q_1=12,\\ Q_3=25',
    steps:[{label:'寫公式', math:'\\text{四分位距}=Q_3-Q_1'},
           {label:'代入', math:'=25-12'}, {label:'計算', math:'=13'}],
    answer:'13'},
  explain:'Q₂ 就是中位數，算四分位距時用不到。四分位距只看中間 50% 的資料，比全距更不受極端值影響。',
  source:'自己要記'}),

card({id:'D12', grade:9, category:'stat', title:'古典機率',
  formula:'\\text{機率}=\\frac{\\text{符合條件的結果數}}{\\text{全部等可能結果數}}',
  variables:[{sym:'分子', desc:'符合題目條件的結果有幾種'}, {sym:'分母', desc:'所有等可能的結果有幾種'}],
  usageConditions:'每個結果出現機會相同（公正骰子、均勻轉盤、隨機抽球）時使用。',
  triggerWords:['機率', 'random', '公正骰子', '隨機抽', '轉盤'],
  commonMistakes:['分母漏算', '結果不是等可能仍套用', '機率算出大於 1'],
  recall:{type:'blank', prompt:'補完古典機率公式。',
    template:'\\text{機率}=\\frac{@1}{@2}', blanks:['\\text{符合的結果數}', '\\text{全部結果數}'],
    bank:['\\text{符合的結果數}', '\\text{全部結果數}', '\\text{次數}', '\\text{總和}'],
    hint1:'符合條件的除以全部等可能的。'},
  recog:{type:'choice', prompt:'下列哪一個情境「不能」直接用古典機率？',
    options:[{t:'明天會不會下雨'}, {t:'擲一顆公正骰子出現 3 點'},
             {t:'從 5 顆相同大小的球中抽一顆'}, {t:'轉均分成 8 格的轉盤'}],
    answer:0, hint1:'每個結果的機會是不是一樣大？',
    why:'下雨與不下雨不是等可能事件，無法用「符合數 ÷ 全部數」計算。'},
  apply:{type:'choice', prompt:'擲一顆公正骰子，出現偶數點的機率是多少？',
    given:'', options:[{math:'\\frac{1}{2}'}, {math:'\\frac{1}{3}'},
      {math:'\\frac{1}{6}'}, {math:'\\frac{2}{3}'}],
    answer:0, unit:'', hint1:'偶數點有 2、4、6 共三種。',
    steps:['全部結果 6 種（1 到 6）', '偶數有 2、4、6 共 3 種', '機率 = 3 ÷ 6 = ½']},
  worked:{title:'擲骰子出現偶數的機率', given:'\\text{公正骰子}',
    steps:[{label:'列出全部結果', math:'1,2,3,4,5,6 \\Rightarrow 6 \\text{ 種}'},
           {label:'找符合的', math:'2,4,6 \\Rightarrow 3 \\text{ 種}'},
           {label:'相除', math:'\\text{機率}=\\frac{3}{6}=\\frac{1}{2}'}],
    answer:'\\frac{1}{2}'},
  explain:'古典機率的前提是「每個結果等可能」。機率一定介於 0 與 1 之間，算出大於 1 就是分母漏算了。',
  source:'自己要記'})

];

var GEOF_CARDS = [

card({id:'E1', grade:7, category:'geo', title:'三角形面積',
  formula:'\\text{面積}=\\text{底}\\times\\text{高}\\div 2',
  variables:[{sym:'底', desc:'任選一邊當作底'},
             {sym:'高', desc:'從對面頂點垂直落到這個底的長度'}],
  usageConditions:'已知一組互相垂直的底與高時使用。',
  triggerWords:['面積', '底', '高', '垂直'],
  commonMistakes:['把斜邊當成高', '忘記最後要除以 2', '底與高不是互相對應的一組'],
  diagramType:'TriangleDiagram', diagramData:{variant:'area'},
  recall:{type:'blank', prompt:'補完三角形面積公式。',
    template:'\\text{面積}=\\text{底}\\times\\text{高}@1', blanks:['\\div 2'],
    bank:['\\div 2', '\\times 2', '\\div 3', '+2'],
    hint1:'三角形是同底同高平行四邊形的一半。'},
  recog:{type:'choice', prompt:'鈍角三角形的高落在底邊外面時，面積公式還能用嗎？',
    options:[{t:'可以，只要高垂直於底（或底的延長線）'}, {t:'不行，要改用其他公式'},
             {t:'要先把三角形補成長方形'}, {t:'要先量斜邊'}],
    answer:0, hint1:'高的定義是「垂直距離」。',
    why:'高是頂點到底邊所在直線的垂直距離，即使垂足落在延長線上，「底 × 高 ÷ 2」仍然成立。'},
  apply:{type:'numeric', prompt:'底 12 公分、高 5 公分的三角形面積是多少平方公分？',
    given:'\\text{底}=12,\\ \\text{高}=5', answer:'30', unit:'平方公分',
    hint1:'12 × 5 ÷ 2。',
    steps:['面積 = 12 × 5 ÷ 2', '= 60 ÷ 2 = 30（平方公分）']},
  worked:{title:'底 12、高 5 的三角形面積', given:'\\text{底}=12,\\ \\text{高}=5',
    steps:[{label:'寫公式', math:'\\text{面積}=\\text{底}\\times\\text{高}\\div 2'},
           {label:'代入', math:'=12\\times 5\\div 2'},
           {label:'計算', math:'=30'}],
    answer:'30 \\text{ 平方公分}'},
  explain:'底與高必須互相垂直、而且是對應的一組。三角形是同底同高平行四邊形的一半，所以最後要除以 2。',
  source:'自己要記'}),

card({id:'E2', grade:7, category:'geo', title:'平行四邊形面積',
  formula:'\\text{面積}=\\text{底}\\times\\text{高}',
  variables:[{sym:'底', desc:'任選一邊當作底'},
             {sym:'高', desc:'兩條平行底之間的垂直距離，不是斜邊'}],
  usageConditions:'已知底與對應的高時使用；高不是斜邊。',
  triggerWords:['平行四邊形', '面積', '底', '高'],
  commonMistakes:['用斜邊當高', '乘了 ½（那是三角形）'],
  diagramType:'QuadrilateralDiagram', diagramData:{variant:'parallelogram-area'},
  recall:{type:'blank', prompt:'補完平行四邊形面積公式。',
    template:'\\text{面積}=@1\\times@2', blanks:['\\text{底}', '\\text{高}'],
    bank:['\\text{底}', '\\text{高}', '\\text{斜邊}', '\\text{周長}'],
    hint1:'底乘高，不用再除以 2；乘的是高，不是斜邊。'},
  recog:{type:'choice', prompt:'平行四邊形底 10、斜邊 6、高 5，面積是多少？',
    options:[{math:'50'}, {math:'60'}, {math:'30'}, {math:'25'}],
    answer:0, hint1:'公式裡要用的是高，不是斜邊。',
    why:'面積 = 底 × 高 = 10 × 5 = 50。斜邊 6 是干擾條件。'},
  apply:{type:'numeric', prompt:'平行四邊形底 9 公分、高 4 公分，面積是多少平方公分？',
    given:'\\text{底}=9,\\ \\text{高}=4', answer:'36', unit:'平方公分', hint1:'9 × 4。',
    steps:['面積 = 9 × 4 = 36（平方公分）']},
  worked:{title:'底 9、高 4 的平行四邊形面積', given:'\\text{底}=9,\\ \\text{高}=4',
    steps:[{label:'寫公式', math:'\\text{面積}=\\text{底}\\times\\text{高}'},
           {label:'代入', math:'=9\\times 4=36'}],
    answer:'36 \\text{ 平方公分}'},
  explain:'把平行四邊形一端的三角形切下來補到另一端，就變成長方形，所以面積是底乘高。',
  source:'自己要記'}),

card({id:'E3', grade:7, category:'geo', title:'梯形面積',
  formula:'\\text{面積}=(\\text{上底}+\\text{下底})\\times\\text{高}\\div 2',
  variables:[{sym:'上底、下底', desc:'互相平行的那一組對邊'},
             {sym:'高', desc:'兩底之間的垂直距離，不是腰長'}],
  usageConditions:'有一組對邊平行時使用；上底與下底必須是互相平行的那一組，兩腰不能代進去。',
  triggerWords:['梯形', '上底', '下底', '面積'],
  commonMistakes:['把腰當成底', '忘記最後要除以 2', '高用斜腰（腰不是高）'],
  diagramType:'QuadrilateralDiagram', diagramData:{variant:'trapezoid-area'},
  recall:{type:'blank', prompt:'補完梯形面積公式。',
    template:'\\text{面積}=(\\text{上底}+\\text{下底})\\times\\text{高}@1',
    blanks:['\\div 2'],
    bank:['\\div 2', '\\times 2', '\\div 3', '+2'],
    hint1:'兩個相同的梯形可以拼成平行四邊形，所以最後要除以 2。'},
  recog:{type:'choice', prompt:'梯形面積公式中的「上底」與「下底」一定是？',
    options:[{t:'互相平行的一組對邊'}, {t:'兩條腰'}, {t:'最長與最短的邊'}, {t:'對角線'}],
    answer:0, hint1:'梯形的定義是「有一組對邊平行」。',
    why:'只有互相平行的那一組對邊才是上底與下底，兩腰不能代入。'},
  apply:{type:'numeric', prompt:'梯形上底 6、下底 10、高 4，面積是多少？',
    given:'\\text{上底}=6,\\ \\text{下底}=10,\\ \\text{高}=4', answer:'32',
    unit:'平方單位', hint1:'(6 + 10) × 4 ÷ 2。',
    steps:['面積 = (6 + 10) × 4 ÷ 2', '= 16 × 4 ÷ 2 = 32']},
  worked:{title:'上底 6、下底 10、高 4 的梯形面積',
    given:'\\text{上底}=6,\\ \\text{下底}=10,\\ \\text{高}=4',
    steps:[{label:'寫公式', math:'\\text{面積}=(\\text{上底}+\\text{下底})\\times\\text{高}\\div 2'},
           {label:'代入', math:'=(6+10)\\times 4\\div 2'},
           {label:'計算', math:'=16\\times 4\\div 2=32'}],
    answer:'32 \\text{ 平方單位}'},
  explain:'兩個相同的梯形可以拼成一個平行四邊形，它的底是「上底 ＋ 下底」、高相同，所以梯形是它的一半。',
  source:'自己要記'}),

card({id:'E4', grade:8, category:'geo', title:'正三角形的高',
  formula:'\\text{高}=\\frac{\\sqrt{3}}{2}\\times\\text{邊長}',
  variables:[{sym:'邊長', desc:'正三角形三邊都一樣長的那個長度'},
             {sym:'高', desc:'從一個頂點垂直落到對邊的長度'}],
  usageConditions:'正三角形（三邊等長）求高時使用，來自 30–60–90 的邊長比。',
  triggerWords:['正三角形', '等邊三角形', '高', '√3'],
  commonMistakes:['把 √3/2 記成 √2/2', '把邊長的一半直接當成高', '與正三角形面積公式混用'],
  diagramType:'TriangleDiagram', diagramData:{variant:'equilateral'},
  recall:{type:'blank', prompt:'補完正三角形的高。',
    template:'\\text{高}=@1\\times\\text{邊長}', blanks:['\\frac{\\sqrt{3}}{2}'],
    bank:['\\frac{\\sqrt{3}}{2}', '\\frac{\\sqrt{3}}{4}', '\\frac{\\sqrt{2}}{2}', '\\frac{1}{2}'],
    hint1:'高把正三角形切成兩個 30–60–90，高對應 √3 那一段。'},
  recog:{type:'choice', prompt:'正三角形作高之後，會得到兩個什麼三角形？',
    options:[{t:'30°–60°–90° 直角三角形'}, {t:'45°–45°–90° 直角三角形'},
             {t:'兩個正三角形'}, {t:'兩個鈍角三角形'}],
    answer:0, hint1:'頂角 60° 被平分成兩個 30°。',
    why:'高平分頂角 60° 成兩個 30°，底角仍是 60°，加上垂足的 90°，正是 30–60–90。'},
  apply:{type:'choice', prompt:'邊長 6 的正三角形，高是多少？',
    given:'\\text{邊長}=6', options:[{math:'3\\sqrt{3}'}, {math:'6\\sqrt{3}'},
      {math:'3'}, {math:'\\frac{3\\sqrt{3}}{2}'}],
    answer:0, unit:'', hint1:'把邊長 6 代進 (√3/2) × 邊長。',
    steps:['高 = (√3 ÷ 2) × 6', '= 3√3']},
  worked:{title:'邊長 6 的正三角形高', given:'\\text{邊長}=6',
    steps:[{label:'寫公式', math:'\\text{高}=\\frac{\\sqrt{3}}{2}\\times\\text{邊長}'},
           {label:'代入', math:'=\\frac{\\sqrt{3}}{2}\\times 6'},
           {label:'化簡', math:'=3\\sqrt{3}'}],
    answer:'3\\sqrt{3}'},
  explain:'高把正三角形切成兩個 30–60–90 直角三角形：斜邊是邊長，短邊是邊長的一半，長邊（也就是高）是短邊的 √3 倍，所以高等於邊長的 √3/2 倍。',
  source:'自己要記'}),

card({id:'E5', grade:8, category:'geo', title:'正三角形面積',
  formula:'\\text{面積}=\\frac{\\sqrt{3}}{4}\\times\\text{邊長}^2',
  variables:[{sym:'邊長', desc:'正三角形三邊共同的長度；公式裡要平方'}],
  usageConditions:'只知道正三角形邊長就要求面積時使用。',
  triggerWords:['正三角形', '面積', '邊長', '√3'],
  commonMistakes:['分母寫成 2', '邊長忘記平方', '與正三角形高的公式互換'],
  diagramType:'TriangleDiagram', diagramData:{variant:'equilateral'},
  recall:{type:'blank', prompt:'補完正三角形面積公式。',
    template:'\\text{面積}=@1\\times\\text{邊長}^2', blanks:['\\frac{\\sqrt{3}}{4}'],
    bank:['\\frac{\\sqrt{3}}{4}', '\\frac{\\sqrt{3}}{2}', '\\frac{1}{2}', '\\frac{\\sqrt{2}}{4}'],
    hint1:'面積比高多除一次 2，因為還要再乘底、再除以 2。'},
  recog:{type:'choice', prompt:'邊長變成 2 倍時，正三角形面積會變成幾倍？',
    options:[{t:'4 倍'}, {t:'2 倍'}, {t:'√3 倍'}, {t:'8 倍'}],
    answer:0, hint1:'公式裡的邊長是平方。',
    why:'面積和「邊長的平方」成正比，邊長變 2 倍 ⇒ 面積變 2² = 4 倍。'},
  apply:{type:'choice', prompt:'邊長 4 的正三角形面積是多少？',
    given:'\\text{邊長}=4', options:[{math:'4\\sqrt{3}'}, {math:'2\\sqrt{3}'},
      {math:'16\\sqrt{3}'}, {math:'8\\sqrt{3}'}],
    answer:0, unit:'', hint1:'(√3/4) × 4²。',
    steps:['面積 = (√3 ÷ 4) × 4²', '= (√3 ÷ 4) × 16 = 4√3']},
  worked:{title:'邊長 4 的正三角形面積', given:'\\text{邊長}=4',
    steps:[{label:'寫公式', math:'\\text{面積}=\\frac{\\sqrt{3}}{4}\\times\\text{邊長}^2'},
           {label:'代入', math:'=\\frac{\\sqrt{3}}{4}\\times 4^2'},
           {label:'計算', math:'=\\frac{\\sqrt{3}}{4}\\times 16=4\\sqrt{3}'}],
    answer:'4\\sqrt{3}'},
  explain:'面積 = 底 × 高 ÷ 2 = 邊長 ×（√3/2）× 邊長 ÷ 2 =（√3/4）× 邊長²。記法：高的分母是 2、面積的分母是 4。',
  source:'自己要記'}),

card({id:'E6', grade:8, category:'geo', title:'坐標平面上兩點的距離',
  formula:'\\text{兩點距離}=\\sqrt{(x_1-x_2)^2+(y_1-y_2)^2}',
  variables:[{sym:'(x₁, y₁)', desc:'第一點坐標'}, {sym:'(x₂, y₂)', desc:'第二點坐標'}],
  usageConditions:'求兩點距離、判斷等腰或直角三角形、求圓上點到圓心距離時使用。',
  triggerWords:['坐標', '距離', '等腰', '判斷三角形形狀'],
  commonMistakes:['x 與 y 相減後忘記平方', '把兩個差直接相加', '最後忘記開根號'],
  diagramType:'CoordinateDistanceDiagram', diagramData:{},
  recall:{type:'blank', prompt:'補完兩點距離公式。',
    template:'\\text{兩點距離}=\\sqrt{@1+@2}', blanks:['(x_1-x_2)^2', '(y_1-y_2)^2'],
    bank:['(x_1-x_2)^2', '(y_1-y_2)^2', '(x_1-x_2)', '(x_1+x_2)^2'],
    hint1:'其實就是把 x 的差與 y 的差當兩股，用勾股定理求斜邊。'},
  recog:{type:'choice', prompt:'這個公式其實是哪一個定理的應用？',
    options:[{t:'勾股定理'}, {t:'相似三角形'}, {t:'圓周角定理'}, {t:'三角形內角和'}],
    answer:0, hint1:'畫出 x 差與 y 差會形成什麼？',
    why:'x 的差與 y 的差構成直角三角形的兩股，兩點距離就是斜邊，所以是勾股定理。'},
  apply:{type:'numeric', prompt:'A(1, 1) 與 B(5, 4) 的距離是多少？',
    given:'A(1,1),\\ B(5,4)', answer:'5', unit:'', hint1:'x 差 4、y 差 3。',
    steps:['x 的差 = 5 − 1 = 4，y 的差 = 4 − 1 = 3', '距離 = √(4² + 3²) = √25', '距離 = 5']},
  worked:{title:'求 A(1,1) 與 B(5,4) 的距離', given:'A(1,1),\\ B(5,4)',
    steps:[{label:'算兩個差', math:'x:\\ 5-1=4,\\quad y:\\ 4-1=3'},
           {label:'代入公式', math:'\\text{兩點距離}=\\sqrt{4^2+3^2}'},
           {label:'計算', math:'=\\sqrt{16+9}=\\sqrt{25}'},
           {label:'開根號', math:'=5'}],
    answer:'5'},
  explain:'相減的順序不影響答案，因為平方後負號會消失。最後一定要記得開根號。',
  source:'自己要記'}),

card({id:'E7', grade:7, category:'geo', title:'正 n 邊形的每個內角',
  formula:'\\text{每個內角}=\\frac{(n-2)180^\\circ}{n}',
  variables:[{sym:'n', desc:'正多邊形的邊數'}],
  usageConditions:'正多邊形（每邊等長、每角相等）求單一內角時使用。',
  triggerWords:['正多邊形', '每一個內角', '正六邊形', '鋪磚'],
  commonMistakes:['忘記除以 n', '把內角和當成單一內角', '一般多邊形也套用'],
  diagramType:'QuadrilateralDiagram', diagramData:{variant:'regular-polygon'},
  recall:{type:'blank', prompt:'補完正 n 邊形每個內角的公式。',
    template:'\\text{每個內角}=\\frac{(n-2)180^\\circ}{@1}', blanks:['n'],
    bank:['n', 'n-2', '2', '180'], hint1:'先算內角和，再平分給 n 個角。'},
  recog:{type:'choice', prompt:'為什麼一般（不規則）多邊形不能用這個公式？',
    options:[{t:'因為各內角不一定相等'}, {t:'因為邊數不固定'},
             {t:'因為內角和公式不適用'}, {t:'因為沒有對角線'}],
    answer:0, hint1:'公式最後一步是「平分」。',
    why:'內角和 (n−2)×180° 對所有凸多邊形都成立，但只有每個角都相等的正多邊形才能直接除以 n。'},
  apply:{type:'numeric', prompt:'正五邊形的每一個內角是幾度？（只填數字）',
    given:'n=5', answer:'108', unit:'度', hint1:'先算 (5−2)×180° = 540°，再除以 5。',
    steps:['內角和 = (5 − 2) × 180° = 540°', '每個內角 = 540° ÷ 5 = 108°']},
  worked:{title:'正五邊形的每個內角', given:'n=5',
    steps:[{label:'算內角和', math:'(5-2)\\times 180^\\circ=540^\\circ'},
           {label:'平分', math:'\\frac{540^\\circ}{5}=108^\\circ'}],
    answer:'108^\\circ'},
  explain:'先用 (n−2)×180° 求出內角和，再除以 n。若題目是不規則多邊形，只能求內角和。',
  source:'自己要記'}),

card({id:'E8', grade:9, category:'geo', kind:'property', title:'相似形的面積比',
  formula:'\\text{邊長比}=k\\Rightarrow\\text{面積比}=k^2',
  variables:[{sym:'k', desc:'對應邊長的比（相似比）'}],
  usageConditions:'兩圖形相似，已知邊長比要求面積比（或反過來）時使用。',
  triggerWords:['相似', '放大', '縮小', '面積比', '比例尺'],
  commonMistakes:['面積比直接寫成 k', '由面積比求邊長比時忘記開根號', '把周長比當面積比'],
  diagramType:'SimilarTriangleDiagram', diagramData:{variant:'sides', k:3},
  recall:{type:'blank', prompt:'相似形邊長比為 k 時，面積比是？',
    template:'\\text{面積比}=@1', blanks:['k^2'],
    bank:['k^2', 'k', '2k', 'k^3'], hint1:'面積是兩個長度相乘，所以比要平方。'},
  recog:{type:'choice', prompt:'兩相似三角形面積比為 9 : 1，對應邊長比是多少？',
    options:[{t:'3 : 1'}, {t:'9 : 1'}, {t:'81 : 1'}, {t:'4.5 : 1'}],
    answer:0, hint1:'面積比開根號才是邊長比。',
    why:'k² = 9 ⇒ k = 3，所以邊長比是 3 : 1。'},
  apply:{type:'numeric', prompt:'兩相似三角形邊長比 1 : 3，小的面積 5，大的面積是多少？',
    given:'k=3,\\ \\text{小面積}=5', answer:'45', unit:'平方單位',
    hint1:'面積比是 1 : 9。',
    steps:['邊長比 1 : 3 ⇒ 面積比 1² : 3² = 1 : 9', '大三角形面積 = 5 × 9 = 45']},
  worked:{title:'由邊長比求面積', given:'k=3,\\ \\text{小面積}=5',
    steps:[{label:'算面積比', math:'k^2=3^2=9'},
           {label:'列式', math:'\\text{大面積}=5\\times 9'},
           {label:'計算', math:'=45'}],
    answer:'45 \\text{ 平方單位}'},
  explain:'相似形的周長比等於對應邊之比，面積比則是它的平方。由面積比反推邊長比時要記得開根號。',
  source:'自己要記'}),

card({id:'E9', grade:8, category:'geo', title:'30°–60°–90° 三角形邊長比',
  formula:'1:\\sqrt{3}:2',
  variables:[{sym:'1', desc:'30° 所對的邊（最短）'}, {sym:'√3', desc:'60° 所對的邊'},
             {sym:'2', desc:'90° 所對的斜邊（最長）'}],
  usageConditions:'題目出現 30°、60° 的直角三角形，或正三角形作高時使用。',
  triggerWords:['30 度', '60 度', '正三角形的高', '直角'],
  commonMistakes:['把 √3 放到斜邊', '短邊與長邊對應的角搞錯', '記成 1:2:√3'],
  diagramType:'SpecialRightTriangleDiagram', diagramData:{variant:'306090'},
  recall:{type:'blank', prompt:'補完 30°–60°–90° 的邊長比（依 30°、60°、90° 順序）。',
    template:'1:@1:@2', blanks:['\\sqrt{3}', '2'],
    bank:['\\sqrt{3}', '2', '\\sqrt{2}', '3'], hint1:'最小的角對最短邊，直角對斜邊。'},
  recog:{type:'choice', prompt:'30–60–90 三角形中，最長的邊對到哪一個角？',
    options:[{t:'90°'}, {t:'60°'}, {t:'30°'}, {t:'不一定'}],
    answer:0, hint1:'大角對大邊。',
    why:'直角是最大的角，所對的斜邊最長，比值為 2。'},
  apply:{type:'choice', prompt:'30–60–90 三角形斜邊長 10，最短邊長是多少？',
    given:'\\text{斜邊}=10', options:[{math:'5'}, {math:'5\\sqrt{3}'},
      {math:'10\\sqrt{3}'}, {math:'\\frac{10}{\\sqrt{3}}'}],
    answer:0, unit:'', hint1:'斜邊對應比值 2，最短邊對應 1。',
    steps:['比值 1 : √3 : 2，斜邊 2 份 = 10', '1 份 = 5', '最短邊 = 5']},
  worked:{title:'斜邊 10 求兩股', given:'\\text{斜邊}=10',
    steps:[{label:'設一份', math:'2\\text{ 份}=10\\Rightarrow 1\\text{ 份}=5'},
           {label:'30° 對邊', math:'1\\times 5=5'},
           {label:'60° 對邊', math:'\\sqrt{3}\\times 5=5\\sqrt{3}'}],
    answer:'\\text{短邊 }5,\\ \\text{長邊 }5\\sqrt{3}'},
  explain:'比值順序要跟著角度走：30° 對 1、60° 對 √3、90° 對 2。先找出「一份」是多少，再乘上各自的比值。',
  source:'自己要記'}),

card({id:'E10', grade:8, category:'geo', title:'45°–45°–90° 三角形邊長比',
  formula:'1:1:\\sqrt{2}',
  variables:[{sym:'1', desc:'兩個 45° 所對的股，兩股等長'}, {sym:'√2', desc:'斜邊'}],
  usageConditions:'等腰直角三角形、正方形對角線、45° 相關題目時使用。',
  triggerWords:['45 度', '等腰直角', '正方形對角線'],
  commonMistakes:['把 √2 記成 √3', '斜邊除以 √2 時忘記有理化'],
  diagramType:'SpecialRightTriangleDiagram', diagramData:{variant:'454590'},
  recall:{type:'blank', prompt:'補完 45°–45°–90° 的邊長比。',
    template:'1:1:@1', blanks:['\\sqrt{2}'],
    bank:['\\sqrt{2}', '\\sqrt{3}', '2', '1'], hint1:'兩股相等，斜邊是股的 √2 倍。'},
  recog:{type:'choice', prompt:'邊長 5 的正方形，對角線長是多少？',
    options:[{math:'5\\sqrt{2}'}, {math:'5\\sqrt{3}'}, {math:'10'}, {math:'25'}],
    answer:0, hint1:'對角線把正方形切成兩個 45–45–90。',
    why:'正方形對角線是等腰直角三角形的斜邊，等於股的 √2 倍，即 5√2。'},
  apply:{type:'choice', prompt:'等腰直角三角形的股長 7，斜邊長是多少？',
    given:'\\text{股}=7', options:[{math:'7\\sqrt{2}'}, {math:'14'},
      {math:'7\\sqrt{3}'}, {math:'\\frac{7}{\\sqrt{2}}'}],
    answer:0, unit:'', hint1:'股 × √2。',
    steps:['比值 1 : 1 : √2，一份 = 7', '斜邊 = √2 × 7 = 7√2']},
  worked:{title:'股長 7 求斜邊', given:'\\text{兩股都是 }7',
    steps:[{label:'用比值', math:'1:1:\\sqrt{2}'},
           {label:'一份是 7', math:'\\text{斜邊}=7\\sqrt{2}'},
           {label:'驗算', math:'7^2+7^2=98=(7\\sqrt{2})^2'}],
    answer:'7\\sqrt{2}'},
  explain:'兩個 45° 相等，所以兩股等長。設一股長為 a，用勾股定理驗算：a² + a² = 2a²，開根號得斜邊 a√2，正好是股的 √2 倍。',
  source:'自己要記'}),

card({id:'E11', grade:9, category:'geo', title:'弧長',
  formula:'\\text{弧長}=2\\pi r\\times\\frac{\\text{圓心角}}{360^\\circ}',
  variables:[{sym:'r', desc:'半徑'},
             {sym:'圓心角', desc:'扇形兩條半徑夾的角度，代入時只寫數字'}],
  usageConditions:'求扇形的弧（曲線部分）長度時使用；扇形周長還要再加兩條半徑。',
  triggerWords:['弧長', '扇形', '圓心角', '轉了幾度'],
  commonMistakes:['把扇形周長當弧長（漏加兩條半徑）', '用 πr² 算弧長', 'θ 沒有除以 360'],
  diagramType:'SectorDiagram', diagramData:{theta:120},
  recall:{type:'blank', prompt:'補完弧長公式。',
    template:'\\text{弧長}=2\\pi r\\times@1', blanks:['\\frac{\\text{圓心角}}{360^\\circ}'],
    bank:['\\frac{\\text{圓心角}}{360^\\circ}', '\\frac{360^\\circ}{\\text{圓心角}}',
          '\\text{圓心角}', '\\frac{\\text{圓心角}}{180^\\circ}'],
    hint1:'弧長是整個圓周長的「圓心角 ÷ 360°」。'},
  recog:{type:'choice', prompt:'題目問「扇形的周長」，要算什麼？',
    options:[{t:'弧長 + 兩條半徑'}, {t:'只算弧長'}, {t:'弧長 + 一條半徑'}, {t:'扇形面積'}],
    answer:0, hint1:'周長是繞著扇形邊界走一圈。',
    why:'扇形的邊界包含一段弧與兩條半徑，所以周長 = 弧長 + 2r。'},
  apply:{type:'choice', prompt:'半徑 6、圓心角 120° 的扇形，弧長是多少？',
    given:'r=6,\\ \\text{圓心角}=120^\\circ',
    options:[{math:'4\\pi'}, {math:'12\\pi'}, {math:'6\\pi'}, {math:'2\\pi'}],
    answer:0, unit:'', hint1:'120/360 = 1/3。',
    steps:['圓周長 = 2π × 6 = 12π', '120° ÷ 360° = 1/3', '弧長 = 12π × 1/3 = 4π']},
  worked:{title:'半徑 6、圓心角 120° 的弧長', given:'r=6,\\ \\text{圓心角}=120^\\circ',
    steps:[{label:'寫公式', math:'\\text{弧長}=2\\pi r\\times\\frac{\\text{圓心角}}{360^\\circ}'},
           {label:'代入', math:'=2\\pi\\times 6\\times\\frac{120}{360}'},
           {label:'約分', math:'=12\\pi\\times\\frac{1}{3}'},
           {label:'計算', math:'=4\\pi'}],
    answer:'4\\pi'},
  explain:'「圓心角 ÷ 360°」就是「這個扇形佔整個圓的幾分之幾」。弧長只算彎曲的那一段，是長度單位。',
  source:'自己要記'}),

card({id:'E12', grade:9, category:'geo', title:'扇形面積',
  formula:'\\text{扇形面積}=\\pi r^2\\times\\frac{\\text{圓心角}}{360^\\circ}',
  variables:[{sym:'r', desc:'半徑'},
             {sym:'圓心角', desc:'扇形兩條半徑夾的角度'}],
  usageConditions:'求扇形（派狀區域）的面積時使用。',
  triggerWords:['扇形面積', '圓心角', '幾分之幾的圓'],
  commonMistakes:['與弧長公式互換', '半徑忘記平方', '「圓心角 ÷ 360°」漏掉'],
  diagramType:'SectorDiagram', diagramData:{theta:120},
  recall:{type:'blank', prompt:'補完扇形面積公式。',
    template:'\\text{扇形面積}=@1\\times\\frac{\\text{圓心角}}{360^\\circ}', blanks:['\\pi r^2'],
    bank:['\\pi r^2', '2\\pi r', '\\pi r', '2\\pi r^2'],
    hint1:'先算整個圓的面積，再取「圓心角 ÷ 360°」。'},
  recog:{type:'choice', prompt:'弧長與扇形面積公式最大的差別在哪裡？',
    options:[{t:'弧長用 2πr，面積用 πr²'}, {t:'弧長要除以 360，面積不用'},
             {t:'面積不需要圓心角'}, {t:'兩者完全相同'}],
    answer:0, hint1:'一個是長度，一個是面積。',
    why:'兩者都要乘「圓心角 ÷ 360°」，差別在前半段：長度用圓周長 2πr，面積用圓面積 πr²。'},
  apply:{type:'choice', prompt:'半徑 6、圓心角 120° 的扇形面積是多少？',
    given:'r=6,\\ \\text{圓心角}=120^\\circ',
    options:[{math:'12\\pi'}, {math:'4\\pi'}, {math:'36\\pi'}, {math:'6\\pi'}],
    answer:0, unit:'', hint1:'圓面積 36π 的三分之一。',
    steps:['圓面積 = π × 6² = 36π', '120° ÷ 360° = 1/3', '扇形面積 = 36π × 1/3 = 12π']},
  worked:{title:'半徑 6、圓心角 120° 的扇形面積', given:'r=6,\\ \\text{圓心角}=120^\\circ',
    steps:[{label:'寫公式', math:'\\text{扇形面積}=\\pi r^2\\times\\frac{\\text{圓心角}}{360^\\circ}'},
           {label:'代入', math:'=\\pi\\times 6^2\\times\\frac{120}{360}'},
           {label:'約分', math:'=36\\pi\\times\\frac{1}{3}'},
           {label:'計算', math:'=12\\pi'}],
    answer:'12\\pi'},
  explain:'扇形佔整個圓的比例就是「圓心角 ÷ 360°」。弧長對應圓周長、面積對應圓面積，兩者只差在前半段。',
  source:'自己要記'}),

card({id:'E13', grade:9, category:'geo', title:'三角形面積與內切圓半徑',
  formula:'\\text{面積}=\\text{周長}\\times\\text{內切圓半徑}\\div 2',
  variables:[{sym:'周長', desc:'三角形三邊長的總和（不是半周長）'},
             {sym:'內切圓半徑', desc:'內心到三邊的距離'}],
  usageConditions:'題目同時提到三角形面積、周長與內切圓時使用；任何三角形都成立。',
  triggerWords:['內切圓', '內心', '周長', '面積'],
  commonMistakes:['把周長寫成半周長又再除以 2', '用外接圓半徑代入', '忘記最後要除以 2'],
  diagramType:'TriangleCentersDiagram', diagramData:{variant:'incenter'},
  recall:{type:'blank', prompt:'補完三角形面積與內切圓半徑的關係。',
    template:'\\text{面積}=\\text{周長}\\times\\text{內切圓半徑}@1', blanks:['\\div 2'],
    bank:['\\div 2', '\\times 2', '\\div 3', '\\div 4'],
    hint1:'把三角形切成三個以內切圓半徑為高的小三角形。'},
  recog:{type:'choice', prompt:'這個公式為什麼成立？',
    options:[{t:'內心到三邊等距，可把三角形切成三個高都是 r 的小三角形'},
             {t:'因為內切圓面積等於三角形面積'},
             {t:'因為三角形一定是直角三角形'},
             {t:'因為 r 等於三角形的高'}],
    answer:0, hint1:'想想從內心連到三個頂點會切出什麼。',
    why:'從內心連到三頂點，切出三個小三角形，各以三邊為底、內切圓半徑為高，把三塊面積加起來就是「周長 × 內切圓半徑 ÷ 2」。'},
  apply:{type:'numeric', prompt:'三角形周長 30、內切圓半徑 4，面積是多少？',
    given:'\\text{周長}=30,\\ \\text{內切圓半徑}=4', answer:'60', unit:'平方單位',
    hint1:'30 × 4 ÷ 2。',
    steps:['面積 = 30 × 4 ÷ 2', '= 120 ÷ 2 = 60']},
  worked:{title:'由周長與內切圓半徑求面積',
    given:'\\text{周長}=30,\\ \\text{內切圓半徑}=4',
    steps:[{label:'寫公式', math:'\\text{面積}=\\text{周長}\\times\\text{內切圓半徑}\\div 2'},
           {label:'代入', math:'=30\\times 4\\div 2'},
           {label:'計算', math:'=60'}],
    answer:'60 \\text{ 平方單位}'},
  explain:'公式用的是「整個周長」再除以 2，不要先算半周長又再除一次 2。內切圓半徑就是內心到三邊的距離。',
  source:'自己要記'}),

card({id:'E14', grade:9, category:'geo', title:'直角三角形的內切圓半徑',
  formula:'\\text{內切圓半徑}=(\\text{兩股和}-\\text{斜邊})\\div 2',
  variables:[{sym:'兩股', desc:'夾住直角的那兩邊'},
             {sym:'斜邊', desc:'直角所對的最長邊'},
             {sym:'內切圓半徑', desc:'內切圓的半徑，也是內心到三邊的距離'}],
  usageConditions:'只有直角三角形才能用；先確認哪一邊是斜邊。',
  triggerWords:['直角三角形', '內切圓', '半徑'],
  commonMistakes:['非直角三角形也套用', '把斜邊算進兩股', '忘記除以 2'],
  diagramType:'SpecialRightTriangleDiagram', diagramData:{variant:'incircle-right'},
  recall:{type:'blank', prompt:'補完直角三角形內切圓半徑公式。',
    template:'\\text{內切圓半徑}=(\\text{兩股和}-\\text{斜邊})@1', blanks:['\\div 2'],
    bank:['\\div 2', '\\times 2', '\\div 3', '\\div 4'],
    hint1:'兩股和減掉斜邊之後，還要再除以 2。'},
  recog:{type:'choice', prompt:'哪一種三角形才可以用這個公式？',
    options:[{t:'直角三角形'}, {t:'任意三角形'}, {t:'正三角形'}, {t:'鈍角三角形'}],
    answer:0, hint1:'公式是從直角推出來的。',
    why:'這個公式由直角三角形的切線長性質推得；其他三角形要改用「面積 = 周長 × 內切圓半徑 ÷ 2」。'},
  apply:{type:'numeric', prompt:'兩股 6、8，斜邊 10 的直角三角形，內切圓半徑是多少？',
    given:'\\text{兩股}=6,\\ 8;\\ \\text{斜邊}=10', answer:'2', unit:'', hint1:'(6 + 8 − 10) ÷ 2。',
    steps:['兩股和 = 6 + 8 = 14', '14 − 10 = 4', '4 ÷ 2 = 2']},
  worked:{title:'兩股 6、8，斜邊 10 的內切圓半徑',
    given:'\\text{兩股}=6,\\ 8;\\ \\text{斜邊}=10',
    steps:[{label:'確認直角', math:'6^2+8^2=100=10^2'},
           {label:'代入', math:'\\text{內切圓半徑}=(6+8-10)\\div 2'},
           {label:'計算', math:'=4\\div 2=2'},
           {label:'驗算', text:'面積 = 6 × 8 ÷ 2 = 24；周長 = 24，24 × 2 ÷ 2 = 24，兩種算法一致'}],
    answer:'2'},
  explain:'兩股和減掉斜邊，剛好等於內切圓半徑的 2 倍，所以要再除以 2。使用前一定要先確認是直角三角形。',
  source:'自己要記'}),

card({id:'E15', grade:7, category:'geo', title:'直角柱體積',
  formula:'\\text{體積}=\\text{底面積}\\times\\text{高}',
  variables:[{sym:'底面積', desc:'一個底面的面積（不是底面周長，也不是邊長）'},
             {sym:'高', desc:'兩個底面之間的距離，也就是側稜長'}],
  usageConditions:'柱體（上下底面全等且平行、側稜垂直底面）求體積時使用。',
  triggerWords:['柱', '體積', '水槽', '容量', '底面積'],
  commonMistakes:['把底面周長當成底面積', '把底面的邊長直接當成底面積', '單位沒有換成立方單位'],
  diagramType:'SolidNetDiagram', diagramData:{variant:'prism'},
  recall:{type:'blank', prompt:'補完直角柱體積公式。',
    template:'\\text{體積}=@1\\times@2', blanks:['\\text{底面積}', '\\text{高}'],
    bank:['\\text{底面積}', '\\text{高}', '\\text{底面周長}', '\\text{表面積}'],
    hint1:'把底面一層一層往上疊，疊「高」那麼多層。'},
  recog:{type:'choice', prompt:'底面是邊長 4 的正方形、高 10 的直角柱，底面積要代入多少？',
    options:[{math:'16'}, {math:'4'}, {math:'40'}, {math:'20'}],
    answer:0, hint1:'要代的是底「面積」，不是邊長，也不是底面周長。',
    why:'底面積 = 4 × 4 = 16（16 才是面積，4 是邊長、16 是周長的一半）。體積 = 16 × 10 = 160。'},
  apply:{type:'numeric', prompt:'底面積 24、高 10 的直角柱體積是多少？',
    given:'\\text{底面積}=24,\\ \\text{高}=10', answer:'240', unit:'立方單位',
    hint1:'24 × 10。',
    steps:['體積 = 底面積 × 高 = 24 × 10', '= 240（立方單位）']},
  worked:{title:'底面積 24、高 10 的柱體體積',
    given:'\\text{底面積}=24,\\ \\text{高}=10',
    steps:[{label:'寫公式', math:'\\text{體積}=\\text{底面積}\\times\\text{高}'},
           {label:'代入', math:'=24\\times 10'},
           {label:'計算', math:'=240'}],
    answer:'240 \\text{ 立方單位}'},
  explain:'要代的是「底面積」，不是底面周長。柱體不論底面是三角形、長方形還是圓，體積都是底面積乘高。',
  source:'自己要記'})

];
